// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Transportes;
using API.SERVICE.Mappings.Transportes;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Transportes;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Transportes;

public interface IGetChoferListUseCase
{
    Task<PagedResult<ChoferDisplay>> ExecuteAsync(ChoferFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetChoferListUseCase(IChoferRepository repository)
    : GetListUseCaseBase<Db.Choferes, ChoferFilter, ChoferDisplay>(repository), IGetChoferListUseCase
{
    protected override ChoferDisplay ToDisplay(Db.Choferes entity) => entity.ToDisplay();
}

public interface IGetChoferByIdUseCase
{
    Task<ChoferDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetChoferByIdUseCase(IChoferRepository repository)
    : GetByIdUseCaseBase<Db.Choferes, int, ChoferFilter, ChoferDisplay>(repository), IGetChoferByIdUseCase
{
    protected override string EntityName => "Chofer";

    protected override ChoferDisplay ToDisplay(Db.Choferes entity) => entity.ToDisplay();
}

public interface ICreateChoferUseCase
{
    Task<ChoferDisplay> ExecuteAsync(ChoferDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateChoferUseCase(IChoferRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.Choferes, int, ChoferFilter, ChoferDto, ChoferDisplay>(repository, cache), ICreateChoferUseCase
{
    protected override string EntityName => "Chofer";

    protected override Db.Choferes ToEntity(ChoferDto dto) => dto.ToEntity();

    protected override ChoferDisplay ToDisplay(Db.Choferes entity) => entity.ToDisplay();
}

public interface IUpdateChoferUseCase
{
    Task<ChoferDisplay> ExecuteAsync(int id, ChoferDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateChoferUseCase(IChoferRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.Choferes, int, ChoferFilter, ChoferDto, ChoferDisplay>(repository, cache), IUpdateChoferUseCase
{
    protected override string EntityName => "Chofer";

    protected override void Apply(ChoferDto dto, Db.Choferes entity) => dto.ApplyTo(entity);

    protected override ChoferDisplay ToDisplay(Db.Choferes entity) => entity.ToDisplay();
}
