// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Transportes;
using API.SERVICE.Mappings.Transportes;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Transportes;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Transportes;

public interface IGetTransporteListUseCase
{
    Task<PagedResult<TransporteDisplay>> ExecuteAsync(TransporteFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetTransporteListUseCase(ITransporteRepository repository)
    : GetListUseCaseBase<Db.Transportes, TransporteFilter, TransporteDisplay>(repository), IGetTransporteListUseCase
{
    protected override TransporteDisplay ToDisplay(Db.Transportes entity) => entity.ToDisplay();
}

public interface IGetTransporteByIdUseCase
{
    Task<TransporteDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetTransporteByIdUseCase(ITransporteRepository repository)
    : GetByIdUseCaseBase<Db.Transportes, int, TransporteFilter, TransporteDisplay>(repository), IGetTransporteByIdUseCase
{
    protected override string EntityName => "Transporte";

    protected override TransporteDisplay ToDisplay(Db.Transportes entity) => entity.ToDisplay();
}

public interface ICreateTransporteUseCase
{
    Task<TransporteDisplay> ExecuteAsync(TransporteDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateTransporteUseCase(ITransporteRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.Transportes, int, TransporteFilter, TransporteDto, TransporteDisplay>(repository, cache), ICreateTransporteUseCase
{
    protected override string EntityName => "Transporte";

    protected override Db.Transportes ToEntity(TransporteDto dto) => dto.ToEntity();

    protected override TransporteDisplay ToDisplay(Db.Transportes entity) => entity.ToDisplay();
}

public interface IUpdateTransporteUseCase
{
    Task<TransporteDisplay> ExecuteAsync(int id, TransporteDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateTransporteUseCase(ITransporteRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.Transportes, int, TransporteFilter, TransporteDto, TransporteDisplay>(repository, cache), IUpdateTransporteUseCase
{
    protected override string EntityName => "Transporte";

    protected override void Apply(TransporteDto dto, Db.Transportes entity) => dto.ApplyTo(entity);

    protected override TransporteDisplay ToDisplay(Db.Transportes entity) => entity.ToDisplay();
}
