// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Items;

/// <summary>Persistencia de dbo.SubRubros.</summary>
public partial interface ISubRubroRepository : global::API.SERVICE.Interfaces.IRepository<Db.SubRubros, int, SubRubroFilter>
{
}
