// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Clientes;
using API.SERVICE.Mappings.Clientes;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Clientes;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Clientes;

public interface IGetEntidadReciboDocumentoClienteListUseCase
{
    Task<PagedResult<EntidadReciboDocumentoClienteDisplay>> ExecuteAsync(EntidadReciboDocumentoClienteFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadReciboDocumentoClienteListUseCase(IEntidadReciboDocumentoClienteRepository repository)
    : GetListUseCaseBase<Db.EntidadRecibosDocumentosCliente, EntidadReciboDocumentoClienteFilter, EntidadReciboDocumentoClienteDisplay>(repository), IGetEntidadReciboDocumentoClienteListUseCase
{
    protected override EntidadReciboDocumentoClienteDisplay ToDisplay(Db.EntidadRecibosDocumentosCliente entity) => entity.ToDisplay();
}

public interface IGetEntidadReciboDocumentoClienteByIdUseCase
{
    Task<EntidadReciboDocumentoClienteDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadReciboDocumentoClienteByIdUseCase(IEntidadReciboDocumentoClienteRepository repository)
    : GetByIdUseCaseBase<Db.EntidadRecibosDocumentosCliente, int, EntidadReciboDocumentoClienteFilter, EntidadReciboDocumentoClienteDisplay>(repository), IGetEntidadReciboDocumentoClienteByIdUseCase
{
    protected override string EntityName => "EntidadReciboDocumentoCliente";

    protected override EntidadReciboDocumentoClienteDisplay ToDisplay(Db.EntidadRecibosDocumentosCliente entity) => entity.ToDisplay();
}
