// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Clientes;
using API.SERVICE.Mappings.Clientes;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Clientes;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Clientes;

public interface IGetEntidadChequeListUseCase
{
    Task<PagedResult<EntidadChequeDisplay>> ExecuteAsync(EntidadChequeFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadChequeListUseCase(IEntidadChequeRepository repository)
    : GetListUseCaseBase<Db.EntidadesCheques, EntidadChequeFilter, EntidadChequeDisplay>(repository), IGetEntidadChequeListUseCase
{
    protected override EntidadChequeDisplay ToDisplay(Db.EntidadesCheques entity) => entity.ToDisplay();
}

public interface IGetEntidadChequeByIdUseCase
{
    Task<EntidadChequeDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadChequeByIdUseCase(IEntidadChequeRepository repository)
    : GetByIdUseCaseBase<Db.EntidadesCheques, int, EntidadChequeFilter, EntidadChequeDisplay>(repository), IGetEntidadChequeByIdUseCase
{
    protected override string EntityName => "EntidadCheque";

    protected override EntidadChequeDisplay ToDisplay(Db.EntidadesCheques entity) => entity.ToDisplay();
}
