// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Clientes;
using API.SERVICE.Mappings.Clientes;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Clientes;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Clientes;

public interface IGetEntidadReciboListUseCase
{
    Task<PagedResult<EntidadReciboDisplay>> ExecuteAsync(EntidadReciboFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadReciboListUseCase(IEntidadReciboRepository repository)
    : GetListUseCaseBase<Db.EntidadesRecibos, EntidadReciboFilter, EntidadReciboDisplay>(repository), IGetEntidadReciboListUseCase
{
    protected override EntidadReciboDisplay ToDisplay(Db.EntidadesRecibos entity) => entity.ToDisplay();
}

public interface IGetEntidadReciboByIdUseCase
{
    Task<EntidadReciboDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadReciboByIdUseCase(IEntidadReciboRepository repository)
    : GetByIdUseCaseBase<Db.EntidadesRecibos, int, EntidadReciboFilter, EntidadReciboDisplay>(repository), IGetEntidadReciboByIdUseCase
{
    protected override string EntityName => "EntidadRecibo";

    protected override EntidadReciboDisplay ToDisplay(Db.EntidadesRecibos entity) => entity.ToDisplay();
}
