// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Clientes;
using API.SERVICE.Models.Clientes;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Clientes;

public sealed partial class EntidadChequeRepository : EfRepository<Db.EntidadesCheques, int, EntidadChequeFilter>, IEntidadChequeRepository
{
    public EntidadChequeRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.EntidadesCheques> ApplyFilter(IQueryable<Db.EntidadesCheques> query, EntidadChequeFilter filter)
    {
        if (filter.IdEntidad is not null)
            query = query.Where(x => x.IdEntidad == filter.IdEntidad);

        if (filter.IdBanco is not null)
            query = query.Where(x => x.IdBanco == filter.IdBanco);

        if (filter.IdSucursal is not null)
            query = query.Where(x => x.IdSucursal == filter.IdSucursal);

        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        if (filter.IdUsuario is not null)
            query = query.Where(x => x.IdUsuario == filter.IdUsuario);

        if (filter.IdEntidadRecibo is not null)
            query = query.Where(x => x.IdEntidadRecibo == filter.IdEntidadRecibo);

        if (filter.IdProveedorRecibo is not null)
            query = query.Where(x => x.IdProveedorRecibo == filter.IdProveedorRecibo);

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        if (filter.IdSucursalEmpresa is not null)
            query = query.Where(x => x.IdSucursalEmpresa == filter.IdSucursalEmpresa);

        if (filter.IdEntidadReciboTipo is not null)
            query = query.Where(x => x.IdEntidadReciboTipo == filter.IdEntidadReciboTipo);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        if (filter.FechaRecepcionDesde is not null)
            query = query.Where(x => x.FechaRecepcion >= filter.FechaRecepcionDesde.Value);

        if (filter.FechaRecepcionHasta is not null)
        {
            var hasta = filter.FechaRecepcionHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaRecepcion < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.EntidadesCheques> ApplyDefaultOrder(IQueryable<Db.EntidadesCheques> query) =>
        query.OrderByDescending(x => x.IdEntidadCheque);
}
