// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Clientes;
using API.SERVICE.Models.Clientes;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Clientes;

public sealed partial class EntidadReciboRepository : EfRepository<Db.EntidadesRecibos, int, EntidadReciboFilter>, IEntidadReciboRepository
{
    public EntidadReciboRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.EntidadesRecibos> ApplyFilter(IQueryable<Db.EntidadesRecibos> query, EntidadReciboFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.RazonSocial != null && x.RazonSocial.Contains(q))
                || (x.Numero != null && x.Numero.Contains(q)));
        }

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        if (filter.IdEntidad is not null)
            query = query.Where(x => x.IdEntidad == filter.IdEntidad);

        if (filter.IdCategoriaIva is not null)
            query = query.Where(x => x.IdCategoriaIva == filter.IdCategoriaIva);

        if (filter.IdUsuario is not null)
            query = query.Where(x => x.IdUsuario == filter.IdUsuario);

        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        if (filter.IdPlanillaCaja is not null)
            query = query.Where(x => x.IdPlanillaCaja == filter.IdPlanillaCaja);

        if (filter.IdSucursal is not null)
            query = query.Where(x => x.IdSucursal == filter.IdSucursal);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        if (filter.FechaEmisionDesde is not null)
            query = query.Where(x => x.FechaEmision >= filter.FechaEmisionDesde.Value);

        if (filter.FechaEmisionHasta is not null)
        {
            var hasta = filter.FechaEmisionHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaEmision < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.EntidadesRecibos> ApplyDefaultOrder(IQueryable<Db.EntidadesRecibos> query) =>
        query.OrderByDescending(x => x.IdEntidadRecibo);
}
