// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Clientes;
using API.SERVICE.Models.Clientes;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Clientes;

public sealed partial class EntidadReciboDocumentoClienteRepository : EfRepository<Db.EntidadRecibosDocumentosCliente, int, EntidadReciboDocumentoClienteFilter>, IEntidadReciboDocumentoClienteRepository
{
    public EntidadReciboDocumentoClienteRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.EntidadRecibosDocumentosCliente> ApplyFilter(IQueryable<Db.EntidadRecibosDocumentosCliente> query, EntidadReciboDocumentoClienteFilter filter)
    {
        if (filter.IdEntidadRecibo is not null)
            query = query.Where(x => x.IdEntidadRecibo == filter.IdEntidadRecibo);

        if (filter.IdEntidad is not null)
            query = query.Where(x => x.IdEntidad == filter.IdEntidad);

        if (filter.IdDocumentoCliente is not null)
            query = query.Where(x => x.IdDocumentoCliente == filter.IdDocumentoCliente);

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        return query;
    }

    protected override IOrderedQueryable<Db.EntidadRecibosDocumentosCliente> ApplyDefaultOrder(IQueryable<Db.EntidadRecibosDocumentosCliente> query) =>
        query.OrderByDescending(x => x.IdEntidadReciboDocumentoCliente);
}
