// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class ComboMappings
{
    public static ComboDisplay ToDisplay(this Db.Combos entity) => new()
    {
        IdCombo = entity.IdCombo,
        Nombre = entity.Nombre,
        PrecioCombo = entity.PrecioCombo,
        FechaInicio = entity.FechaInicio,
        FechaFin = entity.FechaFin,
        IdSucursal = entity.IdSucursal,
    };

    public static Db.Combos ToEntity(this ComboDto dto)
    {
        var entity = new Db.Combos();
        entity.IdCombo = dto.IdCombo!.Value;
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this ComboDto dto, Db.Combos entity)
    {
        entity.Nombre = dto.Nombre;
        entity.PrecioCombo = dto.PrecioCombo;
        entity.FechaInicio = dto.FechaInicio;
        entity.FechaFin = dto.FechaFin;
        entity.IdSucursal = dto.IdSucursal;
    }
}
