// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class ItemNroSerieMappings
{
    public static ItemNroSerieDisplay ToDisplay(this Db.ItemsNroSeries entity) => new()
    {
        IdItemNroSerie = entity.IdItemNroSerie,
        IdItem = entity.IdItem,
        NroSerie = entity.NroSerie,
        IdComprobanteTipo = entity.IdComprobanteTipo,
        IdComprobante = entity.IdComprobante,
        IdDocumentoClienteDetalle = entity.IdDocumentoClienteDetalle,
        IdSucursal = entity.IdSucursal,
        Estado = entity.Estado,
    };

    public static Db.ItemsNroSeries ToEntity(this ItemNroSerieDto dto)
    {
        var entity = new Db.ItemsNroSeries();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this ItemNroSerieDto dto, Db.ItemsNroSeries entity)
    {
        entity.IdItem = dto.IdItem;
        entity.NroSerie = dto.NroSerie;
        entity.IdComprobanteTipo = dto.IdComprobanteTipo;
        entity.IdComprobante = dto.IdComprobante;
        entity.IdDocumentoClienteDetalle = dto.IdDocumentoClienteDetalle;
        entity.IdSucursal = dto.IdSucursal;
        entity.Estado = dto.Estado;
    }
}
