// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class ItemEnvaseMappings
{
    public static ItemEnvaseDisplay ToDisplay(this Db.ItemsEnvanses entity) => new()
    {
        IdItemEnvase = entity.IdItemEnvase,
        IdItem = entity.IdItem,
        IdEnvase = entity.IdEnvase,
        CantidadKg = entity.CantidadKg,
        CantidadEnvases = entity.CantidadEnvases,
        PesoEnvase = entity.PesoEnvase,
        Activo = entity.Activo,
    };

    public static Db.ItemsEnvanses ToEntity(this ItemEnvaseDto dto)
    {
        var entity = new Db.ItemsEnvanses();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this ItemEnvaseDto dto, Db.ItemsEnvanses entity)
    {
        entity.IdItem = dto.IdItem;
        entity.IdEnvase = dto.IdEnvase;
        entity.CantidadKg = dto.CantidadKg;
        entity.CantidadEnvases = dto.CantidadEnvases;
        entity.PesoEnvase = dto.PesoEnvase;
        entity.Activo = dto.Activo;
    }
}
