// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class ItemPrecioActualizacionMappings
{
    public static ItemPrecioActualizacionDisplay ToDisplay(this Db.ItemsPreciosActualizacion entity) => new()
    {
        IdItemPrecioActulizacion = entity.IdItemPrecioActulizacion,
        IdItem = entity.IdItem,
        PrecioActual = entity.PrecioActual,
        PrecioNuevo = entity.PrecioNuevo,
        Rentabilidad = entity.Rentabilidad,
        FechaActualizacion = entity.FechaActualizacion,
        IdUsario = entity.IdUsario,
    };
}
