// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class ItemImpuestoMappings
{
    public static ItemImpuestoDisplay ToDisplay(this Db.ItemsImpuestos entity) => new()
    {
        IdItemImpuesto = entity.IdItemImpuesto,
        IdItem = entity.IdItem,
        IdImpuesto = entity.IdImpuesto,
    };

    public static Db.ItemsImpuestos ToEntity(this ItemImpuestoDto dto)
    {
        var entity = new Db.ItemsImpuestos();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this ItemImpuestoDto dto, Db.ItemsImpuestos entity)
    {
        entity.IdItem = dto.IdItem;
        entity.IdImpuesto = dto.IdImpuesto;
    }
}
