// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class MarcaMappings
{
    public static MarcaDisplay ToDisplay(this Db.Marcas entity) => new()
    {
        IdMarca = entity.IdMarca,
        Descripcion = entity.Descripcion,
        IdEmpresa = entity.IdEmpresa,
        Estado = entity.Estado,
    };

    public static Db.Marcas ToEntity(this MarcaDto dto)
    {
        var entity = new Db.Marcas();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this MarcaDto dto, Db.Marcas entity)
    {
        entity.Descripcion = dto.Descripcion;
        entity.IdEmpresa = dto.IdEmpresa;
        entity.Estado = dto.Estado;
    }
}
