// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class ModeloMappings
{
    public static ModeloDisplay ToDisplay(this Db.Modelos entity) => new()
    {
        IdModelo = entity.IdModelo,
        Descripcion = entity.Descripcion,
        IdMarca = entity.IdMarca,
        IdEmpresa = entity.IdEmpresa,
        Estado = entity.Estado,
    };

    public static Db.Modelos ToEntity(this ModeloDto dto)
    {
        var entity = new Db.Modelos();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this ModeloDto dto, Db.Modelos entity)
    {
        entity.Descripcion = dto.Descripcion;
        entity.IdMarca = dto.IdMarca;
        entity.IdEmpresa = dto.IdEmpresa;
        entity.Estado = dto.Estado;
    }
}
