// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class OfertaAgotamientoMappings
{
    public static OfertaAgotamientoDisplay ToDisplay(this Db.OfertasAgotamiento entity) => new()
    {
        IdOferta = entity.IdOferta,
        IdItem = entity.IdItem,
        IdSucursal = entity.IdSucursal,
        CantidadObjetivo = entity.CantidadObjetivo,
        CantidadDisponible = entity.CantidadDisponible,
    };
}
