// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class OfertaMappings
{
    public static OfertaDisplay ToDisplay(this Db.Ofertas entity) => new()
    {
        IdOferta = entity.IdOferta,
        IdItem = entity.IdItem,
        Nombre = entity.Nombre,
        TipoOferta = entity.TipoOferta,
        Descuento = entity.Descuento,
        FechaInicio = entity.FechaInicio,
        FechaFin = entity.FechaFin,
        CantidadRequerida = entity.CantidadRequerida,
        CantidadGratis = entity.CantidadGratis,
        IdEstado = entity.IdEstado,
        CantidadStock = entity.CantidadStock,
        PrecioConDescuento = entity.PrecioConDescuento,
    };
}
