// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class ProductoComboMappings
{
    public static ProductoComboDisplay ToDisplay(this Db.ProductosCombos entity) => new()
    {
        IdComboProducto = entity.IdComboProducto,
        IdCombo = entity.IdCombo,
        IdItem = entity.IdItem,
        Cantidad = entity.Cantidad,
    };

    public static Db.ProductosCombos ToEntity(this ProductoComboDto dto)
    {
        var entity = new Db.ProductosCombos();
        entity.IdComboProducto = dto.IdComboProducto!.Value;
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this ProductoComboDto dto, Db.ProductosCombos entity)
    {
        entity.IdCombo = dto.IdCombo;
        entity.IdItem = dto.IdItem;
        entity.Cantidad = dto.Cantidad;
    }
}
