// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class RubroActualizacionMappings
{
    public static RubroActualizacionDisplay ToDisplay(this Db.RubrosActualizacion entity) => new()
    {
        IdRubroActualizacion = entity.IdRubroActualizacion,
        IdRubro = entity.IdRubro,
        Alicuota = entity.Alicuota,
        IdUsuario = entity.IdUsuario,
        FechaActualizacion = entity.FechaActualizacion,
    };
}
