// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Items;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Items;

public static partial class UbicacionMappings
{
    public static UbicacionDisplay ToDisplay(this Db.Ubicaciones entity) => new()
    {
        IdUbicacion = entity.IdUbicacion,
        Descripcion = entity.Descripcion,
        IdEmpresa = entity.IdEmpresa,
        Estado = entity.Estado,
    };

    public static Db.Ubicaciones ToEntity(this UbicacionDto dto)
    {
        var entity = new Db.Ubicaciones();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this UbicacionDto dto, Db.Ubicaciones entity)
    {
        entity.Descripcion = dto.Descripcion;
        entity.IdEmpresa = dto.IdEmpresa;
        entity.Estado = dto.Estado;
    }
}
