// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Entidades;
using API.SERVICE.Models.Entidades;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Entidades;

public sealed partial class EntidadEntidadTipoRepository : EfRepository<Db.EntidadesEntidadesTipo, int, EntidadEntidadTipoFilter>, IEntidadEntidadTipoRepository
{
    public EntidadEntidadTipoRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.EntidadesEntidadesTipo> ApplyFilter(IQueryable<Db.EntidadesEntidadesTipo> query, EntidadEntidadTipoFilter filter)
    {
        if (filter.IdEntidad is not null)
            query = query.Where(x => x.IdEntidad == filter.IdEntidad);

        if (filter.IdEntidadTipo is not null)
            query = query.Where(x => x.IdEntidadTipo == filter.IdEntidadTipo);

        return query;
    }

    protected override IOrderedQueryable<Db.EntidadesEntidadesTipo> ApplyDefaultOrder(IQueryable<Db.EntidadesEntidadesTipo> query) =>
        query.OrderByDescending(x => x.IdEntidadEntidadTipo);
}
