// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Entidades;
using API.SERVICE.Models.Entidades;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Entidades;

public sealed partial class EntidadTipoRepository : EfRepository<Db.EntidadesTipo, int, EntidadTipoFilter>, IEntidadTipoRepository
{
    public EntidadTipoRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.EntidadesTipo> ApplyFilter(IQueryable<Db.EntidadesTipo> query, EntidadTipoFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        return query;
    }

    protected override IOrderedQueryable<Db.EntidadesTipo> ApplyDefaultOrder(IQueryable<Db.EntidadesTipo> query) =>
        query.OrderBy(x => x.Descripcion);
}
