// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Entidades;
using API.SERVICE.Models.Entidades;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Entidades;

public sealed partial class EntidadCategoriaRepository : EfRepository<Db.EntidadesCategorias, int, EntidadCategoriaFilter>, IEntidadCategoriaRepository
{
    public EntidadCategoriaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.EntidadesCategorias> ApplyFilter(IQueryable<Db.EntidadesCategorias> query, EntidadCategoriaFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        return query;
    }

    protected override IOrderedQueryable<Db.EntidadesCategorias> ApplyDefaultOrder(IQueryable<Db.EntidadesCategorias> query) =>
        query.OrderBy(x => x.Descripcion);
}
