// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Entidades;
using API.SERVICE.Models.Entidades;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Entidades;

public sealed partial class EntidadFacturacionRepository : EfRepository<Db.EntidadesFacturacion, int, EntidadFacturacionFilter>, IEntidadFacturacionRepository
{
    public EntidadFacturacionRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.EntidadesFacturacion> ApplyFilter(IQueryable<Db.EntidadesFacturacion> query, EntidadFacturacionFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.RazonSocial != null && x.RazonSocial.Contains(q))
                || (x.Cuit != null && x.Cuit.Contains(q)));
        }

        if (filter.IdEntidad is not null)
            query = query.Where(x => x.IdEntidad == filter.IdEntidad);

        if (filter.IdCategoriaIva is not null)
            query = query.Where(x => x.IdCategoriaIva == filter.IdCategoriaIva);

        if (filter.IdProvincia is not null)
            query = query.Where(x => x.IdProvincia == filter.IdProvincia);

        if (filter.IdLocalidad is not null)
            query = query.Where(x => x.IdLocalidad == filter.IdLocalidad);

        return query;
    }

    protected override IOrderedQueryable<Db.EntidadesFacturacion> ApplyDefaultOrder(IQueryable<Db.EntidadesFacturacion> query) =>
        query.OrderByDescending(x => x.IdEntidadFacturacion);
}
