// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Compras;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Compras;

/// <summary>Persistencia de dbo.DocumentosProveedorDetalle.</summary>
public partial interface IDocumentoProveedorDetalleRepository : global::API.SERVICE.Interfaces.IReadRepository<Db.DocumentosProveedorDetalle, long, DocumentoProveedorDetalleFilter>
{
}
