// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Sistema;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Sistema;

public static partial class ConsultaMappings
{
    public static ConsultaDisplay ToDisplay(this Db.Consultas entity) => new()
    {
        IdConsulta = entity.IdConsulta,
        Nombre = entity.Nombre,
        Telefono = entity.Telefono,
        Email = entity.Email,
        NombreEmpresa = entity.NombreEmpresa,
        RubroEmpresa = entity.RubroEmpresa,
        Sucursales = entity.Sucursales,
        IdLocalidad = entity.IdLocalidad,
        IdProvincia = entity.IdProvincia,
        Observaciones = entity.Observaciones,
        Fecha = entity.Fecha,
    };
}
