// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Sistema;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Sistema;

public static partial class ConsultaDetalleMappings
{
    public static ConsultaDetalleDisplay ToDisplay(this Db.ConsultasDetalle entity) => new()
    {
        IdConsultaDetalle = entity.IdConsultaDetalle,
        IdConsulta = entity.IdConsulta,
        IdMotivo = entity.IdMotivo,
    };
}
