// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Sistema;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Sistema;

public static partial class UsuarioMappings
{
    public static UsuarioDisplay ToDisplay(this Db.Usuarios entity) => new()
    {
        IdUsuario = entity.IdUsuario,
        Nombre = entity.Nombre,
        Email = entity.Email,
        Usuario = entity.Usuario,
        UserId = entity.UserId,
        Imagen = entity.Imagen,
        IdSucursal = entity.IdSucursal,
        IdEstado = entity.IdEstado,
    };

    public static Db.Usuarios ToEntity(this UsuarioDto dto)
    {
        var entity = new Db.Usuarios();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this UsuarioDto dto, Db.Usuarios entity)
    {
        entity.Nombre = dto.Nombre;
        entity.Email = dto.Email;
        entity.Imagen = dto.Imagen;
        entity.IdSucursal = dto.IdSucursal;
        entity.IdEstado = dto.IdEstado;
    }
}
