// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Stock;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Stock;

/// <summary>Persistencia de dbo.ItemsMovimientosDetalles.</summary>
public partial interface IItemMovimientoDetalleRepository : global::API.SERVICE.Interfaces.IReadRepository<Db.ItemsMovimientosDetalles, int, ItemMovimientoDetalleFilter>
{
}
