// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Geografia;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Geografia;

/// <summary>Persistencia de dbo.Provincias.</summary>
public partial interface IProvinciaRepository : global::API.SERVICE.Interfaces.IRepository<Db.Provincias, int, ProvinciaFilter>
{
}
