// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Transportes;

/// <summary>Salida de dbo.Choferes.</summary>
public sealed partial class ChoferDisplay
{
    public int IdChofer { get; init; }
    public string? RazonSocial { get; init; }
    public int? IdTransporte { get; init; }
    public int? IdCategoriaIva { get; init; }
    public string? NroDoc { get; init; }
    public int? IdProvincia { get; init; }
    public int? IdLocalidad { get; init; }
    public string? Calle { get; init; }
    public string? Nro { get; init; }
    public string? Telefono { get; init; }
    public string? Mail { get; init; }
    public int? IdEmpresa { get; init; }
    public int? Estado { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.Choferes.</summary>
public sealed partial class ChoferDto
{
    [MaxLength(50)]
    public string? RazonSocial { get; set; }

    public int? IdTransporte { get; set; }

    public int? IdCategoriaIva { get; set; }

    [MaxLength(50)]
    public string? NroDoc { get; set; }

    public int? IdProvincia { get; set; }

    public int? IdLocalidad { get; set; }

    [MaxLength(50)]
    public string? Calle { get; set; }

    [MaxLength(50)]
    public string? Nro { get; set; }

    [MaxLength(50)]
    public string? Telefono { get; set; }

    [MaxLength(50)]
    public string? Mail { get; set; }

    public int? IdEmpresa { get; set; }

    public int? Estado { get; set; }
}

/// <summary>Filtros del listado de dbo.Choferes.</summary>
public sealed partial class ChoferFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en RazonSocial.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdTransporte { get; set; }

    public int? IdCategoriaIva { get; set; }

    public int? IdProvincia { get; set; }

    public int? IdLocalidad { get; set; }

    public int? IdEmpresa { get; set; }

    public int? Estado { get; set; }
}
