// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Entidades;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Entidades;

/// <summary>Persistencia de dbo.EntidadesTipo.</summary>
public partial interface IEntidadTipoRepository : global::API.SERVICE.Interfaces.IReadRepository<Db.EntidadesTipo, int, EntidadTipoFilter>
{
}
