// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Bancos;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Bancos;

/// <summary>Persistencia de dbo.OrdenesExrtacciones.</summary>
public partial interface IOrdenExtraccionRepository : global::API.SERVICE.Interfaces.IReadRepository<Db.OrdenesExrtacciones, int, OrdenExtraccionFilter>
{
}
