// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Comprobantes;
using API.SERVICE.Mappings.Comprobantes;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Comprobantes;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Comprobantes;

public static class ComprobanteTipoCacheKeys
{
    public static readonly string Lookup = CacheKeys.For("Comprobantes", "ComprobanteTipo", "lookup");
}

public interface IGetComprobanteTipoListUseCase
{
    Task<PagedResult<ComprobanteTipoDisplay>> ExecuteAsync(ComprobanteTipoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetComprobanteTipoListUseCase(IComprobanteTipoRepository repository)
    : GetListUseCaseBase<Db.ComprobantesTipo, ComprobanteTipoFilter, ComprobanteTipoDisplay>(repository), IGetComprobanteTipoListUseCase
{
    protected override ComprobanteTipoDisplay ToDisplay(Db.ComprobantesTipo entity) => entity.ToDisplay();
}

public interface IGetComprobanteTipoByIdUseCase
{
    Task<ComprobanteTipoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetComprobanteTipoByIdUseCase(IComprobanteTipoRepository repository)
    : GetByIdUseCaseBase<Db.ComprobantesTipo, int, ComprobanteTipoFilter, ComprobanteTipoDisplay>(repository), IGetComprobanteTipoByIdUseCase
{
    protected override string EntityName => "ComprobanteTipo";

    protected override ComprobanteTipoDisplay ToDisplay(Db.ComprobantesTipo entity) => entity.ToDisplay();
}

public interface IGetComprobanteTipoLookupUseCase
{
    Task<IReadOnlyList<ComprobanteTipoDisplay>> ExecuteAsync(CancellationToken cancellationToken = default);
}

public sealed partial class GetComprobanteTipoLookupUseCase(IComprobanteTipoRepository repository, IRedisCacheService cache)
    : GetLookupUseCaseBase<Db.ComprobantesTipo, int, ComprobanteTipoFilter, ComprobanteTipoDisplay>(repository, cache), IGetComprobanteTipoLookupUseCase
{
    protected override string CacheKey => ComprobanteTipoCacheKeys.Lookup;

    protected override ComprobanteTipoDisplay ToDisplay(Db.ComprobantesTipo entity) => entity.ToDisplay();
}

public interface ICreateComprobanteTipoUseCase
{
    Task<ComprobanteTipoDisplay> ExecuteAsync(ComprobanteTipoDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateComprobanteTipoUseCase(IComprobanteTipoRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.ComprobantesTipo, int, ComprobanteTipoFilter, ComprobanteTipoDto, ComprobanteTipoDisplay>(repository, cache), ICreateComprobanteTipoUseCase
{
    protected override string EntityName => "ComprobanteTipo";

    protected override string? CacheKey => ComprobanteTipoCacheKeys.Lookup;

    protected override Db.ComprobantesTipo ToEntity(ComprobanteTipoDto dto) => dto.ToEntity();

    protected override ComprobanteTipoDisplay ToDisplay(Db.ComprobantesTipo entity) => entity.ToDisplay();
}

public interface IUpdateComprobanteTipoUseCase
{
    Task<ComprobanteTipoDisplay> ExecuteAsync(int id, ComprobanteTipoDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateComprobanteTipoUseCase(IComprobanteTipoRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.ComprobantesTipo, int, ComprobanteTipoFilter, ComprobanteTipoDto, ComprobanteTipoDisplay>(repository, cache), IUpdateComprobanteTipoUseCase
{
    protected override string EntityName => "ComprobanteTipo";

    protected override string? CacheKey => ComprobanteTipoCacheKeys.Lookup;

    protected override void Apply(ComprobanteTipoDto dto, Db.ComprobantesTipo entity) => dto.ApplyTo(entity);

    protected override ComprobanteTipoDisplay ToDisplay(Db.ComprobantesTipo entity) => entity.ToDisplay();
}
