// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Comprobantes;
using API.SERVICE.Mappings.Comprobantes;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Comprobantes;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Comprobantes;

public interface IGetPuntoVentaListUseCase
{
    Task<PagedResult<PuntoVentaDisplay>> ExecuteAsync(PuntoVentaFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetPuntoVentaListUseCase(IPuntoVentaRepository repository)
    : GetListUseCaseBase<Db.PuntosVenta, PuntoVentaFilter, PuntoVentaDisplay>(repository), IGetPuntoVentaListUseCase
{
    protected override PuntoVentaDisplay ToDisplay(Db.PuntosVenta entity) => entity.ToDisplay();
}

public interface IGetPuntoVentaByIdUseCase
{
    Task<PuntoVentaDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetPuntoVentaByIdUseCase(IPuntoVentaRepository repository)
    : GetByIdUseCaseBase<Db.PuntosVenta, int, PuntoVentaFilter, PuntoVentaDisplay>(repository), IGetPuntoVentaByIdUseCase
{
    protected override string EntityName => "PuntoVenta";

    protected override PuntoVentaDisplay ToDisplay(Db.PuntosVenta entity) => entity.ToDisplay();
}

public interface ICreatePuntoVentaUseCase
{
    Task<PuntoVentaDisplay> ExecuteAsync(PuntoVentaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreatePuntoVentaUseCase(IPuntoVentaRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.PuntosVenta, int, PuntoVentaFilter, PuntoVentaDto, PuntoVentaDisplay>(repository, cache), ICreatePuntoVentaUseCase
{
    protected override string EntityName => "PuntoVenta";

    protected override Db.PuntosVenta ToEntity(PuntoVentaDto dto) => dto.ToEntity();

    protected override PuntoVentaDisplay ToDisplay(Db.PuntosVenta entity) => entity.ToDisplay();
}

public interface IUpdatePuntoVentaUseCase
{
    Task<PuntoVentaDisplay> ExecuteAsync(int id, PuntoVentaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdatePuntoVentaUseCase(IPuntoVentaRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.PuntosVenta, int, PuntoVentaFilter, PuntoVentaDto, PuntoVentaDisplay>(repository, cache), IUpdatePuntoVentaUseCase
{
    protected override string EntityName => "PuntoVenta";

    protected override void Apply(PuntoVentaDto dto, Db.PuntosVenta entity) => dto.ApplyTo(entity);

    protected override PuntoVentaDisplay ToDisplay(Db.PuntosVenta entity) => entity.ToDisplay();
}
