// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Geografia;
using API.SERVICE.Mappings.Geografia;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Geografia;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Geografia;

public static class ProvinciaCacheKeys
{
    public static readonly string Lookup = CacheKeys.For("Geografia", "Provincia", "lookup");
}

public interface IGetProvinciaListUseCase
{
    Task<PagedResult<ProvinciaDisplay>> ExecuteAsync(ProvinciaFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetProvinciaListUseCase(IProvinciaRepository repository)
    : GetListUseCaseBase<Db.Provincias, ProvinciaFilter, ProvinciaDisplay>(repository), IGetProvinciaListUseCase
{
    protected override ProvinciaDisplay ToDisplay(Db.Provincias entity) => entity.ToDisplay();
}

public interface IGetProvinciaByIdUseCase
{
    Task<ProvinciaDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetProvinciaByIdUseCase(IProvinciaRepository repository)
    : GetByIdUseCaseBase<Db.Provincias, int, ProvinciaFilter, ProvinciaDisplay>(repository), IGetProvinciaByIdUseCase
{
    protected override string EntityName => "Provincia";

    protected override ProvinciaDisplay ToDisplay(Db.Provincias entity) => entity.ToDisplay();
}

public interface IGetProvinciaLookupUseCase
{
    Task<IReadOnlyList<ProvinciaDisplay>> ExecuteAsync(CancellationToken cancellationToken = default);
}

public sealed partial class GetProvinciaLookupUseCase(IProvinciaRepository repository, IRedisCacheService cache)
    : GetLookupUseCaseBase<Db.Provincias, int, ProvinciaFilter, ProvinciaDisplay>(repository, cache), IGetProvinciaLookupUseCase
{
    protected override string CacheKey => ProvinciaCacheKeys.Lookup;

    protected override ProvinciaDisplay ToDisplay(Db.Provincias entity) => entity.ToDisplay();
}

public interface ICreateProvinciaUseCase
{
    Task<ProvinciaDisplay> ExecuteAsync(ProvinciaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateProvinciaUseCase(IProvinciaRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.Provincias, int, ProvinciaFilter, ProvinciaDto, ProvinciaDisplay>(repository, cache), ICreateProvinciaUseCase
{
    protected override string EntityName => "Provincia";

    protected override string? CacheKey => ProvinciaCacheKeys.Lookup;

    protected override Db.Provincias ToEntity(ProvinciaDto dto) => dto.ToEntity();

    protected override ProvinciaDisplay ToDisplay(Db.Provincias entity) => entity.ToDisplay();
}

public interface IUpdateProvinciaUseCase
{
    Task<ProvinciaDisplay> ExecuteAsync(int id, ProvinciaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateProvinciaUseCase(IProvinciaRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.Provincias, int, ProvinciaFilter, ProvinciaDto, ProvinciaDisplay>(repository, cache), IUpdateProvinciaUseCase
{
    protected override string EntityName => "Provincia";

    protected override string? CacheKey => ProvinciaCacheKeys.Lookup;

    protected override void Apply(ProvinciaDto dto, Db.Provincias entity) => dto.ApplyTo(entity);

    protected override ProvinciaDisplay ToDisplay(Db.Provincias entity) => entity.ToDisplay();
}
