// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.UseCases.Bancos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers.Bancos;

/// <summary>dbo.BancosChequeras.</summary>
[ApiController]
[Authorize]
[Route("api/[controller]")]
[Tags("Bancos")]
[Produces("application/json")]
[ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status401Unauthorized)]
public sealed partial class BancoChequeraController : ControllerBase
{
    /// <summary>Listado paginado y filtrado.</summary>
    [HttpGet]
    [ProducesResponseType(typeof(PagedResult<BancoChequeraDisplay>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<PagedResult<BancoChequeraDisplay>>> GetList([FromQuery] BancoChequeraFilter filter, [FromServices] IGetBancoChequeraListUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(filter, cancellationToken));

    /// <summary>Detalle por Id.</summary>
    [HttpGet("{id:int}")]
    [ProducesResponseType(typeof(BancoChequeraDisplay), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<BancoChequeraDisplay>> GetById(int id, [FromServices] IGetBancoChequeraByIdUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(id, cancellationToken));

    /// <summary>Alta.</summary>
    [HttpPost]
    [ProducesResponseType(typeof(BancoChequeraDisplay), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status409Conflict)]
    public async Task<ActionResult<BancoChequeraDisplay>> Create([FromBody] BancoChequeraDto dto, [FromServices] ICreateBancoChequeraUseCase useCase, CancellationToken cancellationToken)
    {
        var created = await useCase.ExecuteAsync(dto, cancellationToken);
        return CreatedAtAction(nameof(GetById), new { id = created.IdBancosChequeras }, created);
    }

    /// <summary>Modificación.</summary>
    [HttpPut("{id:int}")]
    [ProducesResponseType(typeof(BancoChequeraDisplay), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status409Conflict)]
    public async Task<ActionResult<BancoChequeraDisplay>> Update(int id, [FromBody] BancoChequeraDto dto, [FromServices] IUpdateBancoChequeraUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(id, dto, cancellationToken));
}
