// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.UseCases.Bancos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers.Bancos;

/// <summary>dbo.ConciliacionBancariaDetalle. Solo lectura: las altas se hacen desde el flujo de negocio correspondiente.</summary>
[ApiController]
[Authorize]
[Route("api/[controller]")]
[Tags("Bancos")]
[Produces("application/json")]
[ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status401Unauthorized)]
public sealed partial class ConciliacionBancariaDetalleController : ControllerBase
{
    /// <summary>Listado paginado y filtrado.</summary>
    [HttpGet]
    [ProducesResponseType(typeof(PagedResult<ConciliacionBancariaDetalleDisplay>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<PagedResult<ConciliacionBancariaDetalleDisplay>>> GetList([FromQuery] ConciliacionBancariaDetalleFilter filter, [FromServices] IGetConciliacionBancariaDetalleListUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(filter, cancellationToken));

    /// <summary>Detalle por Id.</summary>
    [HttpGet("{id:long}")]
    [ProducesResponseType(typeof(ConciliacionBancariaDetalleDisplay), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ConciliacionBancariaDetalleDisplay>> GetById(long id, [FromServices] IGetConciliacionBancariaDetalleByIdUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(id, cancellationToken));
}
