// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Stock;

/// <summary>Salida de dbo.EntidadesCtaCteStockMovimientosDetalle.</summary>
public sealed partial class EntidadCtaCteStockMovimientoDetalleDisplay
{
    public int IdEntidadCtaCteStockMovimientoDetalle { get; init; }
    public int? IdEntidad { get; init; }
    public int? IdComprobante { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public string? Concepto { get; init; }
    public int? IdItem { get; init; }
    public decimal? Total { get; init; }
    public decimal? Saldo { get; init; }
    public decimal? Saldo2 { get; init; }
    public DateTime? Fecha { get; init; }
    public int? IdSucursal { get; init; }
    public int? IdComprobanteDetalle { get; init; }
    public int? IdComprobanteRelacion { get; init; }
    public int? IdComprobanteRelacionTipo { get; init; }
    public int? IdComprobanteRelacionDetalle { get; init; }
}

/// <summary>Filtros del listado de dbo.EntidadesCtaCteStockMovimientosDetalle.</summary>
public sealed partial class EntidadCtaCteStockMovimientoDetalleFilter : PagedQuery
{
    public int? IdEntidad { get; set; }

    public int? IdComprobante { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdItem { get; set; }

    public int? IdSucursal { get; set; }

    public int? IdComprobanteDetalle { get; set; }

    public int? IdComprobanteRelacion { get; set; }

    public int? IdComprobanteRelacionTipo { get; set; }

    public int? IdComprobanteRelacionDetalle { get; set; }

    /// <summary>Fecha desde (inclusive).</summary>
    public DateTime? FechaDesde { get; set; }

    /// <summary>Fecha hasta (inclusive, día completo).</summary>
    public DateTime? FechaHasta { get; set; }
}
