// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Stock;

/// <summary>Salida de dbo.ItemsMovimientosDetalles.</summary>
public sealed partial class ItemMovimientoDetalleDisplay
{
    public int IdItemMovientoDetalle { get; init; }
    public int? IdItem { get; init; }
    public int? IdComprobante { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public int? IdComprobanteDetalle { get; init; }
    public DateTime? FechaAlta { get; init; }
    public int? IdUsuario { get; init; }
    public int? IdSucursal { get; init; }
    public string? Concepto { get; init; }
    public string? Item { get; init; }
    public decimal? Total { get; init; }
    public decimal? Debe { get; init; }
    public decimal? Haber { get; init; }
    public decimal? Total2 { get; init; }
    public bool? Automatico { get; init; }
}

/// <summary>Filtros del listado de dbo.ItemsMovimientosDetalles.</summary>
public sealed partial class ItemMovimientoDetalleFilter : PagedQuery
{
    public int? IdItem { get; set; }

    public int? IdComprobante { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdComprobanteDetalle { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdSucursal { get; set; }

    /// <summary>FechaAlta desde (inclusive).</summary>
    public DateTime? FechaAltaDesde { get; set; }

    /// <summary>FechaAlta hasta (inclusive, día completo).</summary>
    public DateTime? FechaAltaHasta { get; set; }
}
