// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Entidades;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Entidades;

public static partial class EntidadMappings
{
    public static EntidadDisplay ToDisplay(this Db.Entidades entity) => new()
    {
        IdEntidad = entity.IdEntidad,
        RazonSocial = entity.RazonSocial,
        IdCategoriaIva = entity.IdCategoriaIva,
        Cuit = entity.Cuit,
        IdProvincia = entity.IdProvincia,
        IdLocalidad = entity.IdLocalidad,
        Direccion = entity.Direccion,
        NroCalle = entity.NroCalle,
        Telefono = entity.Telefono,
        Email = entity.Email,
        CtaCte = entity.CtaCte,
        LimiteCtaCte = entity.LimiteCtaCte,
        IdEmpresa = entity.IdEmpresa,
        IdEstado = entity.IdEstado,
        Imagen = entity.Imagen,
        Lat = entity.Lat,
        Lng = entity.Lng,
        FechaCreacion = entity.FechaCreacion,
        Observaciones = entity.Observaciones,
        EsHijo = entity.EsHijo,
        IdPadre = entity.IdPadre,
        Fantasia = entity.Fantasia,
        IdEntidadCategoria = entity.IdEntidadCategoria,
        Url = entity.Url,
        DiasInteres = entity.DiasInteres,
        InteresCliente = entity.InteresCliente,
        DiasInteresDos = entity.DiasInteresDos,
    };

    public static Db.Entidades ToEntity(this EntidadDto dto)
    {
        var entity = new Db.Entidades();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this EntidadDto dto, Db.Entidades entity)
    {
        entity.RazonSocial = dto.RazonSocial;
        entity.IdCategoriaIva = dto.IdCategoriaIva;
        entity.Cuit = dto.Cuit;
        entity.IdProvincia = dto.IdProvincia;
        entity.IdLocalidad = dto.IdLocalidad;
        entity.Direccion = dto.Direccion;
        entity.NroCalle = dto.NroCalle;
        entity.Telefono = dto.Telefono;
        entity.Email = dto.Email;
        entity.CtaCte = dto.CtaCte;
        entity.LimiteCtaCte = dto.LimiteCtaCte;
        entity.IdEmpresa = dto.IdEmpresa;
        entity.IdEstado = dto.IdEstado;
        entity.Imagen = dto.Imagen;
        entity.Lat = dto.Lat;
        entity.Lng = dto.Lng;
        entity.FechaCreacion = dto.FechaCreacion;
        entity.Observaciones = dto.Observaciones;
        entity.EsHijo = dto.EsHijo;
        entity.IdPadre = dto.IdPadre;
        entity.Fantasia = dto.Fantasia;
        entity.IdEntidadCategoria = dto.IdEntidadCategoria;
        entity.Url = dto.Url;
        entity.DiasInteres = dto.DiasInteres;
        entity.InteresCliente = dto.InteresCliente;
        entity.DiasInteresDos = dto.DiasInteresDos;
    }
}
