// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Entidades;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Entidades;

public static partial class EntidadFacturacionMappings
{
    public static EntidadFacturacionDisplay ToDisplay(this Db.EntidadesFacturacion entity) => new()
    {
        IdEntidadFacturacion = entity.IdEntidadFacturacion,
        IdEntidad = entity.IdEntidad,
        RazonSocial = entity.RazonSocial,
        Fantasia = entity.Fantasia,
        Cuit = entity.Cuit,
        IdCategoriaIva = entity.IdCategoriaIva,
        IdProvincia = entity.IdProvincia,
        IdLocalidad = entity.IdLocalidad,
        Domicilio = entity.Domicilio,
        DomicilioNro = entity.DomicilioNro,
        GeoLatitud = entity.GeoLatitud,
        GeoLongitud = entity.GeoLongitud,
    };

    public static Db.EntidadesFacturacion ToEntity(this EntidadFacturacionDto dto)
    {
        var entity = new Db.EntidadesFacturacion();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this EntidadFacturacionDto dto, Db.EntidadesFacturacion entity)
    {
        entity.IdEntidad = dto.IdEntidad;
        entity.RazonSocial = dto.RazonSocial;
        entity.Fantasia = dto.Fantasia;
        entity.Cuit = dto.Cuit;
        entity.IdCategoriaIva = dto.IdCategoriaIva;
        entity.IdProvincia = dto.IdProvincia;
        entity.IdLocalidad = dto.IdLocalidad;
        entity.Domicilio = dto.Domicilio;
        entity.DomicilioNro = dto.DomicilioNro;
        entity.GeoLatitud = dto.GeoLatitud;
        entity.GeoLongitud = dto.GeoLongitud;
    }
}
