// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Entidades;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Entidades;

public static partial class EntidadEntidadTipoMappings
{
    public static EntidadEntidadTipoDisplay ToDisplay(this Db.EntidadesEntidadesTipo entity) => new()
    {
        IdEntidadEntidadTipo = entity.IdEntidadEntidadTipo,
        IdEntidad = entity.IdEntidad,
        IdEntidadTipo = entity.IdEntidadTipo,
    };

    public static Db.EntidadesEntidadesTipo ToEntity(this EntidadEntidadTipoDto dto)
    {
        var entity = new Db.EntidadesEntidadesTipo();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this EntidadEntidadTipoDto dto, Db.EntidadesEntidadesTipo entity)
    {
        entity.IdEntidad = dto.IdEntidad;
        entity.IdEntidadTipo = dto.IdEntidadTipo;
    }
}
