// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Entidades;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Entidades;

public static partial class EntidadTipoMappings
{
    public static EntidadTipoDisplay ToDisplay(this Db.EntidadesTipo entity) => new()
    {
        IdEntidadTipo = entity.IdEntidadTipo,
        Descripcion = entity.Descripcion,
    };
}
