// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Clientes;

/// <summary>Salida de dbo.EntidadesRecibos.</summary>
public sealed partial class EntidadReciboDisplay
{
    public int IdEntidadRecibo { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public int? IdEntidad { get; init; }
    public string? Letra { get; init; }
    public string? PuntoVenta { get; init; }
    public string? Numero { get; init; }
    public string? RazonSocial { get; init; }
    public int? IdCategoriaIva { get; init; }
    public string? NroDoc { get; init; }
    public DateTime? FechaEmision { get; init; }
    public int? IdUsuario { get; init; }
    public int? IdEmpresa { get; init; }
    public int? IdPlanillaCaja { get; init; }
    public decimal? Total { get; init; }
    public int? Estado { get; init; }
    public string? Observaciones { get; init; }
    public int? IdSucursal { get; init; }
}

/// <summary>Filtros del listado de dbo.EntidadesRecibos.</summary>
public sealed partial class EntidadReciboFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en RazonSocial, Numero.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdEntidad { get; set; }

    public int? IdCategoriaIva { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdEmpresa { get; set; }

    public int? IdPlanillaCaja { get; set; }

    public int? IdSucursal { get; set; }

    public int? Estado { get; set; }

    /// <summary>FechaEmision desde (inclusive).</summary>
    public DateTime? FechaEmisionDesde { get; set; }

    /// <summary>FechaEmision hasta (inclusive, día completo).</summary>
    public DateTime? FechaEmisionHasta { get; set; }
}
