// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Clientes;

/// <summary>Salida de dbo.EntidadesCheques.</summary>
public sealed partial class EntidadChequeDisplay
{
    public int IdEntidadCheque { get; init; }
    public int? IdEntidad { get; init; }
    public int? IdBanco { get; init; }
    public int? IdSucursal { get; init; }
    public string? Nro { get; init; }
    public decimal? Importe { get; init; }
    public DateTime? FechaRecepcion { get; init; }
    public DateTime? FechaEmision { get; init; }
    public DateTime? FechaVencimiento { get; init; }
    public decimal? ValorToma { get; init; }
    public int? IdEmpresa { get; init; }
    public int? IdUsuario { get; init; }
    public int? Tipo { get; init; }
    public int? IdEntidadRecibo { get; init; }
    public int? Estado { get; init; }
    public int? IdProveedorRecibo { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public string? Observaciones { get; init; }
    public int? IdSucursalEmpresa { get; init; }
    public int? IdEntidadReciboTipo { get; init; }
}

/// <summary>Filtros del listado de dbo.EntidadesCheques.</summary>
public sealed partial class EntidadChequeFilter : PagedQuery
{
    public int? IdEntidad { get; set; }

    public int? IdBanco { get; set; }

    public int? IdSucursal { get; set; }

    public int? IdEmpresa { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdEntidadRecibo { get; set; }

    public int? IdProveedorRecibo { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdSucursalEmpresa { get; set; }

    public int? IdEntidadReciboTipo { get; set; }

    public int? Estado { get; set; }

    /// <summary>FechaRecepcion desde (inclusive).</summary>
    public DateTime? FechaRecepcionDesde { get; set; }

    /// <summary>FechaRecepcion hasta (inclusive, día completo).</summary>
    public DateTime? FechaRecepcionHasta { get; set; }
}
