// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Clientes;

/// <summary>Salida de dbo.EntidadRecibosDocumentosCliente.</summary>
public sealed partial class EntidadReciboDocumentoClienteDisplay
{
    public int IdEntidadReciboDocumentoCliente { get; init; }
    public int? IdEntidadRecibo { get; init; }
    public int? IdEntidad { get; init; }
    public string? NumeroRecibo { get; init; }
    public decimal? ImporteRecibo { get; init; }
    public int? IdDocumentoCliente { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public string? NumeroComprobante { get; init; }
    public decimal? ImporteComprobante { get; init; }
    public decimal? Saldo { get; init; }
}

/// <summary>Filtros del listado de dbo.EntidadRecibosDocumentosCliente.</summary>
public sealed partial class EntidadReciboDocumentoClienteFilter : PagedQuery
{
    public int? IdEntidadRecibo { get; set; }

    public int? IdEntidad { get; set; }

    public int? IdDocumentoCliente { get; set; }

    public int? IdComprobanteTipo { get; set; }
}
