// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Reportes;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Reportes;

public static partial class EntidadCtaCteReporteMappings
{
    public static EntidadCtaCteReporteDisplay ToDisplay(this Db.EntidadesCtaCteReporte entity) => new()
    {
        IdEntidadCtaCteReporte = entity.IdEntidadCtaCteReporte,
        Nro = entity.Nro,
        Concepto = entity.Concepto,
        Fecha = entity.Fecha,
        Vencimiento = entity.Vencimiento,
        Debe = entity.Debe,
        Haber = entity.Haber,
        Total = entity.Total,
        IdComprobanteTipo = entity.IdComprobanteTipo,
        IdComprobante = entity.IdComprobante,
        Observaciones = entity.Observaciones,
        Estado = entity.Estado,
    };
}
