// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Compras;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Compras;

public static partial class DocumentoProveedorOtroTributoMappings
{
    public static DocumentoProveedorOtroTributoDisplay ToDisplay(this Db.DocumentosProveedorOtrosTributos entity) => new()
    {
        IdDocumentoProveedorOtroTributo = entity.IdDocumentoProveedorOtroTributo,
        IdDocumentoProveedor = entity.IdDocumentoProveedor,
        IdComprobanteTipo = entity.IdComprobanteTipo,
        IdOtroTributo = entity.IdOtroTributo,
        Detalle = entity.Detalle,
        BaseImponible = entity.BaseImponible,
        Alicuota = entity.Alicuota,
        Total = entity.Total,
    };
}
