// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Compras;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Compras;

public static partial class DocumentoProveedorRemitoDetalleMappings
{
    public static DocumentoProveedorRemitoDetalleDisplay ToDisplay(this Db.DocumentosProveedorRemitosDetalle entity) => new()
    {
        IdDocumentoProveeorRemitoDetalle = entity.IdDocumentoProveeorRemitoDetalle,
        IdDocumentoProveedorRemito = entity.IdDocumentoProveedorRemito,
        IdItem = entity.IdItem,
        CantidadFactura = entity.CantidadFactura,
        CantidadRemito = entity.CantidadRemito,
        Saldo = entity.Saldo,
        IdDocumentoProveedor = entity.IdDocumentoProveedor,
        IdRemito = entity.IdRemito,
    };
}
