// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Compras;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Compras;

public static partial class DocumentoProveedorRemitoMappings
{
    public static DocumentoProveedorRemitoDisplay ToDisplay(this Db.DocumentosProveedorRemitos entity) => new()
    {
        IdDocumentoProveedorRemito = entity.IdDocumentoProveedorRemito,
        IdDocumentoProveedor = entity.IdDocumentoProveedor,
        IdRemito = entity.IdRemito,
        IdComprobanteTipo = entity.IdComprobanteTipo,
    };
}
