// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Geografia;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Geografia;

public static partial class LocalidadMappings
{
    public static LocalidadDisplay ToDisplay(this Db.Localidades entity) => new()
    {
        IdLocalidad = entity.IdLocalidad,
        Descripcion = entity.Descripcion,
        IdProvincia = entity.IdProvincia,
        Cp = entity.Cp,
        Orden = entity.Orden,
        Estado = entity.Estado,
    };

    public static Db.Localidades ToEntity(this LocalidadDto dto)
    {
        var entity = new Db.Localidades();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this LocalidadDto dto, Db.Localidades entity)
    {
        entity.Descripcion = dto.Descripcion;
        entity.IdProvincia = dto.IdProvincia;
        entity.Cp = dto.Cp;
        entity.Orden = dto.Orden;
        entity.Estado = dto.Estado;
    }
}
