// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Geografia;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Geografia;

public static partial class PaisMappings
{
    public static PaisDisplay ToDisplay(this Db.Paises entity) => new()
    {
        IdPais = entity.IdPais,
        Descripcion = entity.Descripcion,
        Orden = entity.Orden,
        Estado = entity.Estado,
    };

    public static Db.Paises ToEntity(this PaisDto dto)
    {
        var entity = new Db.Paises();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this PaisDto dto, Db.Paises entity)
    {
        entity.Descripcion = dto.Descripcion;
        entity.Orden = dto.Orden;
        entity.Estado = dto.Estado;
    }
}
