// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Entidades;

/// <summary>Salida de dbo.EntidadesTipo.</summary>
public sealed partial class EntidadTipoDisplay
{
    public int IdEntidadTipo { get; init; }
    public string? Descripcion { get; init; }
}

/// <summary>Filtros del listado de dbo.EntidadesTipo.</summary>
public sealed partial class EntidadTipoFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }
}
