// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Proveedores;
using API.SERVICE.Mappings.Proveedores;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Proveedores;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Proveedores;

public interface IGetEntidadOrdenPagoDocumentoProveedorListUseCase
{
    Task<PagedResult<EntidadOrdenPagoDocumentoProveedorDisplay>> ExecuteAsync(EntidadOrdenPagoDocumentoProveedorFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadOrdenPagoDocumentoProveedorListUseCase(IEntidadOrdenPagoDocumentoProveedorRepository repository)
    : GetListUseCaseBase<Db.EntidadOrdenPagoDocumentosProveedores, EntidadOrdenPagoDocumentoProveedorFilter, EntidadOrdenPagoDocumentoProveedorDisplay>(repository), IGetEntidadOrdenPagoDocumentoProveedorListUseCase
{
    protected override EntidadOrdenPagoDocumentoProveedorDisplay ToDisplay(Db.EntidadOrdenPagoDocumentosProveedores entity) => entity.ToDisplay();
}

public interface IGetEntidadOrdenPagoDocumentoProveedorByIdUseCase
{
    Task<EntidadOrdenPagoDocumentoProveedorDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadOrdenPagoDocumentoProveedorByIdUseCase(IEntidadOrdenPagoDocumentoProveedorRepository repository)
    : GetByIdUseCaseBase<Db.EntidadOrdenPagoDocumentosProveedores, int, EntidadOrdenPagoDocumentoProveedorFilter, EntidadOrdenPagoDocumentoProveedorDisplay>(repository), IGetEntidadOrdenPagoDocumentoProveedorByIdUseCase
{
    protected override string EntityName => "EntidadOrdenPagoDocumentoProveedor";

    protected override EntidadOrdenPagoDocumentoProveedorDisplay ToDisplay(Db.EntidadOrdenPagoDocumentosProveedores entity) => entity.ToDisplay();
}
