// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Proveedores;
using API.SERVICE.Mappings.Proveedores;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Proveedores;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Proveedores;

public interface IGetProveedorReciboListUseCase
{
    Task<PagedResult<ProveedorReciboDisplay>> ExecuteAsync(ProveedorReciboFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetProveedorReciboListUseCase(IProveedorReciboRepository repository)
    : GetListUseCaseBase<Db.ProveedoresRecibos, ProveedorReciboFilter, ProveedorReciboDisplay>(repository), IGetProveedorReciboListUseCase
{
    protected override ProveedorReciboDisplay ToDisplay(Db.ProveedoresRecibos entity) => entity.ToDisplay();
}

public interface IGetProveedorReciboByIdUseCase
{
    Task<ProveedorReciboDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetProveedorReciboByIdUseCase(IProveedorReciboRepository repository)
    : GetByIdUseCaseBase<Db.ProveedoresRecibos, int, ProveedorReciboFilter, ProveedorReciboDisplay>(repository), IGetProveedorReciboByIdUseCase
{
    protected override string EntityName => "ProveedorRecibo";

    protected override ProveedorReciboDisplay ToDisplay(Db.ProveedoresRecibos entity) => entity.ToDisplay();
}
