// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Proveedores;
using API.SERVICE.Mappings.Proveedores;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Proveedores;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Proveedores;

public interface IGetProveedorReciboDetalleListUseCase
{
    Task<PagedResult<ProveedorReciboDetalleDisplay>> ExecuteAsync(ProveedorReciboDetalleFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetProveedorReciboDetalleListUseCase(IProveedorReciboDetalleRepository repository)
    : GetListUseCaseBase<Db.ProveedoresRecibosDetalle, ProveedorReciboDetalleFilter, ProveedorReciboDetalleDisplay>(repository), IGetProveedorReciboDetalleListUseCase
{
    protected override ProveedorReciboDetalleDisplay ToDisplay(Db.ProveedoresRecibosDetalle entity) => entity.ToDisplay();
}

public interface IGetProveedorReciboDetalleByIdUseCase
{
    Task<ProveedorReciboDetalleDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetProveedorReciboDetalleByIdUseCase(IProveedorReciboDetalleRepository repository)
    : GetByIdUseCaseBase<Db.ProveedoresRecibosDetalle, int, ProveedorReciboDetalleFilter, ProveedorReciboDetalleDisplay>(repository), IGetProveedorReciboDetalleByIdUseCase
{
    protected override string EntityName => "ProveedorReciboDetalle";

    protected override ProveedorReciboDetalleDisplay ToDisplay(Db.ProveedoresRecibosDetalle entity) => entity.ToDisplay();
}
