// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Miscelaneas;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Miscelaneas;

public static partial class CategoriaMappings
{
    public static CategoriaDisplay ToDisplay(this Db.Categorias entity) => new()
    {
        IdCategoria = entity.IdCategoria,
        Nombre = entity.Nombre,
        CategoriaTipo = entity.CategoriaTipo,
        Descripcion = entity.Descripcion,
        Activo = entity.Activo,
        Orden = entity.Orden,
    };

    public static Db.Categorias ToEntity(this CategoriaDto dto)
    {
        var entity = new Db.Categorias();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this CategoriaDto dto, Db.Categorias entity)
    {
        entity.Nombre = dto.Nombre;
        entity.CategoriaTipo = dto.CategoriaTipo;
        entity.Descripcion = dto.Descripcion;
        entity.Activo = dto.Activo;
        entity.Orden = dto.Orden;
    }
}
