// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Miscelaneas;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Miscelaneas;

public static partial class EstadoMappings
{
    public static EstadoDisplay ToDisplay(this Db.Estados entity) => new()
    {
        IdEstado = entity.IdEstado,
        Categoria = entity.Categoria,
        Nombre = entity.Nombre,
        Descripcion = entity.Descripcion,
        Imagen = entity.Imagen,
        Activo = entity.Activo,
    };

    public static Db.Estados ToEntity(this EstadoDto dto)
    {
        var entity = new Db.Estados();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this EstadoDto dto, Db.Estados entity)
    {
        entity.Categoria = dto.Categoria;
        entity.Nombre = dto.Nombre;
        entity.Descripcion = dto.Descripcion;
        entity.Imagen = dto.Imagen;
        entity.Activo = dto.Activo;
    }
}
