// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Compras;

/// <summary>Salida de dbo.DocumentosProveedor.</summary>
public sealed partial class DocumentoProveedorDisplay
{
    public int IdDocumentoProveedor { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public int? IdCondicion { get; init; }
    public string? Letra { get; init; }
    public int? IdPuntoVenta { get; init; }
    public string? PuntoVenta { get; init; }
    public string? Numero { get; init; }
    public int? IdProveedor { get; init; }
    public string? RazonSocial { get; init; }
    public int? IdCategoriaIva { get; init; }
    public string? NroDoc { get; init; }
    public int? IdProvincia { get; init; }
    public int? IdLocalidad { get; init; }
    public string? Calle { get; init; }
    public string? Nro { get; init; }
    public decimal? TotalNeto { get; init; }
    public decimal? TotalIva { get; init; }
    public decimal? TotalOtrosImpuestos { get; init; }
    public decimal? TotalGeneral { get; init; }
    public DateTime? FechaEmision { get; init; }
    public int? IdUsuario { get; init; }
    public int? IdEmpresa { get; init; }
    public int? IdPlanillaCaja { get; init; }
    public int? Estado { get; init; }
    public string? Cae { get; init; }
    public DateTime? VtoCae { get; init; }
    public int? IdTransporte { get; init; }
    public string? Transporte { get; init; }
    public int? IdUnidad { get; init; }
    public string? Unidad { get; init; }
    public int? IdChofer { get; init; }
    public string? Chofer { get; init; }
    public int? IdRemito { get; init; }
    public int? IdSucursal { get; init; }
    public decimal? TotalDescuento { get; init; }
    public decimal? PorcentajeDescuento { get; init; }
    public bool? Remitar { get; init; }
    public bool? Facturar { get; init; }
    public bool? Pendiente { get; init; }
}

/// <summary>Filtros del listado de dbo.DocumentosProveedor.</summary>
public sealed partial class DocumentoProveedorFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en RazonSocial, Numero.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdCondicion { get; set; }

    public int? IdPuntoVenta { get; set; }

    public int? IdProveedor { get; set; }

    public int? IdCategoriaIva { get; set; }

    public int? IdProvincia { get; set; }

    public int? IdLocalidad { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdEmpresa { get; set; }

    public int? IdPlanillaCaja { get; set; }

    public int? IdTransporte { get; set; }

    public int? IdUnidad { get; set; }

    public int? IdChofer { get; set; }

    public int? IdRemito { get; set; }

    public int? IdSucursal { get; set; }

    public int? Estado { get; set; }

    /// <summary>FechaEmision desde (inclusive).</summary>
    public DateTime? FechaEmisionDesde { get; set; }

    /// <summary>FechaEmision hasta (inclusive, día completo).</summary>
    public DateTime? FechaEmisionHasta { get; set; }
}
