// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Compras;

/// <summary>Salida de dbo.DocumentosProveedorRemitosDetalle.</summary>
public sealed partial class DocumentoProveedorRemitoDetalleDisplay
{
    public int IdDocumentoProveeorRemitoDetalle { get; init; }
    public int? IdDocumentoProveedorRemito { get; init; }
    public int? IdItem { get; init; }
    public decimal? CantidadFactura { get; init; }
    public decimal? CantidadRemito { get; init; }
    public decimal? Saldo { get; init; }
    public int? IdDocumentoProveedor { get; init; }
    public int? IdRemito { get; init; }
}

/// <summary>Filtros del listado de dbo.DocumentosProveedorRemitosDetalle.</summary>
public sealed partial class DocumentoProveedorRemitoDetalleFilter : PagedQuery
{
    public int? IdDocumentoProveedorRemito { get; set; }

    public int? IdItem { get; set; }

    public int? IdDocumentoProveedor { get; set; }

    public int? IdRemito { get; set; }
}
