// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Miscelaneas;

/// <summary>Salida de dbo.AreasDeContacto.</summary>
public sealed partial class AreaDeContactoDisplay
{
    public int IdAreaDeContacto { get; init; }
    public string? Descripcion { get; init; }
    public string? Observaciones { get; init; }
    public int? IdEstado { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.AreasDeContacto.</summary>
public sealed partial class AreaDeContactoDto
{
    [MaxLength(500)]
    public string? Descripcion { get; set; }

    [MaxLength(500)]
    public string? Observaciones { get; set; }

    public int? IdEstado { get; set; }
}

/// <summary>Filtros del listado de dbo.AreasDeContacto.</summary>
public sealed partial class AreaDeContactoFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdEstado { get; set; }
}
