// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Miscelaneas;

/// <summary>Salida de dbo.Categorias.</summary>
public sealed partial class CategoriaDisplay
{
    public int IdCategoria { get; init; }
    public string? Nombre { get; init; }
    public string? CategoriaTipo { get; init; }
    public string? Descripcion { get; init; }
    public bool? Activo { get; init; }
    public int? Orden { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.Categorias.</summary>
public sealed partial class CategoriaDto
{
    [MaxLength(50)]
    public string? Nombre { get; set; }

    [MaxLength(50)]
    public string? CategoriaTipo { get; set; }

    [MaxLength(50)]
    public string? Descripcion { get; set; }

    public bool? Activo { get; set; }

    public int? Orden { get; set; }
}

/// <summary>Filtros del listado de dbo.Categorias.</summary>
public sealed partial class CategoriaFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion, Nombre.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public bool? Activo { get; set; }
}
