// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Comprobantes;
using API.SERVICE.Models.Comprobantes;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Comprobantes;

public sealed partial class ComprobanteLetraRepository : EfRepository<Db.ComprobantesLetras, int, ComprobanteLetraFilter>, IComprobanteLetraRepository
{
    public ComprobanteLetraRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.ComprobantesLetras> ApplyFilter(IQueryable<Db.ComprobantesLetras> query, ComprobanteLetraFilter filter)
    {
        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        if (filter.IdCategoriaIvacliente is not null)
            query = query.Where(x => x.IdCategoriaIvacliente == filter.IdCategoriaIvacliente);

        if (filter.IdCategoriaIvaproveedor is not null)
            query = query.Where(x => x.IdCategoriaIvaproveedor == filter.IdCategoriaIvaproveedor);

        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        return query;
    }

    protected override IOrderedQueryable<Db.ComprobantesLetras> ApplyDefaultOrder(IQueryable<Db.ComprobantesLetras> query) =>
        query.OrderByDescending(x => x.IdComprobanteLetra);
}
