// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Comprobantes;
using API.SERVICE.Models.Comprobantes;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Comprobantes;

public sealed partial class ElementoCobroPagoRepository : EfRepository<Db.ElementosCobroPago, int, ElementoCobroPagoFilter>, IElementoCobroPagoRepository
{
    public ElementoCobroPagoRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.ElementosCobroPago> ApplyFilter(IQueryable<Db.ElementosCobroPago> query, ElementoCobroPagoFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        if (filter.IdTipo is not null)
            query = query.Where(x => x.IdTipo == filter.IdTipo);

        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        return query;
    }

    protected override IOrderedQueryable<Db.ElementosCobroPago> ApplyDefaultOrder(IQueryable<Db.ElementosCobroPago> query) =>
        query.OrderBy(x => x.Descripcion);
}
