// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Comprobantes;
using API.SERVICE.Models.Comprobantes;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Comprobantes;

public sealed partial class PuntoVentaRepository : EfRepository<Db.PuntosVenta, int, PuntoVentaFilter>, IPuntoVentaRepository
{
    public PuntoVentaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.PuntosVenta> ApplyFilter(IQueryable<Db.PuntosVenta> query, PuntoVentaFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        if (filter.IdUsuario is not null)
            query = query.Where(x => x.IdUsuario == filter.IdUsuario);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        return query;
    }

    protected override IOrderedQueryable<Db.PuntosVenta> ApplyDefaultOrder(IQueryable<Db.PuntosVenta> query) =>
        query.OrderByDescending(x => x.IdPuntoVenta);
}
