// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Comprobantes;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Comprobantes;

/// <summary>Persistencia de dbo.ComprobantesCarga.</summary>
public partial interface IComprobanteCargaRepository : global::API.SERVICE.Interfaces.IReadRepository<Db.ComprobantesCarga, int, ComprobanteCargaFilter>
{
}
