// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.CuentasCorrientes;
using API.SERVICE.Models.CuentasCorrientes;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.CuentasCorrientes;

public sealed partial class EntidadCtaCteRepository : EfRepository<Db.EntidadesCtaCte, long, EntidadCtaCteFilter>, IEntidadCtaCteRepository
{
    public EntidadCtaCteRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.EntidadesCtaCte> ApplyFilter(IQueryable<Db.EntidadesCtaCte> query, EntidadCtaCteFilter filter)
    {
        if (filter.IdEntidad is not null)
            query = query.Where(x => x.IdEntidad == filter.IdEntidad);

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        if (filter.IdComprobante is not null)
            query = query.Where(x => x.IdComprobante == filter.IdComprobante);

        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        if (filter.IdSucursal is not null)
            query = query.Where(x => x.IdSucursal == filter.IdSucursal);

        if (filter.IdUsuario is not null)
            query = query.Where(x => x.IdUsuario == filter.IdUsuario);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        if (filter.FechaDesde is not null)
            query = query.Where(x => x.Fecha >= filter.FechaDesde.Value);

        if (filter.FechaHasta is not null)
        {
            var hasta = filter.FechaHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.Fecha < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.EntidadesCtaCte> ApplyDefaultOrder(IQueryable<Db.EntidadesCtaCte> query) =>
        query.OrderByDescending(x => x.IdEntidadCtaCte);
}
