// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Common;
using API.SERVICE.Models.Caja;
using API.SERVICE.UseCases.Caja;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers.Caja;

/// <summary>dbo.CajaPlanillas. Solo lectura: las altas se hacen desde el flujo de negocio correspondiente.</summary>
[ApiController]
[Authorize]
[Route("api/[controller]")]
[Tags("Caja")]
[Produces("application/json")]
[ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status401Unauthorized)]
public sealed partial class CajaPlanillaController : ControllerBase
{
    /// <summary>Listado paginado y filtrado.</summary>
    [HttpGet]
    [ProducesResponseType(typeof(PagedResult<CajaPlanillaDisplay>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<PagedResult<CajaPlanillaDisplay>>> GetList([FromQuery] CajaPlanillaFilter filter, [FromServices] IGetCajaPlanillaListUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(filter, cancellationToken));

    /// <summary>Detalle por Id.</summary>
    [HttpGet("{id:int}")]
    [ProducesResponseType(typeof(CajaPlanillaDisplay), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<CajaPlanillaDisplay>> GetById(int id, [FromServices] IGetCajaPlanillaByIdUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(id, cancellationToken));
}
