// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Common;
using API.SERVICE.Models.Proveedores;
using API.SERVICE.UseCases.Proveedores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers.Proveedores;

/// <summary>dbo.ProveedoresRecibos. Solo lectura: las altas se hacen desde el flujo de negocio correspondiente.</summary>
[ApiController]
[Authorize]
[Route("api/[controller]")]
[Tags("Proveedores")]
[Produces("application/json")]
[ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status401Unauthorized)]
public sealed partial class ProveedorReciboController : ControllerBase
{
    /// <summary>Listado paginado y filtrado.</summary>
    [HttpGet]
    [ProducesResponseType(typeof(PagedResult<ProveedorReciboDisplay>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<PagedResult<ProveedorReciboDisplay>>> GetList([FromQuery] ProveedorReciboFilter filter, [FromServices] IGetProveedorReciboListUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(filter, cancellationToken));

    /// <summary>Detalle por Id.</summary>
    [HttpGet("{id:int}")]
    [ProducesResponseType(typeof(ProveedorReciboDisplay), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ProveedorReciboDisplay>> GetById(int id, [FromServices] IGetProveedorReciboByIdUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(id, cancellationToken));
}
