// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Bancos;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Bancos;

public static partial class BancoCuentaMappings
{
    public static BancoCuentaDisplay ToDisplay(this Db.BancosCuentas entity) => new()
    {
        IdBancoCuenta = entity.IdBancoCuenta,
        IdBanco = entity.IdBanco,
        IdBancoSucursal = entity.IdBancoSucursal,
        IdCuentaTipo = entity.IdCuentaTipo,
        NroCuenta = entity.NroCuenta,
        Estado = entity.Estado,
    };

    public static Db.BancosCuentas ToEntity(this BancoCuentaDto dto)
    {
        var entity = new Db.BancosCuentas();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this BancoCuentaDto dto, Db.BancosCuentas entity)
    {
        entity.IdBanco = dto.IdBanco;
        entity.IdBancoSucursal = dto.IdBancoSucursal;
        entity.IdCuentaTipo = dto.IdCuentaTipo;
        entity.NroCuenta = dto.NroCuenta;
        entity.Estado = dto.Estado;
    }
}
