// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Bancos;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Bancos;

public static partial class BancoMappings
{
    public static BancoDisplay ToDisplay(this Db.Bancos entity) => new()
    {
        IdBanco = entity.IdBanco,
        RazonSocial = entity.RazonSocial,
        IdEstado = entity.IdEstado,
    };

    public static Db.Bancos ToEntity(this BancoDto dto)
    {
        var entity = new Db.Bancos();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this BancoDto dto, Db.Bancos entity)
    {
        entity.RazonSocial = dto.RazonSocial;
        entity.IdEstado = dto.IdEstado;
    }
}
