// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Bancos;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Bancos;

public static partial class OrdenDepositoMappings
{
    public static OrdenDepositoDisplay ToDisplay(this Db.OrdenesDepositos entity) => new()
    {
        IdOrdenDepostio = entity.IdOrdenDepostio,
        IdComprobanteTipo = entity.IdComprobanteTipo,
        FechaEmision = entity.FechaEmision,
        IdBancoCuenta = entity.IdBancoCuenta,
        Letra = entity.Letra,
        PuntoVenta = entity.PuntoVenta,
        Numero = entity.Numero,
        IdUsuario = entity.IdUsuario,
        IdEmpresa = entity.IdEmpresa,
        IdPlanillaCaja = entity.IdPlanillaCaja,
        Total = entity.Total,
        Observaciones = entity.Observaciones,
        Estado = entity.Estado,
    };
}
