// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Reportes;
using API.SERVICE.Mappings.Reportes;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Reportes;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Reportes;

public interface IGetEntidadCtaCteReporteListUseCase
{
    Task<PagedResult<EntidadCtaCteReporteDisplay>> ExecuteAsync(EntidadCtaCteReporteFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCtaCteReporteListUseCase(IEntidadCtaCteReporteRepository repository)
    : GetListUseCaseBase<Db.EntidadesCtaCteReporte, EntidadCtaCteReporteFilter, EntidadCtaCteReporteDisplay>(repository), IGetEntidadCtaCteReporteListUseCase
{
    protected override EntidadCtaCteReporteDisplay ToDisplay(Db.EntidadesCtaCteReporte entity) => entity.ToDisplay();
}

public interface IGetEntidadCtaCteReporteByIdUseCase
{
    Task<EntidadCtaCteReporteDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCtaCteReporteByIdUseCase(IEntidadCtaCteReporteRepository repository)
    : GetByIdUseCaseBase<Db.EntidadesCtaCteReporte, int, EntidadCtaCteReporteFilter, EntidadCtaCteReporteDisplay>(repository), IGetEntidadCtaCteReporteByIdUseCase
{
    protected override string EntityName => "EntidadCtaCteReporte";

    protected override EntidadCtaCteReporteDisplay ToDisplay(Db.EntidadesCtaCteReporte entity) => entity.ToDisplay();
}

public interface IDeleteEntidadCtaCteReporteUseCase
{
    Task ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class DeleteEntidadCtaCteReporteUseCase(IEntidadCtaCteReporteRepository repository, IRedisCacheService cache)
    : DeleteUseCaseBase<Db.EntidadesCtaCteReporte, int, EntidadCtaCteReporteFilter>(repository, cache), IDeleteEntidadCtaCteReporteUseCase
{
    protected override string EntityName => "EntidadCtaCteReporte";
}
