// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.CuentasCorrientes;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.CuentasCorrientes;

/// <summary>Persistencia de dbo.EntidadesCtaCteMovimientos.</summary>
public partial interface IEntidadCtaCteMovimientoRepository : global::API.SERVICE.Interfaces.IReadRepository<Db.EntidadesCtaCteMovimientos, long, EntidadCtaCteMovimientoFilter>
{
}
