// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Geografia;

/// <summary>Salida de dbo.Localidades.</summary>
public sealed partial class LocalidadDisplay
{
    public int IdLocalidad { get; init; }
    public string? Descripcion { get; init; }
    public int? IdProvincia { get; init; }
    public string? Cp { get; init; }
    public int? Orden { get; init; }
    public int? Estado { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.Localidades.</summary>
public sealed partial class LocalidadDto
{
    [MaxLength(50)]
    public string? Descripcion { get; set; }

    public int? IdProvincia { get; set; }

    [MaxLength(50)]
    public string? Cp { get; set; }

    public int? Orden { get; set; }

    public int? Estado { get; set; }
}

/// <summary>Filtros del listado de dbo.Localidades.</summary>
public sealed partial class LocalidadFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdProvincia { get; set; }

    public int? Estado { get; set; }
}
