// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Geografia;

/// <summary>Salida de dbo.Provincias.</summary>
public sealed partial class ProvinciaDisplay
{
    public int IdProvincia { get; init; }
    public string? Descripcion { get; init; }
    public int? IdPais { get; init; }
    public int? Orden { get; init; }
    public int? Estado { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.Provincias.</summary>
public sealed partial class ProvinciaDto
{
    [MaxLength(500)]
    public string? Descripcion { get; set; }

    public int? IdPais { get; set; }

    public int? Orden { get; set; }

    public int? Estado { get; set; }
}

/// <summary>Filtros del listado de dbo.Provincias.</summary>
public sealed partial class ProvinciaFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdPais { get; set; }

    public int? Estado { get; set; }
}
