// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Afip;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Afip;

/// <summary>Persistencia de dbo.OtrosTributos.</summary>
public partial interface IOtroTributoRepository : global::API.SERVICE.Interfaces.IRepository<Db.OtrosTributos, int, OtroTributoFilter>
{
}
