// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Proveedores;
using API.SERVICE.Models.Proveedores;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Proveedores;

public sealed partial class EntidadOrdenPagoDocumentoProveedorRepository : EfRepository<Db.EntidadOrdenPagoDocumentosProveedores, int, EntidadOrdenPagoDocumentoProveedorFilter>, IEntidadOrdenPagoDocumentoProveedorRepository
{
    public EntidadOrdenPagoDocumentoProveedorRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.EntidadOrdenPagoDocumentosProveedores> ApplyFilter(IQueryable<Db.EntidadOrdenPagoDocumentosProveedores> query, EntidadOrdenPagoDocumentoProveedorFilter filter)
    {
        if (filter.IdEntidadOrdenPago is not null)
            query = query.Where(x => x.IdEntidadOrdenPago == filter.IdEntidadOrdenPago);

        if (filter.IdEntidad is not null)
            query = query.Where(x => x.IdEntidad == filter.IdEntidad);

        if (filter.IdDocumentoProveedor is not null)
            query = query.Where(x => x.IdDocumentoProveedor == filter.IdDocumentoProveedor);

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        return query;
    }

    protected override IOrderedQueryable<Db.EntidadOrdenPagoDocumentosProveedores> ApplyDefaultOrder(IQueryable<Db.EntidadOrdenPagoDocumentosProveedores> query) =>
        query.OrderByDescending(x => x.IdEntidadOrdenPagoDocumentoProveedor);
}
