// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Proveedores;
using API.SERVICE.Models.Proveedores;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Proveedores;

public sealed partial class ProveedorReciboDetalleRepository : EfRepository<Db.ProveedoresRecibosDetalle, int, ProveedorReciboDetalleFilter>, IProveedorReciboDetalleRepository
{
    public ProveedorReciboDetalleRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.ProveedoresRecibosDetalle> ApplyFilter(IQueryable<Db.ProveedoresRecibosDetalle> query, ProveedorReciboDetalleFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q))
                || (x.Detalle != null && x.Detalle.Contains(q)));
        }

        if (filter.IdProveedorRecibo is not null)
            query = query.Where(x => x.IdProveedorRecibo == filter.IdProveedorRecibo);

        if (filter.IdElementoCobroPago is not null)
            query = query.Where(x => x.IdElementoCobroPago == filter.IdElementoCobroPago);

        if (filter.IdBanco is not null)
            query = query.Where(x => x.IdBanco == filter.IdBanco);

        if (filter.IdSucursal is not null)
            query = query.Where(x => x.IdSucursal == filter.IdSucursal);

        if (filter.IdElemento is not null)
            query = query.Where(x => x.IdElemento == filter.IdElemento);

        return query;
    }

    protected override IOrderedQueryable<Db.ProveedoresRecibosDetalle> ApplyDefaultOrder(IQueryable<Db.ProveedoresRecibosDetalle> query) =>
        query.OrderByDescending(x => x.IdProveedorReciboDetalle);
}
