// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Common;
using API.SERVICE.Models.CuentasCorrientes;
using API.SERVICE.UseCases.CuentasCorrientes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers.CuentasCorrientes;

/// <summary>dbo.EntidadesCtaCteMovimientos. Solo lectura: las altas se hacen desde el flujo de negocio correspondiente.</summary>
[ApiController]
[Authorize]
[Route("api/[controller]")]
[Tags("CuentasCorrientes")]
[Produces("application/json")]
[ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status401Unauthorized)]
public sealed partial class EntidadCtaCteMovimientoController : ControllerBase
{
    /// <summary>Listado paginado y filtrado.</summary>
    [HttpGet]
    [ProducesResponseType(typeof(PagedResult<EntidadCtaCteMovimientoDisplay>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<PagedResult<EntidadCtaCteMovimientoDisplay>>> GetList([FromQuery] EntidadCtaCteMovimientoFilter filter, [FromServices] IGetEntidadCtaCteMovimientoListUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(filter, cancellationToken));

    /// <summary>Detalle por Id.</summary>
    [HttpGet("{id:long}")]
    [ProducesResponseType(typeof(EntidadCtaCteMovimientoDisplay), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<EntidadCtaCteMovimientoDisplay>> GetById(long id, [FromServices] IGetEntidadCtaCteMovimientoByIdUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(id, cancellationToken));
}
