// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Caja;
using API.SERVICE.Mappings.Caja;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Caja;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Caja;

public interface IGetCajaPlanillaListUseCase
{
    Task<PagedResult<CajaPlanillaDisplay>> ExecuteAsync(CajaPlanillaFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetCajaPlanillaListUseCase(ICajaPlanillaRepository repository)
    : GetListUseCaseBase<Db.CajaPlanillas, CajaPlanillaFilter, CajaPlanillaDisplay>(repository), IGetCajaPlanillaListUseCase
{
    protected override CajaPlanillaDisplay ToDisplay(Db.CajaPlanillas entity) => entity.ToDisplay();
}

public interface IGetCajaPlanillaByIdUseCase
{
    Task<CajaPlanillaDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetCajaPlanillaByIdUseCase(ICajaPlanillaRepository repository)
    : GetByIdUseCaseBase<Db.CajaPlanillas, int, CajaPlanillaFilter, CajaPlanillaDisplay>(repository), IGetCajaPlanillaByIdUseCase
{
    protected override string EntityName => "CajaPlanilla";

    protected override CajaPlanillaDisplay ToDisplay(Db.CajaPlanillas entity) => entity.ToDisplay();
}
