// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Caja;
using API.SERVICE.Mappings.Caja;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Caja;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Caja;

public interface IGetCajaPlanillaDetalleListUseCase
{
    Task<PagedResult<CajaPlanillaDetalleDisplay>> ExecuteAsync(CajaPlanillaDetalleFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetCajaPlanillaDetalleListUseCase(ICajaPlanillaDetalleRepository repository)
    : GetListUseCaseBase<Db.CajasPlanillasDetalle, CajaPlanillaDetalleFilter, CajaPlanillaDetalleDisplay>(repository), IGetCajaPlanillaDetalleListUseCase
{
    protected override CajaPlanillaDetalleDisplay ToDisplay(Db.CajasPlanillasDetalle entity) => entity.ToDisplay();
}

public interface IGetCajaPlanillaDetalleByIdUseCase
{
    Task<CajaPlanillaDetalleDisplay> ExecuteAsync(long id, CancellationToken cancellationToken = default);
}

public sealed partial class GetCajaPlanillaDetalleByIdUseCase(ICajaPlanillaDetalleRepository repository)
    : GetByIdUseCaseBase<Db.CajasPlanillasDetalle, long, CajaPlanillaDetalleFilter, CajaPlanillaDetalleDisplay>(repository), IGetCajaPlanillaDetalleByIdUseCase
{
    protected override string EntityName => "CajaPlanillaDetalle";

    protected override CajaPlanillaDetalleDisplay ToDisplay(Db.CajasPlanillasDetalle entity) => entity.ToDisplay();
}
