// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Items;
using API.SERVICE.Mappings.Items;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Items;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Items;

public interface IGetComboListUseCase
{
    Task<PagedResult<ComboDisplay>> ExecuteAsync(ComboFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetComboListUseCase(IComboRepository repository)
    : GetListUseCaseBase<Db.Combos, ComboFilter, ComboDisplay>(repository), IGetComboListUseCase
{
    protected override ComboDisplay ToDisplay(Db.Combos entity) => entity.ToDisplay();
}

public interface IGetComboByIdUseCase
{
    Task<ComboDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetComboByIdUseCase(IComboRepository repository)
    : GetByIdUseCaseBase<Db.Combos, int, ComboFilter, ComboDisplay>(repository), IGetComboByIdUseCase
{
    protected override string EntityName => "Combo";

    protected override ComboDisplay ToDisplay(Db.Combos entity) => entity.ToDisplay();
}

public interface ICreateComboUseCase
{
    Task<ComboDisplay> ExecuteAsync(ComboDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateComboUseCase(IComboRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.Combos, int, ComboFilter, ComboDto, ComboDisplay>(repository, cache), ICreateComboUseCase
{
    protected override string EntityName => "Combo";

    protected override Db.Combos ToEntity(ComboDto dto) => dto.ToEntity();

    protected override ComboDisplay ToDisplay(Db.Combos entity) => entity.ToDisplay();
}

public interface IUpdateComboUseCase
{
    Task<ComboDisplay> ExecuteAsync(int id, ComboDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateComboUseCase(IComboRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.Combos, int, ComboFilter, ComboDto, ComboDisplay>(repository, cache), IUpdateComboUseCase
{
    protected override string EntityName => "Combo";

    protected override void Apply(ComboDto dto, Db.Combos entity) => dto.ApplyTo(entity);

    protected override ComboDisplay ToDisplay(Db.Combos entity) => entity.ToDisplay();
}
