// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Items;
using API.SERVICE.Mappings.Items;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Items;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Items;

public interface IGetItemNroSerieListUseCase
{
    Task<PagedResult<ItemNroSerieDisplay>> ExecuteAsync(ItemNroSerieFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetItemNroSerieListUseCase(IItemNroSerieRepository repository)
    : GetListUseCaseBase<Db.ItemsNroSeries, ItemNroSerieFilter, ItemNroSerieDisplay>(repository), IGetItemNroSerieListUseCase
{
    protected override ItemNroSerieDisplay ToDisplay(Db.ItemsNroSeries entity) => entity.ToDisplay();
}

public interface IGetItemNroSerieByIdUseCase
{
    Task<ItemNroSerieDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetItemNroSerieByIdUseCase(IItemNroSerieRepository repository)
    : GetByIdUseCaseBase<Db.ItemsNroSeries, int, ItemNroSerieFilter, ItemNroSerieDisplay>(repository), IGetItemNroSerieByIdUseCase
{
    protected override string EntityName => "ItemNroSerie";

    protected override ItemNroSerieDisplay ToDisplay(Db.ItemsNroSeries entity) => entity.ToDisplay();
}

public interface ICreateItemNroSerieUseCase
{
    Task<ItemNroSerieDisplay> ExecuteAsync(ItemNroSerieDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateItemNroSerieUseCase(IItemNroSerieRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.ItemsNroSeries, int, ItemNroSerieFilter, ItemNroSerieDto, ItemNroSerieDisplay>(repository, cache), ICreateItemNroSerieUseCase
{
    protected override string EntityName => "ItemNroSerie";

    protected override Db.ItemsNroSeries ToEntity(ItemNroSerieDto dto) => dto.ToEntity();

    protected override ItemNroSerieDisplay ToDisplay(Db.ItemsNroSeries entity) => entity.ToDisplay();
}

public interface IUpdateItemNroSerieUseCase
{
    Task<ItemNroSerieDisplay> ExecuteAsync(int id, ItemNroSerieDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateItemNroSerieUseCase(IItemNroSerieRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.ItemsNroSeries, int, ItemNroSerieFilter, ItemNroSerieDto, ItemNroSerieDisplay>(repository, cache), IUpdateItemNroSerieUseCase
{
    protected override string EntityName => "ItemNroSerie";

    protected override void Apply(ItemNroSerieDto dto, Db.ItemsNroSeries entity) => dto.ApplyTo(entity);

    protected override ItemNroSerieDisplay ToDisplay(Db.ItemsNroSeries entity) => entity.ToDisplay();
}

public interface IDeleteItemNroSerieUseCase
{
    Task ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class DeleteItemNroSerieUseCase(IItemNroSerieRepository repository, IRedisCacheService cache)
    : DeleteUseCaseBase<Db.ItemsNroSeries, int, ItemNroSerieFilter>(repository, cache), IDeleteItemNroSerieUseCase
{
    protected override string EntityName => "ItemNroSerie";
}
