// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Items;
using API.SERVICE.Mappings.Items;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Items;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Items;

public interface IGetItemOfertaListUseCase
{
    Task<PagedResult<ItemOfertaDisplay>> ExecuteAsync(ItemOfertaFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetItemOfertaListUseCase(IItemOfertaRepository repository)
    : GetListUseCaseBase<Db.ItemsOfertas, ItemOfertaFilter, ItemOfertaDisplay>(repository), IGetItemOfertaListUseCase
{
    protected override ItemOfertaDisplay ToDisplay(Db.ItemsOfertas entity) => entity.ToDisplay();
}

public interface IGetItemOfertaByIdUseCase
{
    Task<ItemOfertaDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetItemOfertaByIdUseCase(IItemOfertaRepository repository)
    : GetByIdUseCaseBase<Db.ItemsOfertas, int, ItemOfertaFilter, ItemOfertaDisplay>(repository), IGetItemOfertaByIdUseCase
{
    protected override string EntityName => "ItemOferta";

    protected override ItemOfertaDisplay ToDisplay(Db.ItemsOfertas entity) => entity.ToDisplay();
}

public interface ICreateItemOfertaUseCase
{
    Task<ItemOfertaDisplay> ExecuteAsync(ItemOfertaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateItemOfertaUseCase(IItemOfertaRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.ItemsOfertas, int, ItemOfertaFilter, ItemOfertaDto, ItemOfertaDisplay>(repository, cache), ICreateItemOfertaUseCase
{
    protected override string EntityName => "ItemOferta";

    protected override Db.ItemsOfertas ToEntity(ItemOfertaDto dto) => dto.ToEntity();

    protected override ItemOfertaDisplay ToDisplay(Db.ItemsOfertas entity) => entity.ToDisplay();
}

public interface IUpdateItemOfertaUseCase
{
    Task<ItemOfertaDisplay> ExecuteAsync(int id, ItemOfertaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateItemOfertaUseCase(IItemOfertaRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.ItemsOfertas, int, ItemOfertaFilter, ItemOfertaDto, ItemOfertaDisplay>(repository, cache), IUpdateItemOfertaUseCase
{
    protected override string EntityName => "ItemOferta";

    protected override void Apply(ItemOfertaDto dto, Db.ItemsOfertas entity) => dto.ApplyTo(entity);

    protected override ItemOfertaDisplay ToDisplay(Db.ItemsOfertas entity) => entity.ToDisplay();
}

public interface IDeleteItemOfertaUseCase
{
    Task ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class DeleteItemOfertaUseCase(IItemOfertaRepository repository, IRedisCacheService cache)
    : DeleteUseCaseBase<Db.ItemsOfertas, int, ItemOfertaFilter>(repository, cache), IDeleteItemOfertaUseCase
{
    protected override string EntityName => "ItemOferta";
}
