// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Items;
using API.SERVICE.Mappings.Items;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Items;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Items;

public interface IGetItemListUseCase
{
    Task<PagedResult<ItemDisplay>> ExecuteAsync(ItemFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetItemListUseCase(IItemRepository repository)
    : GetListUseCaseBase<Db.Items, ItemFilter, ItemDisplay>(repository), IGetItemListUseCase
{
    protected override ItemDisplay ToDisplay(Db.Items entity) => entity.ToDisplay();
}

public interface IGetItemByIdUseCase
{
    Task<ItemDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetItemByIdUseCase(IItemRepository repository)
    : GetByIdUseCaseBase<Db.Items, int, ItemFilter, ItemDisplay>(repository), IGetItemByIdUseCase
{
    protected override string EntityName => "Item";

    protected override ItemDisplay ToDisplay(Db.Items entity) => entity.ToDisplay();
}
