// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Items;
using API.SERVICE.Mappings.Items;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Items;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Items;

public interface IGetItemImpuestoListUseCase
{
    Task<PagedResult<ItemImpuestoDisplay>> ExecuteAsync(ItemImpuestoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetItemImpuestoListUseCase(IItemImpuestoRepository repository)
    : GetListUseCaseBase<Db.ItemsImpuestos, ItemImpuestoFilter, ItemImpuestoDisplay>(repository), IGetItemImpuestoListUseCase
{
    protected override ItemImpuestoDisplay ToDisplay(Db.ItemsImpuestos entity) => entity.ToDisplay();
}

public interface IGetItemImpuestoByIdUseCase
{
    Task<ItemImpuestoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetItemImpuestoByIdUseCase(IItemImpuestoRepository repository)
    : GetByIdUseCaseBase<Db.ItemsImpuestos, int, ItemImpuestoFilter, ItemImpuestoDisplay>(repository), IGetItemImpuestoByIdUseCase
{
    protected override string EntityName => "ItemImpuesto";

    protected override ItemImpuestoDisplay ToDisplay(Db.ItemsImpuestos entity) => entity.ToDisplay();
}

public interface ICreateItemImpuestoUseCase
{
    Task<ItemImpuestoDisplay> ExecuteAsync(ItemImpuestoDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateItemImpuestoUseCase(IItemImpuestoRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.ItemsImpuestos, int, ItemImpuestoFilter, ItemImpuestoDto, ItemImpuestoDisplay>(repository, cache), ICreateItemImpuestoUseCase
{
    protected override string EntityName => "ItemImpuesto";

    protected override Db.ItemsImpuestos ToEntity(ItemImpuestoDto dto) => dto.ToEntity();

    protected override ItemImpuestoDisplay ToDisplay(Db.ItemsImpuestos entity) => entity.ToDisplay();
}

public interface IDeleteItemImpuestoUseCase
{
    Task ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class DeleteItemImpuestoUseCase(IItemImpuestoRepository repository, IRedisCacheService cache)
    : DeleteUseCaseBase<Db.ItemsImpuestos, int, ItemImpuestoFilter>(repository, cache), IDeleteItemImpuestoUseCase
{
    protected override string EntityName => "ItemImpuesto";
}
