// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Items;
using API.SERVICE.Mappings.Items;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Items;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Items;

public static class ListaPrecioCacheKeys
{
    public static readonly string Lookup = CacheKeys.For("Items", "ListaPrecio", "lookup");
}

public interface IGetListaPrecioListUseCase
{
    Task<PagedResult<ListaPrecioDisplay>> ExecuteAsync(ListaPrecioFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetListaPrecioListUseCase(IListaPrecioRepository repository)
    : GetListUseCaseBase<Db.ListasPrecio, ListaPrecioFilter, ListaPrecioDisplay>(repository), IGetListaPrecioListUseCase
{
    protected override ListaPrecioDisplay ToDisplay(Db.ListasPrecio entity) => entity.ToDisplay();
}

public interface IGetListaPrecioByIdUseCase
{
    Task<ListaPrecioDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetListaPrecioByIdUseCase(IListaPrecioRepository repository)
    : GetByIdUseCaseBase<Db.ListasPrecio, int, ListaPrecioFilter, ListaPrecioDisplay>(repository), IGetListaPrecioByIdUseCase
{
    protected override string EntityName => "ListaPrecio";

    protected override ListaPrecioDisplay ToDisplay(Db.ListasPrecio entity) => entity.ToDisplay();
}

public interface IGetListaPrecioLookupUseCase
{
    Task<IReadOnlyList<ListaPrecioDisplay>> ExecuteAsync(CancellationToken cancellationToken = default);
}

public sealed partial class GetListaPrecioLookupUseCase(IListaPrecioRepository repository, IRedisCacheService cache)
    : GetLookupUseCaseBase<Db.ListasPrecio, int, ListaPrecioFilter, ListaPrecioDisplay>(repository, cache), IGetListaPrecioLookupUseCase
{
    protected override string CacheKey => ListaPrecioCacheKeys.Lookup;

    protected override ListaPrecioDisplay ToDisplay(Db.ListasPrecio entity) => entity.ToDisplay();
}

public interface ICreateListaPrecioUseCase
{
    Task<ListaPrecioDisplay> ExecuteAsync(ListaPrecioDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateListaPrecioUseCase(IListaPrecioRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.ListasPrecio, int, ListaPrecioFilter, ListaPrecioDto, ListaPrecioDisplay>(repository, cache), ICreateListaPrecioUseCase
{
    protected override string EntityName => "ListaPrecio";

    protected override string? CacheKey => ListaPrecioCacheKeys.Lookup;

    protected override Db.ListasPrecio ToEntity(ListaPrecioDto dto) => dto.ToEntity();

    protected override ListaPrecioDisplay ToDisplay(Db.ListasPrecio entity) => entity.ToDisplay();
}

public interface IUpdateListaPrecioUseCase
{
    Task<ListaPrecioDisplay> ExecuteAsync(int id, ListaPrecioDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateListaPrecioUseCase(IListaPrecioRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.ListasPrecio, int, ListaPrecioFilter, ListaPrecioDto, ListaPrecioDisplay>(repository, cache), IUpdateListaPrecioUseCase
{
    protected override string EntityName => "ListaPrecio";

    protected override string? CacheKey => ListaPrecioCacheKeys.Lookup;

    protected override void Apply(ListaPrecioDto dto, Db.ListasPrecio entity) => dto.ApplyTo(entity);

    protected override ListaPrecioDisplay ToDisplay(Db.ListasPrecio entity) => entity.ToDisplay();
}
