// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Items;
using API.SERVICE.Mappings.Items;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Items;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Items;

public interface IGetModeloActualizacionListUseCase
{
    Task<PagedResult<ModeloActualizacionDisplay>> ExecuteAsync(ModeloActualizacionFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetModeloActualizacionListUseCase(IModeloActualizacionRepository repository)
    : GetListUseCaseBase<Db.ModelosActualizacion, ModeloActualizacionFilter, ModeloActualizacionDisplay>(repository), IGetModeloActualizacionListUseCase
{
    protected override ModeloActualizacionDisplay ToDisplay(Db.ModelosActualizacion entity) => entity.ToDisplay();
}

public interface IGetModeloActualizacionByIdUseCase
{
    Task<ModeloActualizacionDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetModeloActualizacionByIdUseCase(IModeloActualizacionRepository repository)
    : GetByIdUseCaseBase<Db.ModelosActualizacion, int, ModeloActualizacionFilter, ModeloActualizacionDisplay>(repository), IGetModeloActualizacionByIdUseCase
{
    protected override string EntityName => "ModeloActualizacion";

    protected override ModeloActualizacionDisplay ToDisplay(Db.ModelosActualizacion entity) => entity.ToDisplay();
}
