// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Items;
using API.SERVICE.Mappings.Items;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Items;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Items;

public interface IGetRubroActualizacionListUseCase
{
    Task<PagedResult<RubroActualizacionDisplay>> ExecuteAsync(RubroActualizacionFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetRubroActualizacionListUseCase(IRubroActualizacionRepository repository)
    : GetListUseCaseBase<Db.RubrosActualizacion, RubroActualizacionFilter, RubroActualizacionDisplay>(repository), IGetRubroActualizacionListUseCase
{
    protected override RubroActualizacionDisplay ToDisplay(Db.RubrosActualizacion entity) => entity.ToDisplay();
}

public interface IGetRubroActualizacionByIdUseCase
{
    Task<RubroActualizacionDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetRubroActualizacionByIdUseCase(IRubroActualizacionRepository repository)
    : GetByIdUseCaseBase<Db.RubrosActualizacion, int, RubroActualizacionFilter, RubroActualizacionDisplay>(repository), IGetRubroActualizacionByIdUseCase
{
    protected override string EntityName => "RubroActualizacion";

    protected override RubroActualizacionDisplay ToDisplay(Db.RubrosActualizacion entity) => entity.ToDisplay();
}
