// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Items;
using API.SERVICE.Mappings.Items;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Items;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Items;

public static class UbicacionCacheKeys
{
    public static readonly string Lookup = CacheKeys.For("Items", "Ubicacion", "lookup");
}

public interface IGetUbicacionListUseCase
{
    Task<PagedResult<UbicacionDisplay>> ExecuteAsync(UbicacionFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetUbicacionListUseCase(IUbicacionRepository repository)
    : GetListUseCaseBase<Db.Ubicaciones, UbicacionFilter, UbicacionDisplay>(repository), IGetUbicacionListUseCase
{
    protected override UbicacionDisplay ToDisplay(Db.Ubicaciones entity) => entity.ToDisplay();
}

public interface IGetUbicacionByIdUseCase
{
    Task<UbicacionDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetUbicacionByIdUseCase(IUbicacionRepository repository)
    : GetByIdUseCaseBase<Db.Ubicaciones, int, UbicacionFilter, UbicacionDisplay>(repository), IGetUbicacionByIdUseCase
{
    protected override string EntityName => "Ubicacion";

    protected override UbicacionDisplay ToDisplay(Db.Ubicaciones entity) => entity.ToDisplay();
}

public interface IGetUbicacionLookupUseCase
{
    Task<IReadOnlyList<UbicacionDisplay>> ExecuteAsync(CancellationToken cancellationToken = default);
}

public sealed partial class GetUbicacionLookupUseCase(IUbicacionRepository repository, IRedisCacheService cache)
    : GetLookupUseCaseBase<Db.Ubicaciones, int, UbicacionFilter, UbicacionDisplay>(repository, cache), IGetUbicacionLookupUseCase
{
    protected override string CacheKey => UbicacionCacheKeys.Lookup;

    protected override UbicacionDisplay ToDisplay(Db.Ubicaciones entity) => entity.ToDisplay();
}

public interface ICreateUbicacionUseCase
{
    Task<UbicacionDisplay> ExecuteAsync(UbicacionDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateUbicacionUseCase(IUbicacionRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.Ubicaciones, int, UbicacionFilter, UbicacionDto, UbicacionDisplay>(repository, cache), ICreateUbicacionUseCase
{
    protected override string EntityName => "Ubicacion";

    protected override string? CacheKey => UbicacionCacheKeys.Lookup;

    protected override Db.Ubicaciones ToEntity(UbicacionDto dto) => dto.ToEntity();

    protected override UbicacionDisplay ToDisplay(Db.Ubicaciones entity) => entity.ToDisplay();
}

public interface IUpdateUbicacionUseCase
{
    Task<UbicacionDisplay> ExecuteAsync(int id, UbicacionDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateUbicacionUseCase(IUbicacionRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.Ubicaciones, int, UbicacionFilter, UbicacionDto, UbicacionDisplay>(repository, cache), IUpdateUbicacionUseCase
{
    protected override string EntityName => "Ubicacion";

    protected override string? CacheKey => UbicacionCacheKeys.Lookup;

    protected override void Apply(UbicacionDto dto, Db.Ubicaciones entity) => dto.ApplyTo(entity);

    protected override UbicacionDisplay ToDisplay(Db.Ubicaciones entity) => entity.ToDisplay();
}
