// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Items;

/// <summary>Salida de dbo.Combos.</summary>
public sealed partial class ComboDisplay
{
    public int IdCombo { get; init; }
    public string? Nombre { get; init; }
    public decimal? PrecioCombo { get; init; }
    public DateTime? FechaInicio { get; init; }
    public DateTime? FechaFin { get; init; }
    public int? IdSucursal { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.Combos.</summary>
public sealed partial class ComboDto
{
    /// <summary>Clave no autonumérica: obligatoria en el alta, se ignora en la modificación (va en la ruta).</summary>
    [Required]
    public int? IdCombo { get; set; }

    [MaxLength(100)]
    public string? Nombre { get; set; }

    public decimal? PrecioCombo { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public int? IdSucursal { get; set; }
}

/// <summary>Filtros del listado de dbo.Combos.</summary>
public sealed partial class ComboFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Nombre.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdSucursal { get; set; }

    /// <summary>FechaInicio desde (inclusive).</summary>
    public DateTime? FechaInicioDesde { get; set; }

    /// <summary>FechaInicio hasta (inclusive, día completo).</summary>
    public DateTime? FechaInicioHasta { get; set; }
}
