// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Items;

/// <summary>Salida de dbo.Items.</summary>
public sealed partial class ItemDisplay
{
    public int IdItem { get; init; }
    public string? Descripcion { get; init; }
    public int? IdItemTipo { get; init; }
    public int? IdEmpresa { get; init; }
    public int? IdRubro { get; init; }
    public int? IdSubRubro { get; init; }
    public int? IdMarca { get; init; }
    public int? IdModelo { get; init; }
    public DateTime? FechaCompra { get; init; }
    public DateTime? FechaVenta { get; init; }
    public int? IdUnidadMedida { get; init; }
    public string? CodFabrica { get; init; }
    public bool? TieneDetalle { get; init; }
    public bool? MueveStock { get; init; }
    public decimal? StockMaximo { get; init; }
    public decimal? StockMinimo { get; init; }
    public decimal? StockActual { get; init; }
    public int? IdUbicacion { get; init; }
    public decimal? UnidadesXbulto { get; init; }
    public string? Barcode { get; init; }
    public decimal? Neto { get; init; }
    public int? CuentaDebe { get; init; }
    public int? CuentaHaber { get; init; }
    public decimal? MtsKgs { get; init; }
    public int? Estado { get; init; }
    public bool? EsDolar { get; init; }
    public decimal? Rentabilidad { get; init; }
    public decimal? StockInicial { get; init; }
    public bool? MostrarWeb { get; init; }
    public string? Detalle { get; init; }
}

/// <summary>Filtros del listado de dbo.Items.</summary>
public sealed partial class ItemFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion, Detalle.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdItemTipo { get; set; }

    public int? IdEmpresa { get; set; }

    public int? IdRubro { get; set; }

    public int? IdSubRubro { get; set; }

    public int? IdMarca { get; set; }

    public int? IdModelo { get; set; }

    public int? IdUnidadMedida { get; set; }

    public int? IdUbicacion { get; set; }

    public int? Estado { get; set; }

    /// <summary>FechaCompra desde (inclusive).</summary>
    public DateTime? FechaCompraDesde { get; set; }

    /// <summary>FechaCompra hasta (inclusive, día completo).</summary>
    public DateTime? FechaCompraHasta { get; set; }
}
