// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Items;

/// <summary>Salida de dbo.ItemsOfertas.</summary>
public sealed partial class ItemOfertaDisplay
{
    public int IdItemOferta { get; init; }
    public int? IdItems { get; init; }
    public decimal? Precio { get; init; }
    public bool? Web { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.ItemsOfertas.</summary>
public sealed partial class ItemOfertaDto
{
    public int? IdItems { get; set; }

    public decimal? Precio { get; set; }

    public bool? Web { get; set; }
}

/// <summary>Filtros del listado de dbo.ItemsOfertas.</summary>
public sealed partial class ItemOfertaFilter : PagedQuery
{
    public int? IdItems { get; set; }
}
