// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Items;

/// <summary>Salida de dbo.ItemsEnvanses.</summary>
public sealed partial class ItemEnvaseDisplay
{
    public int IdItemEnvase { get; init; }
    public int? IdItem { get; init; }
    public int? IdEnvase { get; init; }
    public decimal? CantidadKg { get; init; }
    public decimal? CantidadEnvases { get; init; }
    public decimal? PesoEnvase { get; init; }
    public bool? Activo { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.ItemsEnvanses.</summary>
public sealed partial class ItemEnvaseDto
{
    public int? IdItem { get; set; }

    public int? IdEnvase { get; set; }

    public decimal? CantidadKg { get; set; }

    public decimal? CantidadEnvases { get; set; }

    public decimal? PesoEnvase { get; set; }

    public bool? Activo { get; set; }
}

/// <summary>Filtros del listado de dbo.ItemsEnvanses.</summary>
public sealed partial class ItemEnvaseFilter : PagedQuery
{
    public int? IdItem { get; set; }

    public int? IdEnvase { get; set; }

    public bool? Activo { get; set; }
}
