// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Items;

/// <summary>Salida de dbo.MarcasActualizacion.</summary>
public sealed partial class MarcaActualizacionDisplay
{
    public int IdMarcaActualizacion { get; init; }
    public int? IdMarca { get; init; }
    public decimal? Alicuota { get; init; }
    public int? IdUsuario { get; init; }
    public DateTime? FechaActualizacion { get; init; }
}

/// <summary>Filtros del listado de dbo.MarcasActualizacion.</summary>
public sealed partial class MarcaActualizacionFilter : PagedQuery
{
    public int? IdMarca { get; set; }

    public int? IdUsuario { get; set; }

    /// <summary>FechaActualizacion desde (inclusive).</summary>
    public DateTime? FechaActualizacionDesde { get; set; }

    /// <summary>FechaActualizacion hasta (inclusive, día completo).</summary>
    public DateTime? FechaActualizacionHasta { get; set; }
}
