// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Items;

/// <summary>Salida de dbo.OfertasSucursales.</summary>
public sealed partial class OfertaSucursalDisplay
{
    public int IdOferta { get; init; }
    public int IdSucursal { get; init; }
}

/// <summary>Filtros del listado de dbo.OfertasSucursales.</summary>
public sealed partial class OfertaSucursalFilter : PagedQuery
{
    public int? IdOferta { get; set; }

    public int? IdSucursal { get; set; }
}
