// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Items;

/// <summary>Salida de dbo.ProductosCombos.</summary>
public sealed partial class ProductoComboDisplay
{
    public int IdComboProducto { get; init; }
    public int? IdCombo { get; init; }
    public int? IdItem { get; init; }
    public int? Cantidad { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.ProductosCombos.</summary>
public sealed partial class ProductoComboDto
{
    /// <summary>Clave no autonumérica: obligatoria en el alta, se ignora en la modificación (va en la ruta).</summary>
    [Required]
    public int? IdComboProducto { get; set; }

    public int? IdCombo { get; set; }

    public int? IdItem { get; set; }

    public int? Cantidad { get; set; }
}

/// <summary>Filtros del listado de dbo.ProductosCombos.</summary>
public sealed partial class ProductoComboFilter : PagedQuery
{
    public int? IdCombo { get; set; }

    public int? IdItem { get; set; }
}
