// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Items;

/// <summary>Salida de dbo.SubRubros.</summary>
public sealed partial class SubRubroDisplay
{
    public int IdSubRubro { get; init; }
    public string? Descripcion { get; init; }
    public int? IdRubro { get; init; }
    public int? IdEmpresa { get; init; }
    public int? Estado { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.SubRubros.</summary>
public sealed partial class SubRubroDto
{
    [MaxLength(50)]
    public string? Descripcion { get; set; }

    public int? IdRubro { get; set; }

    public int? IdEmpresa { get; set; }

    public int? Estado { get; set; }
}

/// <summary>Filtros del listado de dbo.SubRubros.</summary>
public sealed partial class SubRubroFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdRubro { get; set; }

    public int? IdEmpresa { get; set; }

    public int? Estado { get; set; }
}
