// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Stock;
using API.SERVICE.Mappings.Stock;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Stock;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Stock;

public interface IGetEntidadCtaCteStockMovimientoDetalleListUseCase
{
    Task<PagedResult<EntidadCtaCteStockMovimientoDetalleDisplay>> ExecuteAsync(EntidadCtaCteStockMovimientoDetalleFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCtaCteStockMovimientoDetalleListUseCase(IEntidadCtaCteStockMovimientoDetalleRepository repository)
    : GetListUseCaseBase<Db.EntidadesCtaCteStockMovimientosDetalle, EntidadCtaCteStockMovimientoDetalleFilter, EntidadCtaCteStockMovimientoDetalleDisplay>(repository), IGetEntidadCtaCteStockMovimientoDetalleListUseCase
{
    protected override EntidadCtaCteStockMovimientoDetalleDisplay ToDisplay(Db.EntidadesCtaCteStockMovimientosDetalle entity) => entity.ToDisplay();
}

public interface IGetEntidadCtaCteStockMovimientoDetalleByIdUseCase
{
    Task<EntidadCtaCteStockMovimientoDetalleDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCtaCteStockMovimientoDetalleByIdUseCase(IEntidadCtaCteStockMovimientoDetalleRepository repository)
    : GetByIdUseCaseBase<Db.EntidadesCtaCteStockMovimientosDetalle, int, EntidadCtaCteStockMovimientoDetalleFilter, EntidadCtaCteStockMovimientoDetalleDisplay>(repository), IGetEntidadCtaCteStockMovimientoDetalleByIdUseCase
{
    protected override string EntityName => "EntidadCtaCteStockMovimientoDetalle";

    protected override EntidadCtaCteStockMovimientoDetalleDisplay ToDisplay(Db.EntidadesCtaCteStockMovimientosDetalle entity) => entity.ToDisplay();
}
