// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Stock;
using API.SERVICE.Mappings.Stock;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Stock;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Stock;

public interface IGetItemMovimientoDetalleListUseCase
{
    Task<PagedResult<ItemMovimientoDetalleDisplay>> ExecuteAsync(ItemMovimientoDetalleFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetItemMovimientoDetalleListUseCase(IItemMovimientoDetalleRepository repository)
    : GetListUseCaseBase<Db.ItemsMovimientosDetalles, ItemMovimientoDetalleFilter, ItemMovimientoDetalleDisplay>(repository), IGetItemMovimientoDetalleListUseCase
{
    protected override ItemMovimientoDetalleDisplay ToDisplay(Db.ItemsMovimientosDetalles entity) => entity.ToDisplay();
}

public interface IGetItemMovimientoDetalleByIdUseCase
{
    Task<ItemMovimientoDetalleDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetItemMovimientoDetalleByIdUseCase(IItemMovimientoDetalleRepository repository)
    : GetByIdUseCaseBase<Db.ItemsMovimientosDetalles, int, ItemMovimientoDetalleFilter, ItemMovimientoDetalleDisplay>(repository), IGetItemMovimientoDetalleByIdUseCase
{
    protected override string EntityName => "ItemMovimientoDetalle";

    protected override ItemMovimientoDetalleDisplay ToDisplay(Db.ItemsMovimientosDetalles entity) => entity.ToDisplay();
}
