// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Afip;

/// <summary>Salida de dbo.Retenciones.</summary>
public sealed partial class RetencionDisplay
{
    public int IdRetencion { get; init; }
    public int? IdRetencionTipo { get; init; }
    public string? Descripcion { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public int? IdComprobante { get; init; }
    public string? NroComprobante { get; init; }
    public DateTime? FechaEmision { get; init; }
    public DateTime? FechaRecepcion { get; init; }
    public decimal? Total { get; init; }
    public int? Estado { get; init; }
    public int? IdEntidad { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.Retenciones.</summary>
public sealed partial class RetencionDto
{
    public int? IdRetencionTipo { get; set; }

    [MaxLength(50)]
    public string? Descripcion { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdComprobante { get; set; }

    [MaxLength(50)]
    public string? NroComprobante { get; set; }

    public DateTime? FechaEmision { get; set; }

    public DateTime? FechaRecepcion { get; set; }

    public decimal? Total { get; set; }

    public int? Estado { get; set; }

    public int? IdEntidad { get; set; }
}

/// <summary>Filtros del listado de dbo.Retenciones.</summary>
public sealed partial class RetencionFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdRetencionTipo { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdComprobante { get; set; }

    public int? IdEntidad { get; set; }

    public int? Estado { get; set; }

    /// <summary>FechaEmision desde (inclusive).</summary>
    public DateTime? FechaEmisionDesde { get; set; }

    /// <summary>FechaEmision hasta (inclusive, día completo).</summary>
    public DateTime? FechaEmisionHasta { get; set; }
}
