// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Afip;

/// <summary>Salida de dbo.TxtComprasAlicuotas.</summary>
public sealed partial class TxtCompraAlicuotaDisplay
{
    public int TxtCompraAlicuota { get; init; }
    public string? TipoComprobante { get; init; }
    public string? PuntoVenta { get; init; }
    public string? NroComprobante { get; init; }
    public string? CodVendedor { get; init; }
    public string? CuitVendedor { get; init; }
    public decimal? NetoGravado { get; init; }
    public string? Alicuota { get; init; }
    public decimal? ImporteLiquidado { get; init; }
    public int? Mes { get; init; }
    public int? Anio { get; init; }
    public DateOnly? FechaAlta { get; init; }
    public int? IdComprobante { get; init; }
    public int? IdComprobanteTipo { get; init; }
}

/// <summary>Filtros del listado de dbo.TxtComprasAlicuotas.</summary>
public sealed partial class TxtCompraAlicuotaFilter : PagedQuery
{
    public int? IdComprobante { get; set; }

    public int? IdComprobanteTipo { get; set; }

    /// <summary>FechaAlta desde (inclusive).</summary>
    public DateOnly? FechaAltaDesde { get; set; }

    /// <summary>FechaAlta hasta (inclusive, día completo).</summary>
    public DateOnly? FechaAltaHasta { get; set; }
}
