// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Ventas;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Ventas;

/// <summary>Persistencia de dbo.DocumentosClienteRemitosDetalle.</summary>
public partial interface IDocumentoClienteRemitoDetalleRepository : global::API.SERVICE.Interfaces.IReadRepository<Db.DocumentosClienteRemitosDetalle, int, DocumentoClienteRemitoDetalleFilter>
{
}
