// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Afip;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Afip;

public static partial class OtroTributoMappings
{
    public static OtroTributoDisplay ToDisplay(this Db.OtrosTributos entity) => new()
    {
        IdOtrosTributos = entity.IdOtrosTributos,
        Codigo = entity.Codigo,
        Descripcion = entity.Descripcion,
        Observaciones = entity.Observaciones,
        Estado = entity.Estado,
    };

    public static Db.OtrosTributos ToEntity(this OtroTributoDto dto)
    {
        var entity = new Db.OtrosTributos();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this OtroTributoDto dto, Db.OtrosTributos entity)
    {
        entity.Codigo = dto.Codigo;
        entity.Descripcion = dto.Descripcion;
        entity.Observaciones = dto.Observaciones;
        entity.Estado = dto.Estado;
    }
}
