// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Afip;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Afip;

public static partial class TxtCompraAlicuotaMappings
{
    public static TxtCompraAlicuotaDisplay ToDisplay(this Db.TxtComprasAlicuotas entity) => new()
    {
        TxtCompraAlicuota = entity.TxtCompraAlicuota,
        TipoComprobante = entity.TipoComprobante,
        PuntoVenta = entity.PuntoVenta,
        NroComprobante = entity.NroComprobante,
        CodVendedor = entity.CodVendedor,
        CuitVendedor = entity.CuitVendedor,
        NetoGravado = entity.NetoGravado,
        Alicuota = entity.Alicuota,
        ImporteLiquidado = entity.ImporteLiquidado,
        Mes = entity.Mes,
        Anio = entity.Anio,
        FechaAlta = entity.FechaAlta,
        IdComprobante = entity.IdComprobante,
        IdComprobanteTipo = entity.IdComprobanteTipo,
    };
}
