// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class ComboRepository : EfRepository<Db.Combos, int, ComboFilter>, IComboRepository
{
    public ComboRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Combos> ApplyFilter(IQueryable<Db.Combos> query, ComboFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Nombre != null && x.Nombre.Contains(q)));
        }

        if (filter.IdSucursal is not null)
            query = query.Where(x => x.IdSucursal == filter.IdSucursal);

        if (filter.FechaInicioDesde is not null)
            query = query.Where(x => x.FechaInicio >= filter.FechaInicioDesde.Value);

        if (filter.FechaInicioHasta is not null)
        {
            var hasta = filter.FechaInicioHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaInicio < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.Combos> ApplyDefaultOrder(IQueryable<Db.Combos> query) =>
        query.OrderByDescending(x => x.IdCombo);
}
