// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class ItemOfertaRepository : EfRepository<Db.ItemsOfertas, int, ItemOfertaFilter>, IItemOfertaRepository
{
    public ItemOfertaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.ItemsOfertas> ApplyFilter(IQueryable<Db.ItemsOfertas> query, ItemOfertaFilter filter)
    {
        if (filter.IdItems is not null)
            query = query.Where(x => x.IdItems == filter.IdItems);

        return query;
    }

    protected override IOrderedQueryable<Db.ItemsOfertas> ApplyDefaultOrder(IQueryable<Db.ItemsOfertas> query) =>
        query.OrderByDescending(x => x.IdItemOferta);
}
