// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class ItemNroSerieRepository : EfRepository<Db.ItemsNroSeries, int, ItemNroSerieFilter>, IItemNroSerieRepository
{
    public ItemNroSerieRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.ItemsNroSeries> ApplyFilter(IQueryable<Db.ItemsNroSeries> query, ItemNroSerieFilter filter)
    {
        if (filter.IdItem is not null)
            query = query.Where(x => x.IdItem == filter.IdItem);

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        if (filter.IdComprobante is not null)
            query = query.Where(x => x.IdComprobante == filter.IdComprobante);

        if (filter.IdDocumentoClienteDetalle is not null)
            query = query.Where(x => x.IdDocumentoClienteDetalle == filter.IdDocumentoClienteDetalle);

        if (filter.IdSucursal is not null)
            query = query.Where(x => x.IdSucursal == filter.IdSucursal);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        return query;
    }

    protected override IOrderedQueryable<Db.ItemsNroSeries> ApplyDefaultOrder(IQueryable<Db.ItemsNroSeries> query) =>
        query.OrderByDescending(x => x.IdItemNroSerie);
}
