// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class ItemPrecioActualizacionRepository : EfRepository<Db.ItemsPreciosActualizacion, int, ItemPrecioActualizacionFilter>, IItemPrecioActualizacionRepository
{
    public ItemPrecioActualizacionRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.ItemsPreciosActualizacion> ApplyFilter(IQueryable<Db.ItemsPreciosActualizacion> query, ItemPrecioActualizacionFilter filter)
    {
        if (filter.IdItem is not null)
            query = query.Where(x => x.IdItem == filter.IdItem);

        if (filter.IdUsario is not null)
            query = query.Where(x => x.IdUsario == filter.IdUsario);

        if (filter.FechaActualizacionDesde is not null)
            query = query.Where(x => x.FechaActualizacion >= filter.FechaActualizacionDesde.Value);

        if (filter.FechaActualizacionHasta is not null)
        {
            var hasta = filter.FechaActualizacionHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaActualizacion < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.ItemsPreciosActualizacion> ApplyDefaultOrder(IQueryable<Db.ItemsPreciosActualizacion> query) =>
        query.OrderByDescending(x => x.IdItemPrecioActulizacion);
}
