// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class MarcaActualizacionRepository : EfRepository<Db.MarcasActualizacion, int, MarcaActualizacionFilter>, IMarcaActualizacionRepository
{
    public MarcaActualizacionRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.MarcasActualizacion> ApplyFilter(IQueryable<Db.MarcasActualizacion> query, MarcaActualizacionFilter filter)
    {
        if (filter.IdMarca is not null)
            query = query.Where(x => x.IdMarca == filter.IdMarca);

        if (filter.IdUsuario is not null)
            query = query.Where(x => x.IdUsuario == filter.IdUsuario);

        if (filter.FechaActualizacionDesde is not null)
            query = query.Where(x => x.FechaActualizacion >= filter.FechaActualizacionDesde.Value);

        if (filter.FechaActualizacionHasta is not null)
        {
            var hasta = filter.FechaActualizacionHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaActualizacion < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.MarcasActualizacion> ApplyDefaultOrder(IQueryable<Db.MarcasActualizacion> query) =>
        query.OrderByDescending(x => x.IdMarcaActualizacion);
}
