// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class ModeloRepository : EfRepository<Db.Modelos, int, ModeloFilter>, IModeloRepository
{
    public ModeloRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Modelos> ApplyFilter(IQueryable<Db.Modelos> query, ModeloFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        if (filter.IdMarca is not null)
            query = query.Where(x => x.IdMarca == filter.IdMarca);

        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        return query;
    }

    protected override IOrderedQueryable<Db.Modelos> ApplyDefaultOrder(IQueryable<Db.Modelos> query) =>
        query.OrderBy(x => x.Descripcion);
}
