// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class OfertaRepository : EfQueryRepository<Db.Ofertas, OfertaFilter>, IOfertaRepository
{
    public OfertaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Ofertas> ApplyFilter(IQueryable<Db.Ofertas> query, OfertaFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => x.Nombre.Contains(q));
        }

        if (filter.IdOferta is not null)
            query = query.Where(x => x.IdOferta == filter.IdOferta.Value);

        if (filter.IdItem is not null)
            query = query.Where(x => x.IdItem == filter.IdItem.Value);

        if (filter.IdEstado is not null)
            query = query.Where(x => x.IdEstado == filter.IdEstado.Value);

        if (filter.FechaInicioDesde is not null)
            query = query.Where(x => x.FechaInicio >= filter.FechaInicioDesde.Value);

        if (filter.FechaInicioHasta is not null)
        {
            var hasta = filter.FechaInicioHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaInicio < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.Ofertas> ApplyDefaultOrder(IQueryable<Db.Ofertas> query) =>
        query.OrderBy(x => x.IdOferta);
}
