// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class OfertaAgotamientoRepository : EfQueryRepository<Db.OfertasAgotamiento, OfertaAgotamientoFilter>, IOfertaAgotamientoRepository
{
    public OfertaAgotamientoRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.OfertasAgotamiento> ApplyFilter(IQueryable<Db.OfertasAgotamiento> query, OfertaAgotamientoFilter filter)
    {
        if (filter.IdOferta is not null)
            query = query.Where(x => x.IdOferta == filter.IdOferta.Value);

        if (filter.IdItem is not null)
            query = query.Where(x => x.IdItem == filter.IdItem.Value);

        if (filter.IdSucursal is not null)
            query = query.Where(x => x.IdSucursal == filter.IdSucursal.Value);

        return query;
    }

    protected override IOrderedQueryable<Db.OfertasAgotamiento> ApplyDefaultOrder(IQueryable<Db.OfertasAgotamiento> query) =>
        query.OrderBy(x => x.IdOferta);
}
