// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class ProductoComboRepository : EfRepository<Db.ProductosCombos, int, ProductoComboFilter>, IProductoComboRepository
{
    public ProductoComboRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.ProductosCombos> ApplyFilter(IQueryable<Db.ProductosCombos> query, ProductoComboFilter filter)
    {
        if (filter.IdCombo is not null)
            query = query.Where(x => x.IdCombo == filter.IdCombo);

        if (filter.IdItem is not null)
            query = query.Where(x => x.IdItem == filter.IdItem);

        return query;
    }

    protected override IOrderedQueryable<Db.ProductosCombos> ApplyDefaultOrder(IQueryable<Db.ProductosCombos> query) =>
        query.OrderByDescending(x => x.IdComboProducto);
}
