// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class RubroActualizacionRepository : EfRepository<Db.RubrosActualizacion, int, RubroActualizacionFilter>, IRubroActualizacionRepository
{
    public RubroActualizacionRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.RubrosActualizacion> ApplyFilter(IQueryable<Db.RubrosActualizacion> query, RubroActualizacionFilter filter)
    {
        if (filter.IdRubro is not null)
            query = query.Where(x => x.IdRubro == filter.IdRubro);

        if (filter.IdUsuario is not null)
            query = query.Where(x => x.IdUsuario == filter.IdUsuario);

        if (filter.FechaActualizacionDesde is not null)
            query = query.Where(x => x.FechaActualizacion >= filter.FechaActualizacionDesde.Value);

        if (filter.FechaActualizacionHasta is not null)
        {
            var hasta = filter.FechaActualizacionHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaActualizacion < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.RubrosActualizacion> ApplyDefaultOrder(IQueryable<Db.RubrosActualizacion> query) =>
        query.OrderByDescending(x => x.IdRubroActualizacion);
}
