// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Items;
using API.SERVICE.Models.Items;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Items;

public sealed partial class SubRubroActualizacionRepository : EfRepository<Db.SubRubrosActualizacion, int, SubRubroActualizacionFilter>, ISubRubroActualizacionRepository
{
    public SubRubroActualizacionRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.SubRubrosActualizacion> ApplyFilter(IQueryable<Db.SubRubrosActualizacion> query, SubRubroActualizacionFilter filter)
    {
        if (filter.IdSubRubro is not null)
            query = query.Where(x => x.IdSubRubro == filter.IdSubRubro);

        if (filter.IdUsuario is not null)
            query = query.Where(x => x.IdUsuario == filter.IdUsuario);

        if (filter.FechaActualizacionDesde is not null)
            query = query.Where(x => x.FechaActualizacion >= filter.FechaActualizacionDesde.Value);

        if (filter.FechaActualizacionHasta is not null)
        {
            var hasta = filter.FechaActualizacionHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaActualizacion < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.SubRubrosActualizacion> ApplyDefaultOrder(IQueryable<Db.SubRubrosActualizacion> query) =>
        query.OrderByDescending(x => x.IdSubRubroActualizacion);
}
