// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.CuentasCorrientes;
using API.SERVICE.Mappings.CuentasCorrientes;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.CuentasCorrientes;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.CuentasCorrientes;

public interface IGetEntidadCtaCteMovimientoListUseCase
{
    Task<PagedResult<EntidadCtaCteMovimientoDisplay>> ExecuteAsync(EntidadCtaCteMovimientoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCtaCteMovimientoListUseCase(IEntidadCtaCteMovimientoRepository repository)
    : GetListUseCaseBase<Db.EntidadesCtaCteMovimientos, EntidadCtaCteMovimientoFilter, EntidadCtaCteMovimientoDisplay>(repository), IGetEntidadCtaCteMovimientoListUseCase
{
    protected override EntidadCtaCteMovimientoDisplay ToDisplay(Db.EntidadesCtaCteMovimientos entity) => entity.ToDisplay();
}

public interface IGetEntidadCtaCteMovimientoByIdUseCase
{
    Task<EntidadCtaCteMovimientoDisplay> ExecuteAsync(long id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCtaCteMovimientoByIdUseCase(IEntidadCtaCteMovimientoRepository repository)
    : GetByIdUseCaseBase<Db.EntidadesCtaCteMovimientos, long, EntidadCtaCteMovimientoFilter, EntidadCtaCteMovimientoDisplay>(repository), IGetEntidadCtaCteMovimientoByIdUseCase
{
    protected override string EntityName => "EntidadCtaCteMovimiento";

    protected override EntidadCtaCteMovimientoDisplay ToDisplay(Db.EntidadesCtaCteMovimientos entity) => entity.ToDisplay();
}
