// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.CuentasCorrientes;
using API.SERVICE.Mappings.CuentasCorrientes;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.CuentasCorrientes;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.CuentasCorrientes;

public interface IGetEntidadCtaCteListUseCase
{
    Task<PagedResult<EntidadCtaCteDisplay>> ExecuteAsync(EntidadCtaCteFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCtaCteListUseCase(IEntidadCtaCteRepository repository)
    : GetListUseCaseBase<Db.EntidadesCtaCte, EntidadCtaCteFilter, EntidadCtaCteDisplay>(repository), IGetEntidadCtaCteListUseCase
{
    protected override EntidadCtaCteDisplay ToDisplay(Db.EntidadesCtaCte entity) => entity.ToDisplay();
}

public interface IGetEntidadCtaCteByIdUseCase
{
    Task<EntidadCtaCteDisplay> ExecuteAsync(long id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCtaCteByIdUseCase(IEntidadCtaCteRepository repository)
    : GetByIdUseCaseBase<Db.EntidadesCtaCte, long, EntidadCtaCteFilter, EntidadCtaCteDisplay>(repository), IGetEntidadCtaCteByIdUseCase
{
    protected override string EntityName => "EntidadCtaCte";

    protected override EntidadCtaCteDisplay ToDisplay(Db.EntidadesCtaCte entity) => entity.ToDisplay();
}
