// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Mappings.Bancos;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Bancos;

public interface IGetBancoCuentaMovimientoListUseCase
{
    Task<PagedResult<BancoCuentaMovimientoDisplay>> ExecuteAsync(BancoCuentaMovimientoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetBancoCuentaMovimientoListUseCase(IBancoCuentaMovimientoRepository repository)
    : GetListUseCaseBase<Db.BancosCuentasMovimientos, BancoCuentaMovimientoFilter, BancoCuentaMovimientoDisplay>(repository), IGetBancoCuentaMovimientoListUseCase
{
    protected override BancoCuentaMovimientoDisplay ToDisplay(Db.BancosCuentasMovimientos entity) => entity.ToDisplay();
}

public interface IGetBancoCuentaMovimientoByIdUseCase
{
    Task<BancoCuentaMovimientoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetBancoCuentaMovimientoByIdUseCase(IBancoCuentaMovimientoRepository repository)
    : GetByIdUseCaseBase<Db.BancosCuentasMovimientos, int, BancoCuentaMovimientoFilter, BancoCuentaMovimientoDisplay>(repository), IGetBancoCuentaMovimientoByIdUseCase
{
    protected override string EntityName => "BancoCuentaMovimiento";

    protected override BancoCuentaMovimientoDisplay ToDisplay(Db.BancosCuentasMovimientos entity) => entity.ToDisplay();
}
