// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Mappings.Bancos;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Bancos;

public interface IGetBancoChequeListUseCase
{
    Task<PagedResult<BancoChequeDisplay>> ExecuteAsync(BancoChequeFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetBancoChequeListUseCase(IBancoChequeRepository repository)
    : GetListUseCaseBase<Db.BancosCheques, BancoChequeFilter, BancoChequeDisplay>(repository), IGetBancoChequeListUseCase
{
    protected override BancoChequeDisplay ToDisplay(Db.BancosCheques entity) => entity.ToDisplay();
}

public interface IGetBancoChequeByIdUseCase
{
    Task<BancoChequeDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetBancoChequeByIdUseCase(IBancoChequeRepository repository)
    : GetByIdUseCaseBase<Db.BancosCheques, int, BancoChequeFilter, BancoChequeDisplay>(repository), IGetBancoChequeByIdUseCase
{
    protected override string EntityName => "BancoCheque";

    protected override BancoChequeDisplay ToDisplay(Db.BancosCheques entity) => entity.ToDisplay();
}
