// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Mappings.Bancos;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Bancos;

public static class BancoCuentaCacheKeys
{
    public static readonly string Lookup = CacheKeys.For("Bancos", "BancoCuenta", "lookup");
}

public interface IGetBancoCuentaListUseCase
{
    Task<PagedResult<BancoCuentaDisplay>> ExecuteAsync(BancoCuentaFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetBancoCuentaListUseCase(IBancoCuentaRepository repository)
    : GetListUseCaseBase<Db.BancosCuentas, BancoCuentaFilter, BancoCuentaDisplay>(repository), IGetBancoCuentaListUseCase
{
    protected override BancoCuentaDisplay ToDisplay(Db.BancosCuentas entity) => entity.ToDisplay();
}

public interface IGetBancoCuentaByIdUseCase
{
    Task<BancoCuentaDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetBancoCuentaByIdUseCase(IBancoCuentaRepository repository)
    : GetByIdUseCaseBase<Db.BancosCuentas, int, BancoCuentaFilter, BancoCuentaDisplay>(repository), IGetBancoCuentaByIdUseCase
{
    protected override string EntityName => "BancoCuenta";

    protected override BancoCuentaDisplay ToDisplay(Db.BancosCuentas entity) => entity.ToDisplay();
}

public interface IGetBancoCuentaLookupUseCase
{
    Task<IReadOnlyList<BancoCuentaDisplay>> ExecuteAsync(CancellationToken cancellationToken = default);
}

public sealed partial class GetBancoCuentaLookupUseCase(IBancoCuentaRepository repository, IRedisCacheService cache)
    : GetLookupUseCaseBase<Db.BancosCuentas, int, BancoCuentaFilter, BancoCuentaDisplay>(repository, cache), IGetBancoCuentaLookupUseCase
{
    protected override string CacheKey => BancoCuentaCacheKeys.Lookup;

    protected override BancoCuentaDisplay ToDisplay(Db.BancosCuentas entity) => entity.ToDisplay();
}

public interface ICreateBancoCuentaUseCase
{
    Task<BancoCuentaDisplay> ExecuteAsync(BancoCuentaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateBancoCuentaUseCase(IBancoCuentaRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.BancosCuentas, int, BancoCuentaFilter, BancoCuentaDto, BancoCuentaDisplay>(repository, cache), ICreateBancoCuentaUseCase
{
    protected override string EntityName => "BancoCuenta";

    protected override string? CacheKey => BancoCuentaCacheKeys.Lookup;

    protected override Db.BancosCuentas ToEntity(BancoCuentaDto dto) => dto.ToEntity();

    protected override BancoCuentaDisplay ToDisplay(Db.BancosCuentas entity) => entity.ToDisplay();
}

public interface IUpdateBancoCuentaUseCase
{
    Task<BancoCuentaDisplay> ExecuteAsync(int id, BancoCuentaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateBancoCuentaUseCase(IBancoCuentaRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.BancosCuentas, int, BancoCuentaFilter, BancoCuentaDto, BancoCuentaDisplay>(repository, cache), IUpdateBancoCuentaUseCase
{
    protected override string EntityName => "BancoCuenta";

    protected override string? CacheKey => BancoCuentaCacheKeys.Lookup;

    protected override void Apply(BancoCuentaDto dto, Db.BancosCuentas entity) => dto.ApplyTo(entity);

    protected override BancoCuentaDisplay ToDisplay(Db.BancosCuentas entity) => entity.ToDisplay();
}
