// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Mappings.Bancos;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Bancos;

public static class BancoCacheKeys
{
    public static readonly string Lookup = CacheKeys.For("Bancos", "Banco", "lookup");
}

public interface IGetBancoListUseCase
{
    Task<PagedResult<BancoDisplay>> ExecuteAsync(BancoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetBancoListUseCase(IBancoRepository repository)
    : GetListUseCaseBase<Db.Bancos, BancoFilter, BancoDisplay>(repository), IGetBancoListUseCase
{
    protected override BancoDisplay ToDisplay(Db.Bancos entity) => entity.ToDisplay();
}

public interface IGetBancoByIdUseCase
{
    Task<BancoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetBancoByIdUseCase(IBancoRepository repository)
    : GetByIdUseCaseBase<Db.Bancos, int, BancoFilter, BancoDisplay>(repository), IGetBancoByIdUseCase
{
    protected override string EntityName => "Banco";

    protected override BancoDisplay ToDisplay(Db.Bancos entity) => entity.ToDisplay();
}

public interface IGetBancoLookupUseCase
{
    Task<IReadOnlyList<BancoDisplay>> ExecuteAsync(CancellationToken cancellationToken = default);
}

public sealed partial class GetBancoLookupUseCase(IBancoRepository repository, IRedisCacheService cache)
    : GetLookupUseCaseBase<Db.Bancos, int, BancoFilter, BancoDisplay>(repository, cache), IGetBancoLookupUseCase
{
    protected override string CacheKey => BancoCacheKeys.Lookup;

    protected override BancoDisplay ToDisplay(Db.Bancos entity) => entity.ToDisplay();
}

public interface ICreateBancoUseCase
{
    Task<BancoDisplay> ExecuteAsync(BancoDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateBancoUseCase(IBancoRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.Bancos, int, BancoFilter, BancoDto, BancoDisplay>(repository, cache), ICreateBancoUseCase
{
    protected override string EntityName => "Banco";

    protected override string? CacheKey => BancoCacheKeys.Lookup;

    protected override Db.Bancos ToEntity(BancoDto dto) => dto.ToEntity();

    protected override BancoDisplay ToDisplay(Db.Bancos entity) => entity.ToDisplay();
}

public interface IUpdateBancoUseCase
{
    Task<BancoDisplay> ExecuteAsync(int id, BancoDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateBancoUseCase(IBancoRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.Bancos, int, BancoFilter, BancoDto, BancoDisplay>(repository, cache), IUpdateBancoUseCase
{
    protected override string EntityName => "Banco";

    protected override string? CacheKey => BancoCacheKeys.Lookup;

    protected override void Apply(BancoDto dto, Db.Bancos entity) => dto.ApplyTo(entity);

    protected override BancoDisplay ToDisplay(Db.Bancos entity) => entity.ToDisplay();
}
