// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Mappings.Bancos;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Bancos;

public interface IGetConciliacionBancariaDetalleListUseCase
{
    Task<PagedResult<ConciliacionBancariaDetalleDisplay>> ExecuteAsync(ConciliacionBancariaDetalleFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetConciliacionBancariaDetalleListUseCase(IConciliacionBancariaDetalleRepository repository)
    : GetListUseCaseBase<Db.ConciliacionBancariaDetalle, ConciliacionBancariaDetalleFilter, ConciliacionBancariaDetalleDisplay>(repository), IGetConciliacionBancariaDetalleListUseCase
{
    protected override ConciliacionBancariaDetalleDisplay ToDisplay(Db.ConciliacionBancariaDetalle entity) => entity.ToDisplay();
}

public interface IGetConciliacionBancariaDetalleByIdUseCase
{
    Task<ConciliacionBancariaDetalleDisplay> ExecuteAsync(long id, CancellationToken cancellationToken = default);
}

public sealed partial class GetConciliacionBancariaDetalleByIdUseCase(IConciliacionBancariaDetalleRepository repository)
    : GetByIdUseCaseBase<Db.ConciliacionBancariaDetalle, long, ConciliacionBancariaDetalleFilter, ConciliacionBancariaDetalleDisplay>(repository), IGetConciliacionBancariaDetalleByIdUseCase
{
    protected override string EntityName => "ConciliacionBancariaDetalle";

    protected override ConciliacionBancariaDetalleDisplay ToDisplay(Db.ConciliacionBancariaDetalle entity) => entity.ToDisplay();
}
