// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Mappings.Bancos;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Bancos;

public interface IGetOrdenDepositoDetalleListUseCase
{
    Task<PagedResult<OrdenDepositoDetalleDisplay>> ExecuteAsync(OrdenDepositoDetalleFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetOrdenDepositoDetalleListUseCase(IOrdenDepositoDetalleRepository repository)
    : GetListUseCaseBase<Db.OrdenesDepositosDetalle, OrdenDepositoDetalleFilter, OrdenDepositoDetalleDisplay>(repository), IGetOrdenDepositoDetalleListUseCase
{
    protected override OrdenDepositoDetalleDisplay ToDisplay(Db.OrdenesDepositosDetalle entity) => entity.ToDisplay();
}

public interface IGetOrdenDepositoDetalleByIdUseCase
{
    Task<OrdenDepositoDetalleDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetOrdenDepositoDetalleByIdUseCase(IOrdenDepositoDetalleRepository repository)
    : GetByIdUseCaseBase<Db.OrdenesDepositosDetalle, int, OrdenDepositoDetalleFilter, OrdenDepositoDetalleDisplay>(repository), IGetOrdenDepositoDetalleByIdUseCase
{
    protected override string EntityName => "OrdenDepositoDetalle";

    protected override OrdenDepositoDetalleDisplay ToDisplay(Db.OrdenesDepositosDetalle entity) => entity.ToDisplay();
}
