// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Mappings.Bancos;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Bancos;

public interface IGetOrdenDepositoListUseCase
{
    Task<PagedResult<OrdenDepositoDisplay>> ExecuteAsync(OrdenDepositoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetOrdenDepositoListUseCase(IOrdenDepositoRepository repository)
    : GetListUseCaseBase<Db.OrdenesDepositos, OrdenDepositoFilter, OrdenDepositoDisplay>(repository), IGetOrdenDepositoListUseCase
{
    protected override OrdenDepositoDisplay ToDisplay(Db.OrdenesDepositos entity) => entity.ToDisplay();
}

public interface IGetOrdenDepositoByIdUseCase
{
    Task<OrdenDepositoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetOrdenDepositoByIdUseCase(IOrdenDepositoRepository repository)
    : GetByIdUseCaseBase<Db.OrdenesDepositos, int, OrdenDepositoFilter, OrdenDepositoDisplay>(repository), IGetOrdenDepositoByIdUseCase
{
    protected override string EntityName => "OrdenDeposito";

    protected override OrdenDepositoDisplay ToDisplay(Db.OrdenesDepositos entity) => entity.ToDisplay();
}
