// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Mappings.Bancos;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Bancos;

public interface IGetOrdenExtraccionListUseCase
{
    Task<PagedResult<OrdenExtraccionDisplay>> ExecuteAsync(OrdenExtraccionFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetOrdenExtraccionListUseCase(IOrdenExtraccionRepository repository)
    : GetListUseCaseBase<Db.OrdenesExrtacciones, OrdenExtraccionFilter, OrdenExtraccionDisplay>(repository), IGetOrdenExtraccionListUseCase
{
    protected override OrdenExtraccionDisplay ToDisplay(Db.OrdenesExrtacciones entity) => entity.ToDisplay();
}

public interface IGetOrdenExtraccionByIdUseCase
{
    Task<OrdenExtraccionDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetOrdenExtraccionByIdUseCase(IOrdenExtraccionRepository repository)
    : GetByIdUseCaseBase<Db.OrdenesExrtacciones, int, OrdenExtraccionFilter, OrdenExtraccionDisplay>(repository), IGetOrdenExtraccionByIdUseCase
{
    protected override string EntityName => "OrdenExtraccion";

    protected override OrdenExtraccionDisplay ToDisplay(Db.OrdenesExrtacciones entity) => entity.ToDisplay();
}
