// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Mappings.Bancos;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Bancos;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Bancos;

public static class TarjetaCacheKeys
{
    public static readonly string Lookup = CacheKeys.For("Bancos", "Tarjeta", "lookup");
}

public interface IGetTarjetaListUseCase
{
    Task<PagedResult<TarjetaDisplay>> ExecuteAsync(TarjetaFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetTarjetaListUseCase(ITarjetaRepository repository)
    : GetListUseCaseBase<Db.Tarjetas, TarjetaFilter, TarjetaDisplay>(repository), IGetTarjetaListUseCase
{
    protected override TarjetaDisplay ToDisplay(Db.Tarjetas entity) => entity.ToDisplay();
}

public interface IGetTarjetaByIdUseCase
{
    Task<TarjetaDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetTarjetaByIdUseCase(ITarjetaRepository repository)
    : GetByIdUseCaseBase<Db.Tarjetas, int, TarjetaFilter, TarjetaDisplay>(repository), IGetTarjetaByIdUseCase
{
    protected override string EntityName => "Tarjeta";

    protected override TarjetaDisplay ToDisplay(Db.Tarjetas entity) => entity.ToDisplay();
}

public interface IGetTarjetaLookupUseCase
{
    Task<IReadOnlyList<TarjetaDisplay>> ExecuteAsync(CancellationToken cancellationToken = default);
}

public sealed partial class GetTarjetaLookupUseCase(ITarjetaRepository repository, IRedisCacheService cache)
    : GetLookupUseCaseBase<Db.Tarjetas, int, TarjetaFilter, TarjetaDisplay>(repository, cache), IGetTarjetaLookupUseCase
{
    protected override string CacheKey => TarjetaCacheKeys.Lookup;

    protected override TarjetaDisplay ToDisplay(Db.Tarjetas entity) => entity.ToDisplay();
}

public interface ICreateTarjetaUseCase
{
    Task<TarjetaDisplay> ExecuteAsync(TarjetaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateTarjetaUseCase(ITarjetaRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.Tarjetas, int, TarjetaFilter, TarjetaDto, TarjetaDisplay>(repository, cache), ICreateTarjetaUseCase
{
    protected override string EntityName => "Tarjeta";

    protected override string? CacheKey => TarjetaCacheKeys.Lookup;

    protected override Db.Tarjetas ToEntity(TarjetaDto dto) => dto.ToEntity();

    protected override TarjetaDisplay ToDisplay(Db.Tarjetas entity) => entity.ToDisplay();
}

public interface IUpdateTarjetaUseCase
{
    Task<TarjetaDisplay> ExecuteAsync(int id, TarjetaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateTarjetaUseCase(ITarjetaRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.Tarjetas, int, TarjetaFilter, TarjetaDto, TarjetaDisplay>(repository, cache), IUpdateTarjetaUseCase
{
    protected override string EntityName => "Tarjeta";

    protected override string? CacheKey => TarjetaCacheKeys.Lookup;

    protected override void Apply(TarjetaDto dto, Db.Tarjetas entity) => dto.ApplyTo(entity);

    protected override TarjetaDisplay ToDisplay(Db.Tarjetas entity) => entity.ToDisplay();
}
