// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Proveedores;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Proveedores;

public static partial class EntidadOrdenPagoDocumentoProveedorMappings
{
    public static EntidadOrdenPagoDocumentoProveedorDisplay ToDisplay(this Db.EntidadOrdenPagoDocumentosProveedores entity) => new()
    {
        IdEntidadOrdenPagoDocumentoProveedor = entity.IdEntidadOrdenPagoDocumentoProveedor,
        IdEntidadOrdenPago = entity.IdEntidadOrdenPago,
        IdEntidad = entity.IdEntidad,
        NumeroOrdenPago = entity.NumeroOrdenPago,
        ImporteOrdenPago = entity.ImporteOrdenPago,
        IdDocumentoProveedor = entity.IdDocumentoProveedor,
        IdComprobanteTipo = entity.IdComprobanteTipo,
        NumeroComprobante = entity.NumeroComprobante,
        ImporteComprobante = entity.ImporteComprobante,
        Saldo = entity.Saldo,
    };
}
