// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Proveedores;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Proveedores;

public static partial class ProveedorReciboMappings
{
    public static ProveedorReciboDisplay ToDisplay(this Db.ProveedoresRecibos entity) => new()
    {
        IdProveedorRecibo = entity.IdProveedorRecibo,
        IdProveedor = entity.IdProveedor,
        Letra = entity.Letra,
        PuntoVenta = entity.PuntoVenta,
        Numero = entity.Numero,
        RazonSocial = entity.RazonSocial,
        IdCategoriaIva = entity.IdCategoriaIva,
        NroDoc = entity.NroDoc,
        FechaEmision = entity.FechaEmision,
        IdUsuario = entity.IdUsuario,
        IdEmpresa = entity.IdEmpresa,
        IdPlanillaCaja = entity.IdPlanillaCaja,
        Total = entity.Total,
        Estado = entity.Estado,
        IdOrdenPagoTipo = entity.IdOrdenPagoTipo,
        Observaciones = entity.Observaciones,
        IdSucursal = entity.IdSucursal,
    };
}
