// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Ventas;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Ventas;

public static partial class DocumentoClienteMappings
{
    public static DocumentoClienteDisplay ToDisplay(this Db.DocumentosCliente entity) => new()
    {
        IdDocumentoCliente = entity.IdDocumentoCliente,
        IdComprobanteTipo = entity.IdComprobanteTipo,
        IdCondicion = entity.IdCondicion,
        Letra = entity.Letra,
        IdPuntoVenta = entity.IdPuntoVenta,
        PuntoVenta = entity.PuntoVenta,
        Numero = entity.Numero,
        IdCliente = entity.IdCliente,
        RazonSocial = entity.RazonSocial,
        IdCategoriaIva = entity.IdCategoriaIva,
        NroDoc = entity.NroDoc,
        IdProvincia = entity.IdProvincia,
        IdLocalidad = entity.IdLocalidad,
        Calle = entity.Calle,
        Nro = entity.Nro,
        TotalNeto = entity.TotalNeto,
        TotalIva = entity.TotalIva,
        TotalOtrosImpuestos = entity.TotalOtrosImpuestos,
        TotalGeneral = entity.TotalGeneral,
        FechaEmision = entity.FechaEmision,
        IdUsuario = entity.IdUsuario,
        IdEmpresa = entity.IdEmpresa,
        IdPlanillaCaja = entity.IdPlanillaCaja,
        Estado = entity.Estado,
        Cae = entity.Cae,
        VtoCae = entity.VtoCae,
        IdTransporte = entity.IdTransporte,
        Transporte = entity.Transporte,
        IdUnidad = entity.IdUnidad,
        Unidad = entity.Unidad,
        IdChofer = entity.IdChofer,
        Chofer = entity.Chofer,
        IdRemito = entity.IdRemito,
        BarCode = entity.BarCode,
        Observaciones = entity.Observaciones,
        Porcentaje = entity.Porcentaje,
        TotalRecargo = entity.TotalRecargo,
        TotalDescuento = entity.TotalDescuento,
        IdSucursal = entity.IdSucursal,
        Remitar = entity.Remitar,
        Facturar = entity.Facturar,
        Pendiente = entity.Pendiente,
    };
}
