// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Ventas;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Ventas;

public static partial class DocumentoClienteOtroTributoMappings
{
    public static DocumentoClienteOtroTributoDisplay ToDisplay(this Db.DocumentosClientesOtrosTributos entity) => new()
    {
        IdDocumentoClienteOtroTributo = entity.IdDocumentoClienteOtroTributo,
        IdDocumentoCliente = entity.IdDocumentoCliente,
        IdComprobanteTipo = entity.IdComprobanteTipo,
        IdOtroTributo = entity.IdOtroTributo,
        Detalle = entity.Detalle,
        BaseImponible = entity.BaseImponible,
        Alicuota = entity.Alicuota,
        Total = entity.Total,
    };
}
