// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.CuentasCorrientes;

/// <summary>Salida de dbo.EntidadesCtaCte.</summary>
public sealed partial class EntidadCtaCteDisplay
{
    public long IdEntidadCtaCte { get; init; }
    public int? IdEntidad { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public int? IdComprobante { get; init; }
    public string? Concepto { get; init; }
    public int? NroCuota { get; init; }
    public decimal? Total { get; init; }
    public decimal? Saldo { get; init; }
    public bool? Cancelado { get; init; }
    public DateTime? Fecha { get; init; }
    public DateTime? FechaVencimiento { get; init; }
    public DateTime? FechaAnulacion { get; init; }
    public DateTime? FechaPago { get; init; }
    public decimal? InteresAplicado { get; init; }
    public int? Estado { get; init; }
    public decimal? Total2 { get; init; }
    public int? IdEmpresa { get; init; }
    public int? IdSucursal { get; init; }
    public int? IdUsuario { get; init; }
}

/// <summary>Filtros del listado de dbo.EntidadesCtaCte.</summary>
public sealed partial class EntidadCtaCteFilter : PagedQuery
{
    public int? IdEntidad { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdComprobante { get; set; }

    public int? IdEmpresa { get; set; }

    public int? IdSucursal { get; set; }

    public int? IdUsuario { get; set; }

    public int? Estado { get; set; }

    /// <summary>Fecha desde (inclusive).</summary>
    public DateTime? FechaDesde { get; set; }

    /// <summary>Fecha hasta (inclusive, día completo).</summary>
    public DateTime? FechaHasta { get; set; }
}
