// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.CuentasCorrientes;

/// <summary>Salida de dbo.EntidadesCtaCteMovimientos.</summary>
public sealed partial class EntidadCtaCteMovimientoDisplay
{
    public long IdEntidadCtaCteMovimiento { get; init; }
    public long? IdEntidadCtaCte { get; init; }
    public string? Concepto { get; init; }
    public decimal? AfavorEntidad { get; init; }
    public decimal? EnContraEntidad { get; init; }
    public DateTime? Fecha { get; init; }
    public int? IdElementoCobroPago { get; init; }
    public int? IdElemento { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public int? IdComprobante { get; init; }
}

/// <summary>Filtros del listado de dbo.EntidadesCtaCteMovimientos.</summary>
public sealed partial class EntidadCtaCteMovimientoFilter : PagedQuery
{
    public long? IdEntidadCtaCte { get; set; }

    public int? IdElementoCobroPago { get; set; }

    public int? IdElemento { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdComprobante { get; set; }

    /// <summary>Fecha desde (inclusive).</summary>
    public DateTime? FechaDesde { get; set; }

    /// <summary>Fecha hasta (inclusive, día completo).</summary>
    public DateTime? FechaHasta { get; set; }
}
