// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Proveedores;

/// <summary>Salida de dbo.EntidadOrdenPagoDocumentosProveedores.</summary>
public sealed partial class EntidadOrdenPagoDocumentoProveedorDisplay
{
    public int IdEntidadOrdenPagoDocumentoProveedor { get; init; }
    public int? IdEntidadOrdenPago { get; init; }
    public int? IdEntidad { get; init; }
    public string? NumeroOrdenPago { get; init; }
    public decimal? ImporteOrdenPago { get; init; }
    public int? IdDocumentoProveedor { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public string? NumeroComprobante { get; init; }
    public decimal? ImporteComprobante { get; init; }
    public decimal? Saldo { get; init; }
}

/// <summary>Filtros del listado de dbo.EntidadOrdenPagoDocumentosProveedores.</summary>
public sealed partial class EntidadOrdenPagoDocumentoProveedorFilter : PagedQuery
{
    public int? IdEntidadOrdenPago { get; set; }

    public int? IdEntidad { get; set; }

    public int? IdDocumentoProveedor { get; set; }

    public int? IdComprobanteTipo { get; set; }
}
