// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Proveedores;

/// <summary>Salida de dbo.ProveedoresRecibosDetalle.</summary>
public sealed partial class ProveedorReciboDetalleDisplay
{
    public int IdProveedorReciboDetalle { get; init; }
    public int? IdProveedorRecibo { get; init; }
    public int? IdElementoCobroPago { get; init; }
    public string? Descripcion { get; init; }
    public string? Detalle { get; init; }
    public int? IdBanco { get; init; }
    public int? IdSucursal { get; init; }
    public string? Banco { get; init; }
    public string? Sucursal { get; init; }
    public DateTime? Recepcion { get; init; }
    public DateTime? Emision { get; init; }
    public DateTime? Vto { get; init; }
    public string? Nro { get; init; }
    public int? IdElemento { get; init; }
    public decimal? Total { get; init; }
}

/// <summary>Filtros del listado de dbo.ProveedoresRecibosDetalle.</summary>
public sealed partial class ProveedorReciboDetalleFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion, Detalle.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdProveedorRecibo { get; set; }

    public int? IdElementoCobroPago { get; set; }

    public int? IdBanco { get; set; }

    public int? IdSucursal { get; set; }

    public int? IdElemento { get; set; }
}
