// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Bancos;

/// <summary>Salida de dbo.Bancos.</summary>
public sealed partial class BancoDisplay
{
    public int IdBanco { get; init; }
    public string? RazonSocial { get; init; }
    public int? IdEstado { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.Bancos.</summary>
public sealed partial class BancoDto
{
    [MaxLength(500)]
    public string? RazonSocial { get; set; }

    public int? IdEstado { get; set; }
}

/// <summary>Filtros del listado de dbo.Bancos.</summary>
public sealed partial class BancoFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en RazonSocial.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdEstado { get; set; }
}
