// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Bancos;

/// <summary>Salida de dbo.BancosSucursales.</summary>
public sealed partial class BancoSucursalDisplay
{
    public int IdBancoSucursal { get; init; }
    public int? IdBanco { get; init; }
    public string? Descripcion { get; init; }
    public int? IdEstado { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.BancosSucursales.</summary>
public sealed partial class BancoSucursalDto
{
    public int? IdBanco { get; set; }

    [MaxLength(500)]
    public string? Descripcion { get; set; }

    public int? IdEstado { get; set; }
}

/// <summary>Filtros del listado de dbo.BancosSucursales.</summary>
public sealed partial class BancoSucursalFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdBanco { get; set; }

    public int? IdEstado { get; set; }
}
