// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Bancos;

/// <summary>Salida de dbo.BancosCuentas.</summary>
public sealed partial class BancoCuentaDisplay
{
    public int IdBancoCuenta { get; init; }
    public int? IdBanco { get; init; }
    public int? IdBancoSucursal { get; init; }
    public int? IdCuentaTipo { get; init; }
    public string? NroCuenta { get; init; }
    public int? Estado { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.BancosCuentas.</summary>
public sealed partial class BancoCuentaDto
{
    public int? IdBanco { get; set; }

    public int? IdBancoSucursal { get; set; }

    public int? IdCuentaTipo { get; set; }

    [MaxLength(50)]
    public string? NroCuenta { get; set; }

    public int? Estado { get; set; }
}

/// <summary>Filtros del listado de dbo.BancosCuentas.</summary>
public sealed partial class BancoCuentaFilter : PagedQuery
{
    public int? IdBanco { get; set; }

    public int? IdBancoSucursal { get; set; }

    public int? IdCuentaTipo { get; set; }

    public int? Estado { get; set; }
}
