// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Bancos;

/// <summary>Salida de dbo.BancosChequeras.</summary>
public sealed partial class BancoChequeraDisplay
{
    public int IdBancosChequeras { get; init; }
    public int? IdBancoCuenta { get; init; }
    public decimal? Cantidad { get; init; }
    public long? Desde { get; init; }
    public long? Hasta { get; init; }
    public int? Estado { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.BancosChequeras.</summary>
public sealed partial class BancoChequeraDto
{
    public int? IdBancoCuenta { get; set; }

    public decimal? Cantidad { get; set; }

    public long? Desde { get; set; }

    public long? Hasta { get; set; }

    public int? Estado { get; set; }
}

/// <summary>Filtros del listado de dbo.BancosChequeras.</summary>
public sealed partial class BancoChequeraFilter : PagedQuery
{
    public int? IdBancoCuenta { get; set; }

    public int? Estado { get; set; }
}
