// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Bancos;

/// <summary>Salida de dbo.ConciliacionBancaria.</summary>
public sealed partial class ConciliacionBancariaDisplay
{
    public int IdConciliacionBancaria { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public string? Letra { get; init; }
    public int? IdPuntoVenta { get; init; }
    public string? PuntoVenta { get; init; }
    public string? Numero { get; init; }
    public int? IdBancoCuenta { get; init; }
    public string? Cuenta { get; init; }
    public int? IdTipo { get; init; }
    public int? IdBanco { get; init; }
    public int? IdSucursal { get; init; }
    public decimal? TotalGeneral { get; init; }
    public DateTime? FechaEmision { get; init; }
    public int? IdUsuario { get; init; }
    public int? IdEmpresa { get; init; }
    public int? IdPlanillaCaja { get; init; }
    public int? Estado { get; init; }
    public int? IdTipoAjuste { get; init; }
}

/// <summary>Filtros del listado de dbo.ConciliacionBancaria.</summary>
public sealed partial class ConciliacionBancariaFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Numero.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdPuntoVenta { get; set; }

    public int? IdBancoCuenta { get; set; }

    public int? IdTipo { get; set; }

    public int? IdBanco { get; set; }

    public int? IdSucursal { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdEmpresa { get; set; }

    public int? IdPlanillaCaja { get; set; }

    public int? IdTipoAjuste { get; set; }

    public int? Estado { get; set; }

    /// <summary>FechaEmision desde (inclusive).</summary>
    public DateTime? FechaEmisionDesde { get; set; }

    /// <summary>FechaEmision hasta (inclusive, día completo).</summary>
    public DateTime? FechaEmisionHasta { get; set; }
}
