// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Empresas;
using API.SERVICE.Models.Empresas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Empresas;

public sealed partial class DatosEmpresaRepository : EfRepository<Db.DatosEmpresa, int, DatosEmpresaFilter>, IDatosEmpresaRepository
{
    public DatosEmpresaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.DatosEmpresa> ApplyFilter(IQueryable<Db.DatosEmpresa> query, DatosEmpresaFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => x.RazonSocial.Contains(q)
                || x.NombreFantasia.Contains(q)
                || x.Email.Contains(q));
        }

        if (filter.IdProvincia is not null)
            query = query.Where(x => x.IdProvincia == filter.IdProvincia.Value);

        if (filter.IdLocalidad is not null)
            query = query.Where(x => x.IdLocalidad == filter.IdLocalidad.Value);

        if (filter.FechaInicioDesde is not null)
            query = query.Where(x => x.FechaInicio >= filter.FechaInicioDesde.Value);

        if (filter.FechaInicioHasta is not null)
        {
            query = query.Where(x => x.FechaInicio <= filter.FechaInicioHasta.Value);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.DatosEmpresa> ApplyDefaultOrder(IQueryable<Db.DatosEmpresa> query) =>
        query.OrderByDescending(x => x.IdDatosEmpresa);
}
