// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Empresas;
using API.SERVICE.Models.Empresas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Empresas;

public sealed partial class EmpresaRepository : EfRepository<Db.Empresas, int, EmpresaFilter>, IEmpresaRepository
{
    public EmpresaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Empresas> ApplyFilter(IQueryable<Db.Empresas> query, EmpresaFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.RazonSocial != null && x.RazonSocial.Contains(q))
                || (x.Email != null && x.Email.Contains(q)));
        }

        if (filter.IdCategoriaIva is not null)
            query = query.Where(x => x.IdCategoriaIva == filter.IdCategoriaIva);

        if (filter.IdProvincia is not null)
            query = query.Where(x => x.IdProvincia == filter.IdProvincia);

        if (filter.IdLocalidad is not null)
            query = query.Where(x => x.IdLocalidad == filter.IdLocalidad);

        if (filter.IdEmpresaTipo is not null)
            query = query.Where(x => x.IdEmpresaTipo == filter.IdEmpresaTipo);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        if (filter.FechaAltaDesde is not null)
            query = query.Where(x => x.FechaAlta >= filter.FechaAltaDesde.Value);

        if (filter.FechaAltaHasta is not null)
        {
            var hasta = filter.FechaAltaHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaAlta < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.Empresas> ApplyDefaultOrder(IQueryable<Db.Empresas> query) =>
        query.OrderByDescending(x => x.IdEmpresa);
}
