// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Transportes;
using API.SERVICE.Models.Transportes;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Transportes;

public sealed partial class VehiculoRepository : EfRepository<Db.Vehiculos, int, VehiculoFilter>, IVehiculoRepository
{
    public VehiculoRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Vehiculos> ApplyFilter(IQueryable<Db.Vehiculos> query, VehiculoFilter filter)
    {
        if (filter.IdVehiculoTipo is not null)
            query = query.Where(x => x.IdVehiculoTipo == filter.IdVehiculoTipo);

        if (filter.IdTransporte is not null)
            query = query.Where(x => x.IdTransporte == filter.IdTransporte);

        if (filter.IdVehiculoPadre is not null)
            query = query.Where(x => x.IdVehiculoPadre == filter.IdVehiculoPadre);

        if (filter.IdSujeto is not null)
            query = query.Where(x => x.IdSujeto == filter.IdSujeto.Value);

        if (filter.IdCentro is not null)
            query = query.Where(x => x.IdCentro == filter.IdCentro);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        if (filter.FechaAltaDesde is not null)
            query = query.Where(x => x.FechaAlta >= filter.FechaAltaDesde.Value);

        if (filter.FechaAltaHasta is not null)
        {
            var hasta = filter.FechaAltaHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaAlta < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.Vehiculos> ApplyDefaultOrder(IQueryable<Db.Vehiculos> query) =>
        query.OrderByDescending(x => x.IdVehiculo);
}
