// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Common;
using API.SERVICE.Models.Miscelaneas;
using API.SERVICE.UseCases.Miscelaneas;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers.Miscelaneas;

/// <summary>dbo.Estados.</summary>
[ApiController]
[Authorize]
[Route("api/[controller]")]
[Tags("Miscelaneas")]
[Produces("application/json")]
[ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status401Unauthorized)]
public sealed partial class EstadoController : ControllerBase
{
    /// <summary>Listado paginado y filtrado.</summary>
    [HttpGet]
    [ProducesResponseType(typeof(PagedResult<EstadoDisplay>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<PagedResult<EstadoDisplay>>> GetList([FromQuery] EstadoFilter filter, [FromServices] IGetEstadoListUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(filter, cancellationToken));

    /// <summary>Catálogo completo para combos (cacheado).</summary>
    [HttpGet("lookup")]
    [ProducesResponseType(typeof(IReadOnlyList<EstadoDisplay>), StatusCodes.Status200OK)]
    public async Task<ActionResult<IReadOnlyList<EstadoDisplay>>> GetLookup([FromServices] IGetEstadoLookupUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(cancellationToken));

    /// <summary>Detalle por Id.</summary>
    [HttpGet("{id:int}")]
    [ProducesResponseType(typeof(EstadoDisplay), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<EstadoDisplay>> GetById(int id, [FromServices] IGetEstadoByIdUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(id, cancellationToken));

    /// <summary>Alta.</summary>
    [HttpPost]
    [ProducesResponseType(typeof(EstadoDisplay), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status409Conflict)]
    public async Task<ActionResult<EstadoDisplay>> Create([FromBody] EstadoDto dto, [FromServices] ICreateEstadoUseCase useCase, CancellationToken cancellationToken)
    {
        var created = await useCase.ExecuteAsync(dto, cancellationToken);
        return CreatedAtAction(nameof(GetById), new { id = created.IdEstado }, created);
    }

    /// <summary>Modificación.</summary>
    [HttpPut("{id:int}")]
    [ProducesResponseType(typeof(EstadoDisplay), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ErrorCatchResponse), StatusCodes.Status409Conflict)]
    public async Task<ActionResult<EstadoDisplay>> Update(int id, [FromBody] EstadoDto dto, [FromServices] IUpdateEstadoUseCase useCase, CancellationToken cancellationToken) =>
        Ok(await useCase.ExecuteAsync(id, dto, cancellationToken));
}
