// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Comprobantes;

/// <summary>Salida de dbo.ComprobantesLetras.</summary>
public sealed partial class ComprobanteLetraDisplay
{
    public int IdComprobanteLetra { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public int? IdCategoriaIvacliente { get; init; }
    public int? IdCategoriaIvaproveedor { get; init; }
    public string? Letra { get; init; }
    public int? IdEmpresa { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.ComprobantesLetras.</summary>
public sealed partial class ComprobanteLetraDto
{
    public int? IdComprobanteTipo { get; set; }

    public int? IdCategoriaIvacliente { get; set; }

    public int? IdCategoriaIvaproveedor { get; set; }

    [MaxLength(50)]
    public string? Letra { get; set; }

    public int? IdEmpresa { get; set; }
}

/// <summary>Filtros del listado de dbo.ComprobantesLetras.</summary>
public sealed partial class ComprobanteLetraFilter : PagedQuery
{
    public int? IdComprobanteTipo { get; set; }

    public int? IdCategoriaIvacliente { get; set; }

    public int? IdCategoriaIvaproveedor { get; set; }

    public int? IdEmpresa { get; set; }
}
