// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Comprobantes;

/// <summary>Salida de dbo.ComprobantesCarga.</summary>
public sealed partial class ComprobanteCargaDisplay
{
    public int IdComprobanteCarga { get; init; }
    public int? IdComprobante { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public DateTime? FechaCarga { get; init; }
    public int? IdUsuario { get; init; }
}

/// <summary>Filtros del listado de dbo.ComprobantesCarga.</summary>
public sealed partial class ComprobanteCargaFilter : PagedQuery
{
    public int? IdComprobante { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdUsuario { get; set; }

    /// <summary>FechaCarga desde (inclusive).</summary>
    public DateTime? FechaCargaDesde { get; set; }

    /// <summary>FechaCarga hasta (inclusive, día completo).</summary>
    public DateTime? FechaCargaHasta { get; set; }
}
