// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Comprobantes;

/// <summary>Salida de dbo.ElementosCobroPago.</summary>
public sealed partial class ElementoCobroPagoDisplay
{
    public int IdElementroCobroPago { get; init; }
    public int? IdTipo { get; init; }
    public string? Descripcion { get; init; }
    public string? Reducida { get; init; }
    public bool? HabilitaMoneda { get; init; }
    public int? IdEmpresa { get; init; }
    public int? CuentaDebe { get; init; }
    public int? CuentaHaber { get; init; }
    public int? Estado { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.ElementosCobroPago.</summary>
public sealed partial class ElementoCobroPagoDto
{
    public int? IdTipo { get; set; }

    [MaxLength(50)]
    public string? Descripcion { get; set; }

    [MaxLength(50)]
    public string? Reducida { get; set; }

    public bool? HabilitaMoneda { get; set; }

    public int? IdEmpresa { get; set; }

    public int? CuentaDebe { get; set; }

    public int? CuentaHaber { get; set; }

    public int? Estado { get; set; }
}

/// <summary>Filtros del listado de dbo.ElementosCobroPago.</summary>
public sealed partial class ElementoCobroPagoFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdTipo { get; set; }

    public int? IdEmpresa { get; set; }

    public int? Estado { get; set; }
}
