// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Comprobantes;

/// <summary>Salida de dbo.PuntosVenta.</summary>
public sealed partial class PuntoVentaDisplay
{
    public int IdPuntoVenta { get; init; }
    public string? Descripcion { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public string? Letra { get; init; }
    public long? Nro { get; init; }
    public int? IdEmpresa { get; init; }
    public int? Estado { get; init; }
    public int? IdUsuario { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.PuntosVenta.</summary>
public sealed partial class PuntoVentaDto
{
    [MaxLength(50)]
    public string? Descripcion { get; set; }

    public int? IdComprobanteTipo { get; set; }

    [MaxLength(50)]
    public string? Letra { get; set; }

    public long? Nro { get; set; }

    public int? IdEmpresa { get; set; }

    public int? Estado { get; set; }

    public int? IdUsuario { get; set; }
}

/// <summary>Filtros del listado de dbo.PuntosVenta.</summary>
public sealed partial class PuntoVentaFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdEmpresa { get; set; }

    public int? IdUsuario { get; set; }

    public int? Estado { get; set; }
}
