// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Ventas;

/// <summary>Salida de dbo.DocumentosClienteRemitos.</summary>
public sealed partial class DocumentoClienteRemitoDisplay
{
    public int IdDocumentoClienteRemito { get; init; }
    public int? IdDocumentoCliente { get; init; }
    public int? IdRemito { get; init; }
    public int? IdComprobanteTipo { get; init; }
}

/// <summary>Filtros del listado de dbo.DocumentosClienteRemitos.</summary>
public sealed partial class DocumentoClienteRemitoFilter : PagedQuery
{
    public int? IdDocumentoCliente { get; set; }

    public int? IdRemito { get; set; }

    public int? IdComprobanteTipo { get; set; }
}
