// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Ventas;

/// <summary>Salida de dbo.DocumentosClienteVencimientos.</summary>
public sealed partial class DocumentoClienteVencimientoDisplay
{
    public int IdDocumentoClienteVencimiento { get; init; }
    public int? IdDocumentoCliente { get; init; }
    public DateTime? FechaVencimiento { get; init; }
}

/// <summary>Filtros del listado de dbo.DocumentosClienteVencimientos.</summary>
public sealed partial class DocumentoClienteVencimientoFilter : PagedQuery
{
    public int? IdDocumentoCliente { get; set; }

    /// <summary>FechaVencimiento desde (inclusive).</summary>
    public DateTime? FechaVencimientoDesde { get; set; }

    /// <summary>FechaVencimiento hasta (inclusive, día completo).</summary>
    public DateTime? FechaVencimientoHasta { get; set; }
}
