// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Ventas;

/// <summary>Salida de dbo.DocumentosClienteRelacion.</summary>
public sealed partial class DocumentoClienteRelacionDisplay
{
    public int IdDocumentoClienteRelacion { get; init; }
    public int? IdDocumentoCliente1 { get; init; }
    public int? IdDocumentoCliente2 { get; init; }
}

/// <summary>Filtros del listado de dbo.DocumentosClienteRelacion.</summary>
public sealed partial class DocumentoClienteRelacionFilter : PagedQuery
{
    public int? IdDocumentoCliente1 { get; set; }

    public int? IdDocumentoCliente2 { get; set; }
}
