// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Ventas;

/// <summary>Salida de dbo.DocumentosClienteObservaciones.</summary>
public sealed partial class DocumentoClienteObservacionDisplay
{
    public int IdDocumentoClienteObservacion { get; init; }
    public int? IdDocumentoCliente { get; init; }
    public string? Observaciones { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.DocumentosClienteObservaciones.</summary>
public sealed partial class DocumentoClienteObservacionDto
{
    public int? IdDocumentoCliente { get; set; }

    public string? Observaciones { get; set; }
}

/// <summary>Filtros del listado de dbo.DocumentosClienteObservaciones.</summary>
public sealed partial class DocumentoClienteObservacionFilter : PagedQuery
{
    public int? IdDocumentoCliente { get; set; }
}
