// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Ventas;

/// <summary>Salida de dbo.DocumentosClientesOtrosTributos.</summary>
public sealed partial class DocumentoClienteOtroTributoDisplay
{
    public int IdDocumentoClienteOtroTributo { get; init; }
    public int? IdDocumentoCliente { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public int? IdOtroTributo { get; init; }
    public string? Detalle { get; init; }
    public decimal? BaseImponible { get; init; }
    public decimal? Alicuota { get; init; }
    public decimal? Total { get; init; }
}

/// <summary>Filtros del listado de dbo.DocumentosClientesOtrosTributos.</summary>
public sealed partial class DocumentoClienteOtroTributoFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Detalle.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdDocumentoCliente { get; set; }

    public int? IdComprobanteTipo { get; set; }

    public int? IdOtroTributo { get; set; }
}
