// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Ventas;

/// <summary>Salida de dbo.DocumentosClienteRemitosDetalle.</summary>
public sealed partial class DocumentoClienteRemitoDetalleDisplay
{
    public int IdDocumentoClienteRemitoDetalle { get; init; }
    public int? IdDocumentoClienteRemito { get; init; }
    public int? IdItem { get; init; }
    public decimal? CantidadFactura { get; init; }
    public decimal? CantidadRemito { get; init; }
    public decimal? Saldo { get; init; }
    public int? IdDocumentoCliente { get; init; }
    public int? IdRemito { get; init; }
}

/// <summary>Filtros del listado de dbo.DocumentosClienteRemitosDetalle.</summary>
public sealed partial class DocumentoClienteRemitoDetalleFilter : PagedQuery
{
    public int? IdDocumentoClienteRemito { get; set; }

    public int? IdItem { get; set; }

    public int? IdDocumentoCliente { get; set; }

    public int? IdRemito { get; set; }
}
