// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Transportes;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Transportes;

/// <summary>Persistencia de dbo.Vehiculos.</summary>
public partial interface IVehiculoRepository : global::API.SERVICE.Interfaces.IRepository<Db.Vehiculos, int, VehiculoFilter>
{
}
