// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Clientes;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Clientes;

public static partial class EntidadReciboDocumentoClienteMappings
{
    public static EntidadReciboDocumentoClienteDisplay ToDisplay(this Db.EntidadRecibosDocumentosCliente entity) => new()
    {
        IdEntidadReciboDocumentoCliente = entity.IdEntidadReciboDocumentoCliente,
        IdEntidadRecibo = entity.IdEntidadRecibo,
        IdEntidad = entity.IdEntidad,
        NumeroRecibo = entity.NumeroRecibo,
        ImporteRecibo = entity.ImporteRecibo,
        IdDocumentoCliente = entity.IdDocumentoCliente,
        IdComprobanteTipo = entity.IdComprobanteTipo,
        NumeroComprobante = entity.NumeroComprobante,
        ImporteComprobante = entity.ImporteComprobante,
        Saldo = entity.Saldo,
    };
}
