// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Empresas;

/// <summary>Salida de dbo.DatosEmpresa.</summary>
public sealed partial class DatosEmpresaDisplay
{
    public int IdDatosEmpresa { get; init; }
    public string RazonSocial { get; init; } = string.Empty;
    public string NombreFantasia { get; init; } = string.Empty;
    public string CuitEmpresa { get; init; } = string.Empty;
    public int CondicionIva { get; init; }
    public DateOnly FechaInicio { get; init; }
    public string DireccionComercial { get; init; } = string.Empty;
    public int IdProvincia { get; init; }
    public int IdLocalidad { get; init; }
    public string Telefono { get; init; } = string.Empty;
    public string Email { get; init; } = string.Empty;
    public string CuitPersona { get; init; } = string.Empty;
    public string Logo { get; init; } = string.Empty;
}

/// <summary>Entrada de alta/modificación de dbo.DatosEmpresa.</summary>
public sealed partial class DatosEmpresaDto
{
    [Required(AllowEmptyStrings = true), MaxLength(50)]
    public string? RazonSocial { get; set; }

    [Required(AllowEmptyStrings = true), MaxLength(50)]
    public string? NombreFantasia { get; set; }

    [Required(AllowEmptyStrings = true), MaxLength(50)]
    public string? CuitEmpresa { get; set; }

    [Required]
    public int? CondicionIva { get; set; }

    [Required]
    public DateOnly? FechaInicio { get; set; }

    [Required(AllowEmptyStrings = true), MaxLength(50)]
    public string? DireccionComercial { get; set; }

    [Required]
    public int? IdProvincia { get; set; }

    [Required]
    public int? IdLocalidad { get; set; }

    [Required(AllowEmptyStrings = true), MaxLength(50)]
    public string? Telefono { get; set; }

    [Required(AllowEmptyStrings = true), MaxLength(50)]
    public string? Email { get; set; }

    [Required(AllowEmptyStrings = true), MaxLength(50)]
    public string? CuitPersona { get; set; }

    [Required(AllowEmptyStrings = true)]
    public string? Logo { get; set; }
}

/// <summary>Filtros del listado de dbo.DatosEmpresa.</summary>
public sealed partial class DatosEmpresaFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en RazonSocial, NombreFantasia, Email.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdProvincia { get; set; }

    public int? IdLocalidad { get; set; }

    /// <summary>FechaInicio desde (inclusive).</summary>
    public DateOnly? FechaInicioDesde { get; set; }

    /// <summary>FechaInicio hasta (inclusive, día completo).</summary>
    public DateOnly? FechaInicioHasta { get; set; }
}
