// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Empresas;

/// <summary>Salida de dbo.Empresas.</summary>
public sealed partial class EmpresaDisplay
{
    public int IdEmpresa { get; init; }
    public string? RazonSocial { get; init; }
    public string? Fantasia { get; init; }
    public int? IdCategoriaIva { get; init; }
    public string? NroCuit { get; init; }
    public int? IdProvincia { get; init; }
    public int? IdLocalidad { get; init; }
    public string? Calle { get; init; }
    public string? Nro { get; init; }
    public DateTime? FechaAlta { get; init; }
    public bool? Admin { get; init; }
    public string? Imagen { get; init; }
    public int? IdEmpresaTipo { get; init; }
    public string? Email { get; init; }
    public string? Telefono { get; init; }
    public int? Estado { get; init; }
    public string? Iibb { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.Empresas.</summary>
public sealed partial class EmpresaDto
{
    [MaxLength(50)]
    public string? RazonSocial { get; set; }

    [MaxLength(50)]
    public string? Fantasia { get; set; }

    public int? IdCategoriaIva { get; set; }

    [MaxLength(50)]
    public string? NroCuit { get; set; }

    public int? IdProvincia { get; set; }

    public int? IdLocalidad { get; set; }

    [MaxLength(50)]
    public string? Calle { get; set; }

    [MaxLength(50)]
    public string? Nro { get; set; }

    public DateTime? FechaAlta { get; set; }

    public bool? Admin { get; set; }

    [MaxLength(50)]
    public string? Imagen { get; set; }

    public int? IdEmpresaTipo { get; set; }

    [MaxLength(50)]
    public string? Email { get; set; }

    [MaxLength(50)]
    public string? Telefono { get; set; }

    public int? Estado { get; set; }

    [MaxLength(50)]
    public string? Iibb { get; set; }
}

/// <summary>Filtros del listado de dbo.Empresas.</summary>
public sealed partial class EmpresaFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en RazonSocial, Email.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdCategoriaIva { get; set; }

    public int? IdProvincia { get; set; }

    public int? IdLocalidad { get; set; }

    public int? IdEmpresaTipo { get; set; }

    public int? Estado { get; set; }

    /// <summary>FechaAlta desde (inclusive).</summary>
    public DateTime? FechaAltaDesde { get; set; }

    /// <summary>FechaAlta hasta (inclusive, día completo).</summary>
    public DateTime? FechaAltaHasta { get; set; }
}
