// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Comprobantes;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Comprobantes;

public static partial class PuntoVentaMappings
{
    public static PuntoVentaDisplay ToDisplay(this Db.PuntosVenta entity) => new()
    {
        IdPuntoVenta = entity.IdPuntoVenta,
        Descripcion = entity.Descripcion,
        IdComprobanteTipo = entity.IdComprobanteTipo,
        Letra = entity.Letra,
        Nro = entity.Nro,
        IdEmpresa = entity.IdEmpresa,
        Estado = entity.Estado,
        IdUsuario = entity.IdUsuario,
    };

    public static Db.PuntosVenta ToEntity(this PuntoVentaDto dto)
    {
        var entity = new Db.PuntosVenta();
        dto.ApplyTo(entity);
        return entity;
    }

    /// <summary>Copia el Dto sobre la entidad (no toca la clave).</summary>
    public static void ApplyTo(this PuntoVentaDto dto, Db.PuntosVenta entity)
    {
        entity.Descripcion = dto.Descripcion;
        entity.IdComprobanteTipo = dto.IdComprobanteTipo;
        entity.Letra = dto.Letra;
        entity.Nro = dto.Nro;
        entity.IdEmpresa = dto.IdEmpresa;
        entity.Estado = dto.Estado;
        entity.IdUsuario = dto.IdUsuario;
    }
}
