// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Miscelaneas;
using API.SERVICE.Mappings.Miscelaneas;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Miscelaneas;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Miscelaneas;

public static class AreaDeContactoCacheKeys
{
    public static readonly string Lookup = CacheKeys.For("Miscelaneas", "AreaDeContacto", "lookup");
}

public interface IGetAreaDeContactoListUseCase
{
    Task<PagedResult<AreaDeContactoDisplay>> ExecuteAsync(AreaDeContactoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetAreaDeContactoListUseCase(IAreaDeContactoRepository repository)
    : GetListUseCaseBase<Db.AreasDeContacto, AreaDeContactoFilter, AreaDeContactoDisplay>(repository), IGetAreaDeContactoListUseCase
{
    protected override AreaDeContactoDisplay ToDisplay(Db.AreasDeContacto entity) => entity.ToDisplay();
}

public interface IGetAreaDeContactoByIdUseCase
{
    Task<AreaDeContactoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetAreaDeContactoByIdUseCase(IAreaDeContactoRepository repository)
    : GetByIdUseCaseBase<Db.AreasDeContacto, int, AreaDeContactoFilter, AreaDeContactoDisplay>(repository), IGetAreaDeContactoByIdUseCase
{
    protected override string EntityName => "AreaDeContacto";

    protected override AreaDeContactoDisplay ToDisplay(Db.AreasDeContacto entity) => entity.ToDisplay();
}

public interface IGetAreaDeContactoLookupUseCase
{
    Task<IReadOnlyList<AreaDeContactoDisplay>> ExecuteAsync(CancellationToken cancellationToken = default);
}

public sealed partial class GetAreaDeContactoLookupUseCase(IAreaDeContactoRepository repository, IRedisCacheService cache)
    : GetLookupUseCaseBase<Db.AreasDeContacto, int, AreaDeContactoFilter, AreaDeContactoDisplay>(repository, cache), IGetAreaDeContactoLookupUseCase
{
    protected override string CacheKey => AreaDeContactoCacheKeys.Lookup;

    protected override AreaDeContactoDisplay ToDisplay(Db.AreasDeContacto entity) => entity.ToDisplay();
}

public interface ICreateAreaDeContactoUseCase
{
    Task<AreaDeContactoDisplay> ExecuteAsync(AreaDeContactoDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateAreaDeContactoUseCase(IAreaDeContactoRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.AreasDeContacto, int, AreaDeContactoFilter, AreaDeContactoDto, AreaDeContactoDisplay>(repository, cache), ICreateAreaDeContactoUseCase
{
    protected override string EntityName => "AreaDeContacto";

    protected override string? CacheKey => AreaDeContactoCacheKeys.Lookup;

    protected override Db.AreasDeContacto ToEntity(AreaDeContactoDto dto) => dto.ToEntity();

    protected override AreaDeContactoDisplay ToDisplay(Db.AreasDeContacto entity) => entity.ToDisplay();
}

public interface IUpdateAreaDeContactoUseCase
{
    Task<AreaDeContactoDisplay> ExecuteAsync(int id, AreaDeContactoDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateAreaDeContactoUseCase(IAreaDeContactoRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.AreasDeContacto, int, AreaDeContactoFilter, AreaDeContactoDto, AreaDeContactoDisplay>(repository, cache), IUpdateAreaDeContactoUseCase
{
    protected override string EntityName => "AreaDeContacto";

    protected override string? CacheKey => AreaDeContactoCacheKeys.Lookup;

    protected override void Apply(AreaDeContactoDto dto, Db.AreasDeContacto entity) => dto.ApplyTo(entity);

    protected override AreaDeContactoDisplay ToDisplay(Db.AreasDeContacto entity) => entity.ToDisplay();
}
