// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Caja;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Caja;

public static partial class CajaPlanillaAjusteMappings
{
    public static CajaPlanillaAjusteDisplay ToDisplay(this Db.CajasPlanillasAjustes entity) => new()
    {
        IdCajaPlanillaAjuste = entity.IdCajaPlanillaAjuste,
        IdPlanillaCaja = entity.IdPlanillaCaja,
        IdPlanillaCajaDetalle = entity.IdPlanillaCajaDetalle,
        IdTipo = entity.IdTipo,
        IdUsuario = entity.IdUsuario,
        PuntoVenta = entity.PuntoVenta,
        Numero = entity.Numero,
        FechaEmision = entity.FechaEmision,
        IdItem = entity.IdItem,
        Descripcion = entity.Descripcion,
        Total = entity.Total,
        IdEstado = entity.IdEstado,
        IdSucursal = entity.IdSucursal,
    };
}
