// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Caja;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.Caja;

public static partial class CajaPlanillaMappings
{
    public static CajaPlanillaDisplay ToDisplay(this Db.CajaPlanillas entity) => new()
    {
        IdPlanillaCaja = entity.IdPlanillaCaja,
        PuntoVenta = entity.PuntoVenta,
        IdEmpresa = entity.IdEmpresa,
        FechaApertura = entity.FechaApertura,
        FechaCierre = entity.FechaCierre,
        IdUsuario = entity.IdUsuario,
        SaldoInicial = entity.SaldoInicial,
        TotalIngresos = entity.TotalIngresos,
        TotalEgresos = entity.TotalEgresos,
        TotalRendido = entity.TotalRendido,
        Diferencia = entity.Diferencia,
        Estado = entity.Estado,
        IdSucursal = entity.IdSucursal,
    };
}
