// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Sistema;
using API.SERVICE.Mappings.Sistema;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Sistema;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Sistema;

public interface IGetUsuarioListUseCase
{
    Task<PagedResult<UsuarioDisplay>> ExecuteAsync(UsuarioFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetUsuarioListUseCase(IUsuarioRepository repository)
    : GetListUseCaseBase<Db.Usuarios, UsuarioFilter, UsuarioDisplay>(repository), IGetUsuarioListUseCase
{
    protected override UsuarioDisplay ToDisplay(Db.Usuarios entity) => entity.ToDisplay();
}

public interface IGetUsuarioByIdUseCase
{
    Task<UsuarioDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetUsuarioByIdUseCase(IUsuarioRepository repository)
    : GetByIdUseCaseBase<Db.Usuarios, int, UsuarioFilter, UsuarioDisplay>(repository), IGetUsuarioByIdUseCase
{
    protected override string EntityName => "Usuario";

    protected override UsuarioDisplay ToDisplay(Db.Usuarios entity) => entity.ToDisplay();
}
