// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Sistema;
using API.SERVICE.Mappings.Sistema;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Sistema;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Sistema;

public interface IGetUsuarioSucursalListUseCase
{
    Task<PagedResult<UsuarioSucursalDisplay>> ExecuteAsync(UsuarioSucursalFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetUsuarioSucursalListUseCase(IUsuarioSucursalRepository repository)
    : GetListUseCaseBase<Db.UsuariosSucursales, UsuarioSucursalFilter, UsuarioSucursalDisplay>(repository), IGetUsuarioSucursalListUseCase
{
    protected override UsuarioSucursalDisplay ToDisplay(Db.UsuariosSucursales entity) => entity.ToDisplay();
}

public interface IGetUsuarioSucursalByIdUseCase
{
    Task<UsuarioSucursalDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetUsuarioSucursalByIdUseCase(IUsuarioSucursalRepository repository)
    : GetByIdUseCaseBase<Db.UsuariosSucursales, int, UsuarioSucursalFilter, UsuarioSucursalDisplay>(repository), IGetUsuarioSucursalByIdUseCase
{
    protected override string EntityName => "UsuarioSucursal";

    protected override UsuarioSucursalDisplay ToDisplay(Db.UsuariosSucursales entity) => entity.ToDisplay();
}

public interface ICreateUsuarioSucursalUseCase
{
    Task<UsuarioSucursalDisplay> ExecuteAsync(UsuarioSucursalDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateUsuarioSucursalUseCase(IUsuarioSucursalRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.UsuariosSucursales, int, UsuarioSucursalFilter, UsuarioSucursalDto, UsuarioSucursalDisplay>(repository, cache), ICreateUsuarioSucursalUseCase
{
    protected override string EntityName => "UsuarioSucursal";

    protected override Db.UsuariosSucursales ToEntity(UsuarioSucursalDto dto) => dto.ToEntity();

    protected override UsuarioSucursalDisplay ToDisplay(Db.UsuariosSucursales entity) => entity.ToDisplay();
}

public interface IDeleteUsuarioSucursalUseCase
{
    Task ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class DeleteUsuarioSucursalUseCase(IUsuarioSucursalRepository repository, IRedisCacheService cache)
    : DeleteUseCaseBase<Db.UsuariosSucursales, int, UsuarioSucursalFilter>(repository, cache), IDeleteUsuarioSucursalUseCase
{
    protected override string EntityName => "UsuarioSucursal";
}
