// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Compras;
using API.SERVICE.Models.Compras;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Compras;

public sealed partial class DocumentoProveedorDetalleRepository : EfRepository<Db.DocumentosProveedorDetalle, long, DocumentoProveedorDetalleFilter>, IDocumentoProveedorDetalleRepository
{
    public DocumentoProveedorDetalleRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.DocumentosProveedorDetalle> ApplyFilter(IQueryable<Db.DocumentosProveedorDetalle> query, DocumentoProveedorDetalleFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        if (filter.IdDocumentoProveedor is not null)
            query = query.Where(x => x.IdDocumentoProveedor == filter.IdDocumentoProveedor);

        if (filter.IdItem is not null)
            query = query.Where(x => x.IdItem == filter.IdItem);

        if (filter.IdImpuestoIva is not null)
            query = query.Where(x => x.IdImpuestoIva == filter.IdImpuestoIva);

        if (filter.IdListaPrecio is not null)
            query = query.Where(x => x.IdListaPrecio == filter.IdListaPrecio);

        return query;
    }

    protected override IOrderedQueryable<Db.DocumentosProveedorDetalle> ApplyDefaultOrder(IQueryable<Db.DocumentosProveedorDetalle> query) =>
        query.OrderByDescending(x => x.IdDocumentoProveedorDetalle);
}
