// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Compras;
using API.SERVICE.Models.Compras;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Compras;

public sealed partial class DocumentoProveedorRemitoDetalleRepository : EfRepository<Db.DocumentosProveedorRemitosDetalle, int, DocumentoProveedorRemitoDetalleFilter>, IDocumentoProveedorRemitoDetalleRepository
{
    public DocumentoProveedorRemitoDetalleRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.DocumentosProveedorRemitosDetalle> ApplyFilter(IQueryable<Db.DocumentosProveedorRemitosDetalle> query, DocumentoProveedorRemitoDetalleFilter filter)
    {
        if (filter.IdDocumentoProveedorRemito is not null)
            query = query.Where(x => x.IdDocumentoProveedorRemito == filter.IdDocumentoProveedorRemito);

        if (filter.IdItem is not null)
            query = query.Where(x => x.IdItem == filter.IdItem);

        if (filter.IdDocumentoProveedor is not null)
            query = query.Where(x => x.IdDocumentoProveedor == filter.IdDocumentoProveedor);

        if (filter.IdRemito is not null)
            query = query.Where(x => x.IdRemito == filter.IdRemito);

        return query;
    }

    protected override IOrderedQueryable<Db.DocumentosProveedorRemitosDetalle> ApplyDefaultOrder(IQueryable<Db.DocumentosProveedorRemitosDetalle> query) =>
        query.OrderByDescending(x => x.IdDocumentoProveeorRemitoDetalle);
}
