// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Mappings.Ventas;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Ventas;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Ventas;

public interface IGetDocumentoClienteObservacionListUseCase
{
    Task<PagedResult<DocumentoClienteObservacionDisplay>> ExecuteAsync(DocumentoClienteObservacionFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteObservacionListUseCase(IDocumentoClienteObservacionRepository repository)
    : GetListUseCaseBase<Db.DocumentosClienteObservaciones, DocumentoClienteObservacionFilter, DocumentoClienteObservacionDisplay>(repository), IGetDocumentoClienteObservacionListUseCase
{
    protected override DocumentoClienteObservacionDisplay ToDisplay(Db.DocumentosClienteObservaciones entity) => entity.ToDisplay();
}

public interface IGetDocumentoClienteObservacionByIdUseCase
{
    Task<DocumentoClienteObservacionDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteObservacionByIdUseCase(IDocumentoClienteObservacionRepository repository)
    : GetByIdUseCaseBase<Db.DocumentosClienteObservaciones, int, DocumentoClienteObservacionFilter, DocumentoClienteObservacionDisplay>(repository), IGetDocumentoClienteObservacionByIdUseCase
{
    protected override string EntityName => "DocumentoClienteObservacion";

    protected override DocumentoClienteObservacionDisplay ToDisplay(Db.DocumentosClienteObservaciones entity) => entity.ToDisplay();
}

public interface ICreateDocumentoClienteObservacionUseCase
{
    Task<DocumentoClienteObservacionDisplay> ExecuteAsync(DocumentoClienteObservacionDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateDocumentoClienteObservacionUseCase(IDocumentoClienteObservacionRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.DocumentosClienteObservaciones, int, DocumentoClienteObservacionFilter, DocumentoClienteObservacionDto, DocumentoClienteObservacionDisplay>(repository, cache), ICreateDocumentoClienteObservacionUseCase
{
    protected override string EntityName => "DocumentoClienteObservacion";

    protected override Db.DocumentosClienteObservaciones ToEntity(DocumentoClienteObservacionDto dto) => dto.ToEntity();

    protected override DocumentoClienteObservacionDisplay ToDisplay(Db.DocumentosClienteObservaciones entity) => entity.ToDisplay();
}

public interface IUpdateDocumentoClienteObservacionUseCase
{
    Task<DocumentoClienteObservacionDisplay> ExecuteAsync(int id, DocumentoClienteObservacionDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateDocumentoClienteObservacionUseCase(IDocumentoClienteObservacionRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.DocumentosClienteObservaciones, int, DocumentoClienteObservacionFilter, DocumentoClienteObservacionDto, DocumentoClienteObservacionDisplay>(repository, cache), IUpdateDocumentoClienteObservacionUseCase
{
    protected override string EntityName => "DocumentoClienteObservacion";

    protected override void Apply(DocumentoClienteObservacionDto dto, Db.DocumentosClienteObservaciones entity) => dto.ApplyTo(entity);

    protected override DocumentoClienteObservacionDisplay ToDisplay(Db.DocumentosClienteObservaciones entity) => entity.ToDisplay();
}
