// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Mappings.Ventas;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Ventas;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Ventas;

public interface IGetDocumentoClienteRemitoListUseCase
{
    Task<PagedResult<DocumentoClienteRemitoDisplay>> ExecuteAsync(DocumentoClienteRemitoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteRemitoListUseCase(IDocumentoClienteRemitoRepository repository)
    : GetListUseCaseBase<Db.DocumentosClienteRemitos, DocumentoClienteRemitoFilter, DocumentoClienteRemitoDisplay>(repository), IGetDocumentoClienteRemitoListUseCase
{
    protected override DocumentoClienteRemitoDisplay ToDisplay(Db.DocumentosClienteRemitos entity) => entity.ToDisplay();
}

public interface IGetDocumentoClienteRemitoByIdUseCase
{
    Task<DocumentoClienteRemitoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteRemitoByIdUseCase(IDocumentoClienteRemitoRepository repository)
    : GetByIdUseCaseBase<Db.DocumentosClienteRemitos, int, DocumentoClienteRemitoFilter, DocumentoClienteRemitoDisplay>(repository), IGetDocumentoClienteRemitoByIdUseCase
{
    protected override string EntityName => "DocumentoClienteRemito";

    protected override DocumentoClienteRemitoDisplay ToDisplay(Db.DocumentosClienteRemitos entity) => entity.ToDisplay();
}
