// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Mappings.Ventas;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Ventas;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Ventas;

public interface IGetDocumentoClienteQrListUseCase
{
    Task<PagedResult<DocumentoClienteQrDisplay>> ExecuteAsync(DocumentoClienteQrFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteQrListUseCase(IDocumentoClienteQrRepository repository)
    : GetListUseCaseBase<Db.DocumentosClienteQr, DocumentoClienteQrFilter, DocumentoClienteQrDisplay>(repository), IGetDocumentoClienteQrListUseCase
{
    protected override DocumentoClienteQrDisplay ToDisplay(Db.DocumentosClienteQr entity) => entity.ToDisplay();
}

public interface IGetDocumentoClienteQrByIdUseCase
{
    Task<DocumentoClienteQrDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteQrByIdUseCase(IDocumentoClienteQrRepository repository)
    : GetByIdUseCaseBase<Db.DocumentosClienteQr, int, DocumentoClienteQrFilter, DocumentoClienteQrDisplay>(repository), IGetDocumentoClienteQrByIdUseCase
{
    protected override string EntityName => "DocumentoClienteQr";

    protected override DocumentoClienteQrDisplay ToDisplay(Db.DocumentosClienteQr entity) => entity.ToDisplay();
}
