// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Mappings.Ventas;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Ventas;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Ventas;

public interface IGetDocumentoClienteRelacionListUseCase
{
    Task<PagedResult<DocumentoClienteRelacionDisplay>> ExecuteAsync(DocumentoClienteRelacionFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteRelacionListUseCase(IDocumentoClienteRelacionRepository repository)
    : GetListUseCaseBase<Db.DocumentosClienteRelacion, DocumentoClienteRelacionFilter, DocumentoClienteRelacionDisplay>(repository), IGetDocumentoClienteRelacionListUseCase
{
    protected override DocumentoClienteRelacionDisplay ToDisplay(Db.DocumentosClienteRelacion entity) => entity.ToDisplay();
}

public interface IGetDocumentoClienteRelacionByIdUseCase
{
    Task<DocumentoClienteRelacionDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteRelacionByIdUseCase(IDocumentoClienteRelacionRepository repository)
    : GetByIdUseCaseBase<Db.DocumentosClienteRelacion, int, DocumentoClienteRelacionFilter, DocumentoClienteRelacionDisplay>(repository), IGetDocumentoClienteRelacionByIdUseCase
{
    protected override string EntityName => "DocumentoClienteRelacion";

    protected override DocumentoClienteRelacionDisplay ToDisplay(Db.DocumentosClienteRelacion entity) => entity.ToDisplay();
}
