// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Mappings.Ventas;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Ventas;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Ventas;

public interface IGetDocumentoClienteListUseCase
{
    Task<PagedResult<DocumentoClienteDisplay>> ExecuteAsync(DocumentoClienteFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteListUseCase(IDocumentoClienteRepository repository)
    : GetListUseCaseBase<Db.DocumentosCliente, DocumentoClienteFilter, DocumentoClienteDisplay>(repository), IGetDocumentoClienteListUseCase
{
    protected override DocumentoClienteDisplay ToDisplay(Db.DocumentosCliente entity) => entity.ToDisplay();
}

public interface IGetDocumentoClienteByIdUseCase
{
    Task<DocumentoClienteDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteByIdUseCase(IDocumentoClienteRepository repository)
    : GetByIdUseCaseBase<Db.DocumentosCliente, int, DocumentoClienteFilter, DocumentoClienteDisplay>(repository), IGetDocumentoClienteByIdUseCase
{
    protected override string EntityName => "DocumentoCliente";

    protected override DocumentoClienteDisplay ToDisplay(Db.DocumentosCliente entity) => entity.ToDisplay();
}
