// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Mappings.Ventas;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Ventas;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Ventas;

public interface IGetDocumentoClienteOtroTributoListUseCase
{
    Task<PagedResult<DocumentoClienteOtroTributoDisplay>> ExecuteAsync(DocumentoClienteOtroTributoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteOtroTributoListUseCase(IDocumentoClienteOtroTributoRepository repository)
    : GetListUseCaseBase<Db.DocumentosClientesOtrosTributos, DocumentoClienteOtroTributoFilter, DocumentoClienteOtroTributoDisplay>(repository), IGetDocumentoClienteOtroTributoListUseCase
{
    protected override DocumentoClienteOtroTributoDisplay ToDisplay(Db.DocumentosClientesOtrosTributos entity) => entity.ToDisplay();
}

public interface IGetDocumentoClienteOtroTributoByIdUseCase
{
    Task<DocumentoClienteOtroTributoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoClienteOtroTributoByIdUseCase(IDocumentoClienteOtroTributoRepository repository)
    : GetByIdUseCaseBase<Db.DocumentosClientesOtrosTributos, int, DocumentoClienteOtroTributoFilter, DocumentoClienteOtroTributoDisplay>(repository), IGetDocumentoClienteOtroTributoByIdUseCase
{
    protected override string EntityName => "DocumentoClienteOtroTributo";

    protected override DocumentoClienteOtroTributoDisplay ToDisplay(Db.DocumentosClientesOtrosTributos entity) => entity.ToDisplay();
}
