// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Models.Bancos;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Bancos;

public sealed partial class BancoCuentaRepository : EfRepository<Db.BancosCuentas, int, BancoCuentaFilter>, IBancoCuentaRepository
{
    public BancoCuentaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.BancosCuentas> ApplyFilter(IQueryable<Db.BancosCuentas> query, BancoCuentaFilter filter)
    {
        if (filter.IdBanco is not null)
            query = query.Where(x => x.IdBanco == filter.IdBanco);

        if (filter.IdBancoSucursal is not null)
            query = query.Where(x => x.IdBancoSucursal == filter.IdBancoSucursal);

        if (filter.IdCuentaTipo is not null)
            query = query.Where(x => x.IdCuentaTipo == filter.IdCuentaTipo);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        return query;
    }

    protected override IOrderedQueryable<Db.BancosCuentas> ApplyDefaultOrder(IQueryable<Db.BancosCuentas> query) =>
        query.OrderByDescending(x => x.IdBancoCuenta);
}
