// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Models.Bancos;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Bancos;

public sealed partial class ConciliacionBancariaRepository : EfRepository<Db.ConciliacionBancaria, int, ConciliacionBancariaFilter>, IConciliacionBancariaRepository
{
    public ConciliacionBancariaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.ConciliacionBancaria> ApplyFilter(IQueryable<Db.ConciliacionBancaria> query, ConciliacionBancariaFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Numero != null && x.Numero.Contains(q)));
        }

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        if (filter.IdPuntoVenta is not null)
            query = query.Where(x => x.IdPuntoVenta == filter.IdPuntoVenta);

        if (filter.IdBancoCuenta is not null)
            query = query.Where(x => x.IdBancoCuenta == filter.IdBancoCuenta);

        if (filter.IdTipo is not null)
            query = query.Where(x => x.IdTipo == filter.IdTipo);

        if (filter.IdBanco is not null)
            query = query.Where(x => x.IdBanco == filter.IdBanco);

        if (filter.IdSucursal is not null)
            query = query.Where(x => x.IdSucursal == filter.IdSucursal);

        if (filter.IdUsuario is not null)
            query = query.Where(x => x.IdUsuario == filter.IdUsuario);

        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        if (filter.IdPlanillaCaja is not null)
            query = query.Where(x => x.IdPlanillaCaja == filter.IdPlanillaCaja);

        if (filter.IdTipoAjuste is not null)
            query = query.Where(x => x.IdTipoAjuste == filter.IdTipoAjuste);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        if (filter.FechaEmisionDesde is not null)
            query = query.Where(x => x.FechaEmision >= filter.FechaEmisionDesde.Value);

        if (filter.FechaEmisionHasta is not null)
        {
            var hasta = filter.FechaEmisionHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaEmision < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.ConciliacionBancaria> ApplyDefaultOrder(IQueryable<Db.ConciliacionBancaria> query) =>
        query.OrderByDescending(x => x.IdConciliacionBancaria);
}
