// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Bancos;
using API.SERVICE.Models.Bancos;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Bancos;

public sealed partial class TarjetaRepository : EfRepository<Db.Tarjetas, int, TarjetaFilter>, ITarjetaRepository
{
    public TarjetaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Tarjetas> ApplyFilter(IQueryable<Db.Tarjetas> query, TarjetaFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        if (filter.IdEstado is not null)
            query = query.Where(x => x.IdEstado == filter.IdEstado);

        return query;
    }

    protected override IOrderedQueryable<Db.Tarjetas> ApplyDefaultOrder(IQueryable<Db.Tarjetas> query) =>
        query.OrderBy(x => x.Descripcion);
}
