// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Miscelaneas;
using API.SERVICE.Models.Miscelaneas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Miscelaneas;

public sealed partial class AreaDeContactoRepository : EfRepository<Db.AreasDeContacto, int, AreaDeContactoFilter>, IAreaDeContactoRepository
{
    public AreaDeContactoRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.AreasDeContacto> ApplyFilter(IQueryable<Db.AreasDeContacto> query, AreaDeContactoFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        if (filter.IdEstado is not null)
            query = query.Where(x => x.IdEstado == filter.IdEstado);

        return query;
    }

    protected override IOrderedQueryable<Db.AreasDeContacto> ApplyDefaultOrder(IQueryable<Db.AreasDeContacto> query) =>
        query.OrderBy(x => x.Descripcion);
}
