// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Miscelaneas;
using API.SERVICE.Models.Miscelaneas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Miscelaneas;

public sealed partial class EstadoRepository : EfRepository<Db.Estados, int, EstadoFilter>, IEstadoRepository
{
    public EstadoRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Estados> ApplyFilter(IQueryable<Db.Estados> query, EstadoFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q))
                || (x.Nombre != null && x.Nombre.Contains(q)));
        }

        if (filter.Activo is not null)
            query = query.Where(x => x.Activo == filter.Activo);

        return query;
    }

    protected override IOrderedQueryable<Db.Estados> ApplyDefaultOrder(IQueryable<Db.Estados> query) =>
        query.OrderBy(x => x.Descripcion);
}
