// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Miscelaneas;
using API.SERVICE.Models.Miscelaneas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Miscelaneas;

public sealed partial class MotivoRepository : EfRepository<Db.Motivos, int, MotivoFilter>, IMotivoRepository
{
    public MotivoRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Motivos> ApplyFilter(IQueryable<Db.Motivos> query, MotivoFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        return query;
    }

    protected override IOrderedQueryable<Db.Motivos> ApplyDefaultOrder(IQueryable<Db.Motivos> query) =>
        query.OrderBy(x => x.Descripcion);
}
