// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Models.Ventas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Ventas;

public sealed partial class DocumentoClienteQrRepository : EfRepository<Db.DocumentosClienteQr, int, DocumentoClienteQrFilter>, IDocumentoClienteQrRepository
{
    public DocumentoClienteQrRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.DocumentosClienteQr> ApplyFilter(IQueryable<Db.DocumentosClienteQr> query, DocumentoClienteQrFilter filter)
    {
        if (filter.IdDocumentoCliente is not null)
            query = query.Where(x => x.IdDocumentoCliente == filter.IdDocumentoCliente);

        return query;
    }

    protected override IOrderedQueryable<Db.DocumentosClienteQr> ApplyDefaultOrder(IQueryable<Db.DocumentosClienteQr> query) =>
        query.OrderByDescending(x => x.IdDocumentoClienteQr);
}
