// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Models.Ventas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Ventas;

public sealed partial class DocumentoClienteOtroTributoRepository : EfRepository<Db.DocumentosClientesOtrosTributos, int, DocumentoClienteOtroTributoFilter>, IDocumentoClienteOtroTributoRepository
{
    public DocumentoClienteOtroTributoRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.DocumentosClientesOtrosTributos> ApplyFilter(IQueryable<Db.DocumentosClientesOtrosTributos> query, DocumentoClienteOtroTributoFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Detalle != null && x.Detalle.Contains(q)));
        }

        if (filter.IdDocumentoCliente is not null)
            query = query.Where(x => x.IdDocumentoCliente == filter.IdDocumentoCliente);

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        if (filter.IdOtroTributo is not null)
            query = query.Where(x => x.IdOtroTributo == filter.IdOtroTributo);

        return query;
    }

    protected override IOrderedQueryable<Db.DocumentosClientesOtrosTributos> ApplyDefaultOrder(IQueryable<Db.DocumentosClientesOtrosTributos> query) =>
        query.OrderByDescending(x => x.IdDocumentoClienteOtroTributo);
}
