// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Models.Ventas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Ventas;

public sealed partial class DocumentoClienteRemitoRepository : EfRepository<Db.DocumentosClienteRemitos, int, DocumentoClienteRemitoFilter>, IDocumentoClienteRemitoRepository
{
    public DocumentoClienteRemitoRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.DocumentosClienteRemitos> ApplyFilter(IQueryable<Db.DocumentosClienteRemitos> query, DocumentoClienteRemitoFilter filter)
    {
        if (filter.IdDocumentoCliente is not null)
            query = query.Where(x => x.IdDocumentoCliente == filter.IdDocumentoCliente);

        if (filter.IdRemito is not null)
            query = query.Where(x => x.IdRemito == filter.IdRemito);

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        return query;
    }

    protected override IOrderedQueryable<Db.DocumentosClienteRemitos> ApplyDefaultOrder(IQueryable<Db.DocumentosClienteRemitos> query) =>
        query.OrderByDescending(x => x.IdDocumentoClienteRemito);
}
