// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Models.Ventas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Ventas;

public sealed partial class DocumentoClienteRelacionRepository : EfRepository<Db.DocumentosClienteRelacion, int, DocumentoClienteRelacionFilter>, IDocumentoClienteRelacionRepository
{
    public DocumentoClienteRelacionRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.DocumentosClienteRelacion> ApplyFilter(IQueryable<Db.DocumentosClienteRelacion> query, DocumentoClienteRelacionFilter filter)
    {
        if (filter.IdDocumentoCliente1 is not null)
            query = query.Where(x => x.IdDocumentoCliente1 == filter.IdDocumentoCliente1);

        if (filter.IdDocumentoCliente2 is not null)
            query = query.Where(x => x.IdDocumentoCliente2 == filter.IdDocumentoCliente2);

        return query;
    }

    protected override IOrderedQueryable<Db.DocumentosClienteRelacion> ApplyDefaultOrder(IQueryable<Db.DocumentosClienteRelacion> query) =>
        query.OrderByDescending(x => x.IdDocumentoClienteRelacion);
}
