// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Models.Ventas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Ventas;

public sealed partial class DocumentoClienteRemitoDetalleRepository : EfRepository<Db.DocumentosClienteRemitosDetalle, int, DocumentoClienteRemitoDetalleFilter>, IDocumentoClienteRemitoDetalleRepository
{
    public DocumentoClienteRemitoDetalleRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.DocumentosClienteRemitosDetalle> ApplyFilter(IQueryable<Db.DocumentosClienteRemitosDetalle> query, DocumentoClienteRemitoDetalleFilter filter)
    {
        if (filter.IdDocumentoClienteRemito is not null)
            query = query.Where(x => x.IdDocumentoClienteRemito == filter.IdDocumentoClienteRemito);

        if (filter.IdItem is not null)
            query = query.Where(x => x.IdItem == filter.IdItem);

        if (filter.IdDocumentoCliente is not null)
            query = query.Where(x => x.IdDocumentoCliente == filter.IdDocumentoCliente);

        if (filter.IdRemito is not null)
            query = query.Where(x => x.IdRemito == filter.IdRemito);

        return query;
    }

    protected override IOrderedQueryable<Db.DocumentosClienteRemitosDetalle> ApplyDefaultOrder(IQueryable<Db.DocumentosClienteRemitosDetalle> query) =>
        query.OrderByDescending(x => x.IdDocumentoClienteRemitoDetalle);
}
