// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Ventas;
using API.SERVICE.Models.Ventas;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Ventas;

public sealed partial class DocumentoClienteObservacionRepository : EfRepository<Db.DocumentosClienteObservaciones, int, DocumentoClienteObservacionFilter>, IDocumentoClienteObservacionRepository
{
    public DocumentoClienteObservacionRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.DocumentosClienteObservaciones> ApplyFilter(IQueryable<Db.DocumentosClienteObservaciones> query, DocumentoClienteObservacionFilter filter)
    {
        if (filter.IdDocumentoCliente is not null)
            query = query.Where(x => x.IdDocumentoCliente == filter.IdDocumentoCliente);

        return query;
    }

    protected override IOrderedQueryable<Db.DocumentosClienteObservaciones> ApplyDefaultOrder(IQueryable<Db.DocumentosClienteObservaciones> query) =>
        query.OrderByDescending(x => x.IdDocumentoClienteObservacion);
}
