// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.Sistema;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Interfaces.Sistema;

/// <summary>Persistencia de dbo.UsuariosSucursales.</summary>
public partial interface IUsuarioSucursalRepository : global::API.SERVICE.Interfaces.IReadRepository<Db.UsuariosSucursales, int, UsuarioSucursalFilter>
{
}
