// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Caja;

/// <summary>Salida de dbo.CajaPlanillas.</summary>
public sealed partial class CajaPlanillaDisplay
{
    public int IdPlanillaCaja { get; init; }
    public string? PuntoVenta { get; init; }
    public int? IdEmpresa { get; init; }
    public DateTime? FechaApertura { get; init; }
    public DateTime? FechaCierre { get; init; }
    public int? IdUsuario { get; init; }
    public decimal? SaldoInicial { get; init; }
    public decimal? TotalIngresos { get; init; }
    public decimal? TotalEgresos { get; init; }
    public decimal? TotalRendido { get; init; }
    public decimal? Diferencia { get; init; }
    public int? Estado { get; init; }
    public int? IdSucursal { get; init; }
}

/// <summary>Filtros del listado de dbo.CajaPlanillas.</summary>
public sealed partial class CajaPlanillaFilter : PagedQuery
{
    public int? IdEmpresa { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdSucursal { get; set; }

    public int? Estado { get; set; }

    /// <summary>FechaApertura desde (inclusive).</summary>
    public DateTime? FechaAperturaDesde { get; set; }

    /// <summary>FechaApertura hasta (inclusive, día completo).</summary>
    public DateTime? FechaAperturaHasta { get; set; }
}
