// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Models.CuentasCorrientes;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Mappings.CuentasCorrientes;

public static partial class EntidadCtaCteMappings
{
    public static EntidadCtaCteDisplay ToDisplay(this Db.EntidadesCtaCte entity) => new()
    {
        IdEntidadCtaCte = entity.IdEntidadCtaCte,
        IdEntidad = entity.IdEntidad,
        IdComprobanteTipo = entity.IdComprobanteTipo,
        IdComprobante = entity.IdComprobante,
        Concepto = entity.Concepto,
        NroCuota = entity.NroCuota,
        Total = entity.Total,
        Saldo = entity.Saldo,
        Cancelado = entity.Cancelado,
        Fecha = entity.Fecha,
        FechaVencimiento = entity.FechaVencimiento,
        FechaAnulacion = entity.FechaAnulacion,
        FechaPago = entity.FechaPago,
        InteresAplicado = entity.InteresAplicado,
        Estado = entity.Estado,
        Total2 = entity.Total2,
        IdEmpresa = entity.IdEmpresa,
        IdSucursal = entity.IdSucursal,
        IdUsuario = entity.IdUsuario,
    };
}
