// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Entidades;
using API.SERVICE.Mappings.Entidades;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Entidades;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Entidades;

public static class EntidadCategoriaCacheKeys
{
    public static readonly string Lookup = CacheKeys.For("Entidades", "EntidadCategoria", "lookup");
}

public interface IGetEntidadCategoriaListUseCase
{
    Task<PagedResult<EntidadCategoriaDisplay>> ExecuteAsync(EntidadCategoriaFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCategoriaListUseCase(IEntidadCategoriaRepository repository)
    : GetListUseCaseBase<Db.EntidadesCategorias, EntidadCategoriaFilter, EntidadCategoriaDisplay>(repository), IGetEntidadCategoriaListUseCase
{
    protected override EntidadCategoriaDisplay ToDisplay(Db.EntidadesCategorias entity) => entity.ToDisplay();
}

public interface IGetEntidadCategoriaByIdUseCase
{
    Task<EntidadCategoriaDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCategoriaByIdUseCase(IEntidadCategoriaRepository repository)
    : GetByIdUseCaseBase<Db.EntidadesCategorias, int, EntidadCategoriaFilter, EntidadCategoriaDisplay>(repository), IGetEntidadCategoriaByIdUseCase
{
    protected override string EntityName => "EntidadCategoria";

    protected override EntidadCategoriaDisplay ToDisplay(Db.EntidadesCategorias entity) => entity.ToDisplay();
}

public interface IGetEntidadCategoriaLookupUseCase
{
    Task<IReadOnlyList<EntidadCategoriaDisplay>> ExecuteAsync(CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadCategoriaLookupUseCase(IEntidadCategoriaRepository repository, IRedisCacheService cache)
    : GetLookupUseCaseBase<Db.EntidadesCategorias, int, EntidadCategoriaFilter, EntidadCategoriaDisplay>(repository, cache), IGetEntidadCategoriaLookupUseCase
{
    protected override string CacheKey => EntidadCategoriaCacheKeys.Lookup;

    protected override EntidadCategoriaDisplay ToDisplay(Db.EntidadesCategorias entity) => entity.ToDisplay();
}

public interface ICreateEntidadCategoriaUseCase
{
    Task<EntidadCategoriaDisplay> ExecuteAsync(EntidadCategoriaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateEntidadCategoriaUseCase(IEntidadCategoriaRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.EntidadesCategorias, int, EntidadCategoriaFilter, EntidadCategoriaDto, EntidadCategoriaDisplay>(repository, cache), ICreateEntidadCategoriaUseCase
{
    protected override string EntityName => "EntidadCategoria";

    protected override string? CacheKey => EntidadCategoriaCacheKeys.Lookup;

    protected override Db.EntidadesCategorias ToEntity(EntidadCategoriaDto dto) => dto.ToEntity();

    protected override EntidadCategoriaDisplay ToDisplay(Db.EntidadesCategorias entity) => entity.ToDisplay();
}

public interface IUpdateEntidadCategoriaUseCase
{
    Task<EntidadCategoriaDisplay> ExecuteAsync(int id, EntidadCategoriaDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateEntidadCategoriaUseCase(IEntidadCategoriaRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.EntidadesCategorias, int, EntidadCategoriaFilter, EntidadCategoriaDto, EntidadCategoriaDisplay>(repository, cache), IUpdateEntidadCategoriaUseCase
{
    protected override string EntityName => "EntidadCategoria";

    protected override string? CacheKey => EntidadCategoriaCacheKeys.Lookup;

    protected override void Apply(EntidadCategoriaDto dto, Db.EntidadesCategorias entity) => dto.ApplyTo(entity);

    protected override EntidadCategoriaDisplay ToDisplay(Db.EntidadesCategorias entity) => entity.ToDisplay();
}
