// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Entidades;
using API.SERVICE.Mappings.Entidades;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Entidades;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Entidades;

public interface IGetEntidadAreaDeContactoListUseCase
{
    Task<PagedResult<EntidadAreaDeContactoDisplay>> ExecuteAsync(EntidadAreaDeContactoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadAreaDeContactoListUseCase(IEntidadAreaDeContactoRepository repository)
    : GetListUseCaseBase<Db.EntidadesAreasDeContacto, EntidadAreaDeContactoFilter, EntidadAreaDeContactoDisplay>(repository), IGetEntidadAreaDeContactoListUseCase
{
    protected override EntidadAreaDeContactoDisplay ToDisplay(Db.EntidadesAreasDeContacto entity) => entity.ToDisplay();
}

public interface IGetEntidadAreaDeContactoByIdUseCase
{
    Task<EntidadAreaDeContactoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadAreaDeContactoByIdUseCase(IEntidadAreaDeContactoRepository repository)
    : GetByIdUseCaseBase<Db.EntidadesAreasDeContacto, int, EntidadAreaDeContactoFilter, EntidadAreaDeContactoDisplay>(repository), IGetEntidadAreaDeContactoByIdUseCase
{
    protected override string EntityName => "EntidadAreaDeContacto";

    protected override EntidadAreaDeContactoDisplay ToDisplay(Db.EntidadesAreasDeContacto entity) => entity.ToDisplay();
}

public interface ICreateEntidadAreaDeContactoUseCase
{
    Task<EntidadAreaDeContactoDisplay> ExecuteAsync(EntidadAreaDeContactoDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateEntidadAreaDeContactoUseCase(IEntidadAreaDeContactoRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.EntidadesAreasDeContacto, int, EntidadAreaDeContactoFilter, EntidadAreaDeContactoDto, EntidadAreaDeContactoDisplay>(repository, cache), ICreateEntidadAreaDeContactoUseCase
{
    protected override string EntityName => "EntidadAreaDeContacto";

    protected override Db.EntidadesAreasDeContacto ToEntity(EntidadAreaDeContactoDto dto) => dto.ToEntity();

    protected override EntidadAreaDeContactoDisplay ToDisplay(Db.EntidadesAreasDeContacto entity) => entity.ToDisplay();
}

public interface IUpdateEntidadAreaDeContactoUseCase
{
    Task<EntidadAreaDeContactoDisplay> ExecuteAsync(int id, EntidadAreaDeContactoDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateEntidadAreaDeContactoUseCase(IEntidadAreaDeContactoRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.EntidadesAreasDeContacto, int, EntidadAreaDeContactoFilter, EntidadAreaDeContactoDto, EntidadAreaDeContactoDisplay>(repository, cache), IUpdateEntidadAreaDeContactoUseCase
{
    protected override string EntityName => "EntidadAreaDeContacto";

    protected override void Apply(EntidadAreaDeContactoDto dto, Db.EntidadesAreasDeContacto entity) => dto.ApplyTo(entity);

    protected override EntidadAreaDeContactoDisplay ToDisplay(Db.EntidadesAreasDeContacto entity) => entity.ToDisplay();
}

public interface IDeleteEntidadAreaDeContactoUseCase
{
    Task ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class DeleteEntidadAreaDeContactoUseCase(IEntidadAreaDeContactoRepository repository, IRedisCacheService cache)
    : DeleteUseCaseBase<Db.EntidadesAreasDeContacto, int, EntidadAreaDeContactoFilter>(repository, cache), IDeleteEntidadAreaDeContactoUseCase
{
    protected override string EntityName => "EntidadAreaDeContacto";
}
