// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Entidades;
using API.SERVICE.Mappings.Entidades;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Entidades;
using API.SERVICE.Services.Cache;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Entidades;

public interface IGetEntidadDireccionListUseCase
{
    Task<PagedResult<EntidadDireccionDisplay>> ExecuteAsync(EntidadDireccionFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadDireccionListUseCase(IEntidadDireccionRepository repository)
    : GetListUseCaseBase<Db.EntidadesDirecciones, EntidadDireccionFilter, EntidadDireccionDisplay>(repository), IGetEntidadDireccionListUseCase
{
    protected override EntidadDireccionDisplay ToDisplay(Db.EntidadesDirecciones entity) => entity.ToDisplay();
}

public interface IGetEntidadDireccionByIdUseCase
{
    Task<EntidadDireccionDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetEntidadDireccionByIdUseCase(IEntidadDireccionRepository repository)
    : GetByIdUseCaseBase<Db.EntidadesDirecciones, int, EntidadDireccionFilter, EntidadDireccionDisplay>(repository), IGetEntidadDireccionByIdUseCase
{
    protected override string EntityName => "EntidadDireccion";

    protected override EntidadDireccionDisplay ToDisplay(Db.EntidadesDirecciones entity) => entity.ToDisplay();
}

public interface ICreateEntidadDireccionUseCase
{
    Task<EntidadDireccionDisplay> ExecuteAsync(EntidadDireccionDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class CreateEntidadDireccionUseCase(IEntidadDireccionRepository repository, IRedisCacheService cache)
    : CreateUseCaseBase<Db.EntidadesDirecciones, int, EntidadDireccionFilter, EntidadDireccionDto, EntidadDireccionDisplay>(repository, cache), ICreateEntidadDireccionUseCase
{
    protected override string EntityName => "EntidadDireccion";

    protected override Db.EntidadesDirecciones ToEntity(EntidadDireccionDto dto) => dto.ToEntity();

    protected override EntidadDireccionDisplay ToDisplay(Db.EntidadesDirecciones entity) => entity.ToDisplay();
}

public interface IUpdateEntidadDireccionUseCase
{
    Task<EntidadDireccionDisplay> ExecuteAsync(int id, EntidadDireccionDto dto, CancellationToken cancellationToken = default);
}

public sealed partial class UpdateEntidadDireccionUseCase(IEntidadDireccionRepository repository, IRedisCacheService cache)
    : UpdateUseCaseBase<Db.EntidadesDirecciones, int, EntidadDireccionFilter, EntidadDireccionDto, EntidadDireccionDisplay>(repository, cache), IUpdateEntidadDireccionUseCase
{
    protected override string EntityName => "EntidadDireccion";

    protected override void Apply(EntidadDireccionDto dto, Db.EntidadesDirecciones entity) => dto.ApplyTo(entity);

    protected override EntidadDireccionDisplay ToDisplay(Db.EntidadesDirecciones entity) => entity.ToDisplay();
}

public interface IDeleteEntidadDireccionUseCase
{
    Task ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class DeleteEntidadDireccionUseCase(IEntidadDireccionRepository repository, IRedisCacheService cache)
    : DeleteUseCaseBase<Db.EntidadesDirecciones, int, EntidadDireccionFilter>(repository, cache), IDeleteEntidadDireccionUseCase
{
    protected override string EntityName => "EntidadDireccion";
}
