// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Sistema;
using API.SERVICE.Models.Sistema;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Sistema;

public sealed partial class ConsultaRepository : EfRepository<Db.Consultas, int, ConsultaFilter>, IConsultaRepository
{
    public ConsultaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Consultas> ApplyFilter(IQueryable<Db.Consultas> query, ConsultaFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => x.Nombre.Contains(q)
                || x.Email.Contains(q));
        }

        if (filter.IdLocalidad is not null)
            query = query.Where(x => x.IdLocalidad == filter.IdLocalidad.Value);

        if (filter.IdProvincia is not null)
            query = query.Where(x => x.IdProvincia == filter.IdProvincia.Value);

        if (filter.FechaDesde is not null)
            query = query.Where(x => x.Fecha >= filter.FechaDesde.Value);

        if (filter.FechaHasta is not null)
        {
            var hasta = filter.FechaHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.Fecha < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.Consultas> ApplyDefaultOrder(IQueryable<Db.Consultas> query) =>
        query.OrderByDescending(x => x.IdConsulta);
}
