// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Sistema;
using API.SERVICE.Models.Sistema;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Sistema;

public sealed partial class ParametroJsonRepository : EfRepository<Db.ParametroJson, int, ParametroJsonFilter>, IParametroJsonRepository
{
    public ParametroJsonRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.ParametroJson> ApplyFilter(IQueryable<Db.ParametroJson> query, ParametroJsonFilter filter)
    {
        return query;
    }

    protected override IOrderedQueryable<Db.ParametroJson> ApplyDefaultOrder(IQueryable<Db.ParametroJson> query) =>
        query.OrderByDescending(x => x.Id);
}
