// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Sistema;
using API.SERVICE.Models.Sistema;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Sistema;

public sealed partial class ParametroRepository : EfRepository<Db.Parametros, int, ParametroFilter>, IParametroRepository
{
    public ParametroRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Parametros> ApplyFilter(IQueryable<Db.Parametros> query, ParametroFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q))
                || (x.Nombre != null && x.Nombre.Contains(q)));
        }

        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        if (filter.Activo is not null)
            query = query.Where(x => x.Activo == filter.Activo);

        return query;
    }

    protected override IOrderedQueryable<Db.Parametros> ApplyDefaultOrder(IQueryable<Db.Parametros> query) =>
        query.OrderBy(x => x.Descripcion);
}
