// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Sistema;
using API.SERVICE.Models.Sistema;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Sistema;

public sealed partial class UsuarioSucursalRepository : EfRepository<Db.UsuariosSucursales, int, UsuarioSucursalFilter>, IUsuarioSucursalRepository
{
    public UsuarioSucursalRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.UsuariosSucursales> ApplyFilter(IQueryable<Db.UsuariosSucursales> query, UsuarioSucursalFilter filter)
    {
        if (filter.IdUsuario is not null)
            query = query.Where(x => x.IdUsuario == filter.IdUsuario);

        if (filter.IdSucursal is not null)
            query = query.Where(x => x.IdSucursal == filter.IdSucursal);

        return query;
    }

    protected override IOrderedQueryable<Db.UsuariosSucursales> ApplyDefaultOrder(IQueryable<Db.UsuariosSucursales> query) =>
        query.OrderByDescending(x => x.IdUsuarioSucursal);
}
