// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Reportes;

/// <summary>Salida de dbo.EntidadesCtaCteReporte.</summary>
public sealed partial class EntidadCtaCteReporteDisplay
{
    public int IdEntidadCtaCteReporte { get; init; }
    public string? Nro { get; init; }
    public string? Concepto { get; init; }
    public DateTime? Fecha { get; init; }
    public DateTime? Vencimiento { get; init; }
    public decimal? Debe { get; init; }
    public decimal? Haber { get; init; }
    public decimal? Total { get; init; }
    public int? IdComprobanteTipo { get; init; }
    public int? IdComprobante { get; init; }
    public string? Observaciones { get; init; }
    public string? Estado { get; init; }
}

/// <summary>Filtros del listado de dbo.EntidadesCtaCteReporte.</summary>
public sealed partial class EntidadCtaCteReporteFilter : PagedQuery
{
    public int? IdComprobanteTipo { get; set; }

    public int? IdComprobante { get; set; }

    /// <summary>Fecha desde (inclusive).</summary>
    public DateTime? FechaDesde { get; set; }

    /// <summary>Fecha hasta (inclusive, día completo).</summary>
    public DateTime? FechaHasta { get; set; }
}
