// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Afip;
using API.SERVICE.Mappings.Afip;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Afip;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Afip;

public interface IGetLibroIvaCompraListUseCase
{
    Task<PagedResult<LibroIvaCompraDisplay>> ExecuteAsync(LibroIvaCompraFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetLibroIvaCompraListUseCase(ILibroIvaCompraRepository repository)
    : GetListUseCaseBase<Db.LibroIvaCompra, LibroIvaCompraFilter, LibroIvaCompraDisplay>(repository), IGetLibroIvaCompraListUseCase
{
    protected override LibroIvaCompraDisplay ToDisplay(Db.LibroIvaCompra entity) => entity.ToDisplay();
}

public interface IGetLibroIvaCompraByIdUseCase
{
    Task<LibroIvaCompraDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetLibroIvaCompraByIdUseCase(ILibroIvaCompraRepository repository)
    : GetByIdUseCaseBase<Db.LibroIvaCompra, int, LibroIvaCompraFilter, LibroIvaCompraDisplay>(repository), IGetLibroIvaCompraByIdUseCase
{
    protected override string EntityName => "LibroIvaCompra";

    protected override LibroIvaCompraDisplay ToDisplay(Db.LibroIvaCompra entity) => entity.ToDisplay();
}
