// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Afip;
using API.SERVICE.Mappings.Afip;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Afip;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Afip;

public interface IGetTxtVentaAlicuotaListUseCase
{
    Task<PagedResult<TxtVentaAlicuotaDisplay>> ExecuteAsync(TxtVentaAlicuotaFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetTxtVentaAlicuotaListUseCase(ITxtVentaAlicuotaRepository repository)
    : GetListUseCaseBase<Db.TxtVentasAlicuotas, TxtVentaAlicuotaFilter, TxtVentaAlicuotaDisplay>(repository), IGetTxtVentaAlicuotaListUseCase
{
    protected override TxtVentaAlicuotaDisplay ToDisplay(Db.TxtVentasAlicuotas entity) => entity.ToDisplay();
}

public interface IGetTxtVentaAlicuotaByIdUseCase
{
    Task<TxtVentaAlicuotaDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetTxtVentaAlicuotaByIdUseCase(ITxtVentaAlicuotaRepository repository)
    : GetByIdUseCaseBase<Db.TxtVentasAlicuotas, int, TxtVentaAlicuotaFilter, TxtVentaAlicuotaDisplay>(repository), IGetTxtVentaAlicuotaByIdUseCase
{
    protected override string EntityName => "TxtVentaAlicuota";

    protected override TxtVentaAlicuotaDisplay ToDisplay(Db.TxtVentasAlicuotas entity) => entity.ToDisplay();
}
