// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Geografia;
using API.SERVICE.Models.Geografia;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Geografia;

public sealed partial class ProvinciaRepository : EfRepository<Db.Provincias, int, ProvinciaFilter>, IProvinciaRepository
{
    public ProvinciaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.Provincias> ApplyFilter(IQueryable<Db.Provincias> query, ProvinciaFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        if (filter.IdPais is not null)
            query = query.Where(x => x.IdPais == filter.IdPais);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        return query;
    }

    protected override IOrderedQueryable<Db.Provincias> ApplyDefaultOrder(IQueryable<Db.Provincias> query) =>
        query.OrderBy(x => x.Descripcion);
}
