// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Sistema;

/// <summary>Salida de dbo.Consultas.</summary>
public sealed partial class ConsultaDisplay
{
    public int IdConsulta { get; init; }
    public string Nombre { get; init; } = string.Empty;
    public string Telefono { get; init; } = string.Empty;
    public string Email { get; init; } = string.Empty;
    public string NombreEmpresa { get; init; } = string.Empty;
    public string RubroEmpresa { get; init; } = string.Empty;
    public string Sucursales { get; init; } = string.Empty;
    public int IdLocalidad { get; init; }
    public int IdProvincia { get; init; }
    public string Observaciones { get; init; } = string.Empty;
    public DateTime Fecha { get; init; }
}

/// <summary>Filtros del listado de dbo.Consultas.</summary>
public sealed partial class ConsultaFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Nombre, Email.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdLocalidad { get; set; }

    public int? IdProvincia { get; set; }

    /// <summary>Fecha desde (inclusive).</summary>
    public DateTime? FechaDesde { get; set; }

    /// <summary>Fecha hasta (inclusive, día completo).</summary>
    public DateTime? FechaHasta { get; set; }
}
