// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Sistema;

/// <summary>Salida de dbo.Parametros.</summary>
public sealed partial class ParametroDisplay
{
    public int IdParametro { get; init; }
    public string? Categoria { get; init; }
    public string? Nombre { get; init; }
    public string? Valor { get; init; }
    public string? Descripcion { get; init; }
    public int? Orden { get; init; }
    public int? IdEmpresa { get; init; }
    public bool? Activo { get; init; }
}

/// <summary>Entrada de alta/modificación de dbo.Parametros.</summary>
public sealed partial class ParametroDto
{
    [MaxLength(50)]
    public string? Categoria { get; set; }

    [MaxLength(50)]
    public string? Nombre { get; set; }

    [MaxLength(500)]
    public string? Valor { get; set; }

    [MaxLength(50)]
    public string? Descripcion { get; set; }

    public int? Orden { get; set; }

    public int? IdEmpresa { get; set; }

    public bool? Activo { get; set; }
}

/// <summary>Filtros del listado de dbo.Parametros.</summary>
public sealed partial class ParametroFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Descripcion, Nombre.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdEmpresa { get; set; }

    public bool? Activo { get; set; }
}
