// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Sistema;

/// <summary>Salida de dbo.ParametroJson.</summary>
public sealed partial class ParametroJsonDisplay
{
    public int Id { get; init; }
    public string? Json { get; init; }
}

/// <summary>Filtros del listado de dbo.ParametroJson.</summary>
public sealed partial class ParametroJsonFilter : PagedQuery
{
}
