// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using System.ComponentModel.DataAnnotations;
using API.SERVICE.Models.Common;

namespace API.SERVICE.Models.Sistema;

/// <summary>Salida de dbo.Usuarios.</summary>
public sealed partial class UsuarioDisplay
{
    public int IdUsuario { get; init; }
    public string? Nombre { get; init; }
    public string? Email { get; init; }
    public string? Usuario { get; init; }
    public Guid? UserId { get; init; }
    public string? Imagen { get; init; }
    public int? IdSucursal { get; init; }
    public int? IdEstado { get; init; }
}

/// <summary>Filtros del listado de dbo.Usuarios.</summary>
public sealed partial class UsuarioFilter : PagedQuery
{
    /// <summary>Búsqueda parcial en Nombre, Email, Usuario.</summary>
    [MaxLength(100)]
    public string? Q { get; set; }

    public int? IdSucursal { get; set; }

    public int? IdEstado { get; set; }
}
