// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Compras;
using API.SERVICE.Mappings.Compras;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Compras;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Compras;

public interface IGetDocumentoProveedorOtroTributoListUseCase
{
    Task<PagedResult<DocumentoProveedorOtroTributoDisplay>> ExecuteAsync(DocumentoProveedorOtroTributoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoProveedorOtroTributoListUseCase(IDocumentoProveedorOtroTributoRepository repository)
    : GetListUseCaseBase<Db.DocumentosProveedorOtrosTributos, DocumentoProveedorOtroTributoFilter, DocumentoProveedorOtroTributoDisplay>(repository), IGetDocumentoProveedorOtroTributoListUseCase
{
    protected override DocumentoProveedorOtroTributoDisplay ToDisplay(Db.DocumentosProveedorOtrosTributos entity) => entity.ToDisplay();
}

public interface IGetDocumentoProveedorOtroTributoByIdUseCase
{
    Task<DocumentoProveedorOtroTributoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoProveedorOtroTributoByIdUseCase(IDocumentoProveedorOtroTributoRepository repository)
    : GetByIdUseCaseBase<Db.DocumentosProveedorOtrosTributos, int, DocumentoProveedorOtroTributoFilter, DocumentoProveedorOtroTributoDisplay>(repository), IGetDocumentoProveedorOtroTributoByIdUseCase
{
    protected override string EntityName => "DocumentoProveedorOtroTributo";

    protected override DocumentoProveedorOtroTributoDisplay ToDisplay(Db.DocumentosProveedorOtrosTributos entity) => entity.ToDisplay();
}
