// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Compras;
using API.SERVICE.Mappings.Compras;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Compras;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Compras;

public interface IGetDocumentoProveedorListUseCase
{
    Task<PagedResult<DocumentoProveedorDisplay>> ExecuteAsync(DocumentoProveedorFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoProveedorListUseCase(IDocumentoProveedorRepository repository)
    : GetListUseCaseBase<Db.DocumentosProveedor, DocumentoProveedorFilter, DocumentoProveedorDisplay>(repository), IGetDocumentoProveedorListUseCase
{
    protected override DocumentoProveedorDisplay ToDisplay(Db.DocumentosProveedor entity) => entity.ToDisplay();
}

public interface IGetDocumentoProveedorByIdUseCase
{
    Task<DocumentoProveedorDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoProveedorByIdUseCase(IDocumentoProveedorRepository repository)
    : GetByIdUseCaseBase<Db.DocumentosProveedor, int, DocumentoProveedorFilter, DocumentoProveedorDisplay>(repository), IGetDocumentoProveedorByIdUseCase
{
    protected override string EntityName => "DocumentoProveedor";

    protected override DocumentoProveedorDisplay ToDisplay(Db.DocumentosProveedor entity) => entity.ToDisplay();
}
