// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.SERVICE.Interfaces.Compras;
using API.SERVICE.Mappings.Compras;
using API.SERVICE.Models.Common;
using API.SERVICE.Models.Compras;
using API.SERVICE.UseCases.Crud;
using Db = global::API.DA.Entities;

namespace API.SERVICE.UseCases.Compras;

public interface IGetDocumentoProveedorRemitoListUseCase
{
    Task<PagedResult<DocumentoProveedorRemitoDisplay>> ExecuteAsync(DocumentoProveedorRemitoFilter filter, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoProveedorRemitoListUseCase(IDocumentoProveedorRemitoRepository repository)
    : GetListUseCaseBase<Db.DocumentosProveedorRemitos, DocumentoProveedorRemitoFilter, DocumentoProveedorRemitoDisplay>(repository), IGetDocumentoProveedorRemitoListUseCase
{
    protected override DocumentoProveedorRemitoDisplay ToDisplay(Db.DocumentosProveedorRemitos entity) => entity.ToDisplay();
}

public interface IGetDocumentoProveedorRemitoByIdUseCase
{
    Task<DocumentoProveedorRemitoDisplay> ExecuteAsync(int id, CancellationToken cancellationToken = default);
}

public sealed partial class GetDocumentoProveedorRemitoByIdUseCase(IDocumentoProveedorRemitoRepository repository)
    : GetByIdUseCaseBase<Db.DocumentosProveedorRemitos, int, DocumentoProveedorRemitoFilter, DocumentoProveedorRemitoDisplay>(repository), IGetDocumentoProveedorRemitoByIdUseCase
{
    protected override string EntityName => "DocumentoProveedorRemito";

    protected override DocumentoProveedorRemitoDisplay ToDisplay(Db.DocumentosProveedorRemitos entity) => entity.ToDisplay();
}
