// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Caja;
using API.SERVICE.Models.Caja;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Caja;

public sealed partial class CajaPlanillaRepository : EfRepository<Db.CajaPlanillas, int, CajaPlanillaFilter>, ICajaPlanillaRepository
{
    public CajaPlanillaRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.CajaPlanillas> ApplyFilter(IQueryable<Db.CajaPlanillas> query, CajaPlanillaFilter filter)
    {
        if (filter.IdEmpresa is not null)
            query = query.Where(x => x.IdEmpresa == filter.IdEmpresa);

        if (filter.IdUsuario is not null)
            query = query.Where(x => x.IdUsuario == filter.IdUsuario);

        if (filter.IdSucursal is not null)
            query = query.Where(x => x.IdSucursal == filter.IdSucursal);

        if (filter.Estado is not null)
            query = query.Where(x => x.Estado == filter.Estado);

        if (filter.FechaAperturaDesde is not null)
            query = query.Where(x => x.FechaApertura >= filter.FechaAperturaDesde.Value);

        if (filter.FechaAperturaHasta is not null)
        {
            var hasta = filter.FechaAperturaHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.FechaApertura < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.CajaPlanillas> ApplyDefaultOrder(IQueryable<Db.CajaPlanillas> query) =>
        query.OrderByDescending(x => x.IdPlanillaCaja);
}
