// <auto-generated>
// Generado por tools/ApiGenerator a partir del modelo EF y entities.config.
// NO editar: los cambios se pierden al regenerar. Extender con un archivo partial sin ".g".
// </auto-generated>
#nullable enable

using API.DA.DbContexts;
using API.SERVICE.Interfaces.Caja;
using API.SERVICE.Models.Caja;
using API.SERVICE.Repositories.Base;
using Db = global::API.DA.Entities;

namespace API.SERVICE.Repositories.Caja;

public sealed partial class CajaPlanillaDetalleRepository : EfRepository<Db.CajasPlanillasDetalle, long, CajaPlanillaDetalleFilter>, ICajaPlanillaDetalleRepository
{
    public CajaPlanillaDetalleRepository(ElRenacerDbContext context) : base(context) { }

    protected override IQueryable<Db.CajasPlanillasDetalle> ApplyFilter(IQueryable<Db.CajasPlanillasDetalle> query, CajaPlanillaDetalleFilter filter)
    {
        if (!string.IsNullOrWhiteSpace(filter.Q))
        {
            var q = filter.Q.Trim();
            query = query.Where(x => (x.Descripcion != null && x.Descripcion.Contains(q)));
        }

        if (filter.IdCajaPlanilla is not null)
            query = query.Where(x => x.IdCajaPlanilla == filter.IdCajaPlanilla);

        if (filter.IdElementoCobro is not null)
            query = query.Where(x => x.IdElementoCobro == filter.IdElementoCobro);

        if (filter.IdComprobanteTipo is not null)
            query = query.Where(x => x.IdComprobanteTipo == filter.IdComprobanteTipo);

        if (filter.IdComprobante is not null)
            query = query.Where(x => x.IdComprobante == filter.IdComprobante);

        if (filter.FechaDesde is not null)
            query = query.Where(x => x.Fecha >= filter.FechaDesde.Value);

        if (filter.FechaHasta is not null)
        {
            var hasta = filter.FechaHasta.Value.Date.AddDays(1);
            query = query.Where(x => x.Fecha < hasta);
        }

        return query;
    }

    protected override IOrderedQueryable<Db.CajasPlanillasDetalle> ApplyDefaultOrder(IQueryable<Db.CajasPlanillasDetalle> query) =>
        query.OrderByDescending(x => x.IdCajaPlanillaDetalle);
}
